// <auto-generated />
// Source SHA256 665e753fe1cc48bc06a2b438d6f07c6beea2b1098174983f1effbe784ac8d7ea
namespace TypeScript.Compiler.Binding;
[Flags]
public enum CheckFlags : uint
{
    None = 0,
    Instantiated = 1 << 0,
    SyntheticProperty = 1 << 1,
    SyntheticMethod = 1 << 2,
    Readonly = 1 << 3,
    ReadPartial = 1 << 4,
    WritePartial = 1 << 5,
    HasNonUniformType = 1 << 6,
    HasLiteralType = 1 << 7,
    ContainsPublic = 1 << 8,
    ContainsProtected = 1 << 9,
    ContainsPrivate = 1 << 10,
    ContainsWritePublic = 1 << 11,
    ContainsWriteProtected = 1 << 12,
    ContainsWritePrivate = 1 << 13,
    ContainsStatic = 1 << 14,
    Late = 1 << 15,
    ReverseMapped = 1 << 16,
    OptionalParameter = 1 << 17,
    RestParameter = 1 << 18,
    DeferredType = 1 << 19,
    HasNeverType = 1 << 20,
    Mapped = 1 << 21,
    StripOptional = 1 << 22,
    Unresolved = 1 << 23,
    IsDiscriminantComputed = 1 << 24,
    IsDiscriminant = 1 << 25,
    IndexSymbol = 1 << 26,
    Synthetic = SyntheticProperty | SyntheticMethod,
    NonUniformAndLiteral = HasNonUniformType | HasLiteralType,
    Partial = ReadPartial | WritePartial,
}
