// <auto-generated />
// Source SHA256 6fa8526bbedad06a4e37d8e7957a12cdf8a049daf5bfb7353ffbee4c5cb41d2d
namespace TypeScript.Compiler.Binding;
[Flags]
public enum FlowFlags : uint
{
    Unreachable = 1 << 0,
    Start = 1 << 1,
    BranchLabel = 1 << 2,
    LoopLabel = 1 << 3,
    Assignment = 1 << 4,
    TrueCondition = 1 << 5,
    FalseCondition = 1 << 6,
    SwitchClause = 1 << 7,
    ArrayMutation = 1 << 8,
    Call = 1 << 9,
    ReduceLabel = 1 << 10,
    Referenced = 1 << 11,
    Shared = 1 << 12,
    Label = BranchLabel | LoopLabel,
    Condition = TrueCondition | FalseCondition,
}
