export function declarationCases() {
    const samples = [
        ['variables', 'const a = 1, b = "text", c = true; let d = 1; var e; export {a,b,c,d,e};'],
        ['global', 'const a = 1; let b = [1, 2]; function f(x = 1) { return x; } class C { x = 1; }'],
        ['functions', 'export function f<T extends string = "a">(x: T, y = 1, ...rest: string[]) { return {x, y, rest}; }'],
        ['overloads', 'export function f(x: number): number; export function f(x: string): string; export function f(x: any) { return x; }'],
        ['private', 'export class C { #x = 1; public x!: number; private y = 1; protected z = "x"; static readonly k = 1; private m(x: string): number { return 1; } }'],
        ['accessors', 'export class C { get x() { return 1; } set x(value) {} private get y() { return 1; } private set y(value) {} get z(this: C) { return "x"; } }'],
        ['parameters', 'export class C { constructor(public x: number, private y = "a", readonly z?: boolean) {} }'],
        ['private-constructor', 'export class C { private constructor(x: number) {} protected m<T>(x: T) { return x; } }'],
        ['interface', 'export interface I<T extends object = {}> extends Other<T> { readonly x?: T; f?<U>(x: U): U; (x: T): T; new(x: T): I<T>; [key: string]: unknown; } interface Other<T> { a: T; }'],
        ['types', 'export type A<T> = T extends infer U ? U[] : never; export type B = [a: number, b?: string, ...c: boolean[]]; export type C<T> = { readonly [P in keyof T as `get${string & P}`]?: T[P] };'],
        ['destructure', 'export const {a, b: c} = {a: 1, b: "b"}; export let [d, e = 2] = [1, 2];'],
        ['destructure-default', 'export const {a = 1, b: {c = "c"}} = {a: 2, b: {c: "d"}};'],
        ['destructure-param', 'export function f({a = 1, b: c = "c"} = {}) { return [a, c]; }'],
        ['enums', 'export enum E { A, B = A + 1, C = "x", D = -1, N = 0/0, I = 1/0 } export const enum F { A = E.A }'],
        ['namespace', 'export namespace A { export const x = 1; const y = 2; export interface I {x: typeof y} }'],
        ['namespace-nested', 'namespace A.B.C { export const x = 1; } export {A};'],
        ['namespace-alias', 'namespace A { export namespace Q { export const x = 1; } import B = Q; import C = B; export import D = C; } export {A};'],
        ['namespace-export', 'namespace A { const x = 1; export {x}; } export {A};'],
        ['declare-namespace', 'declare namespace A { const x: number; namespace B { const y: string; } } export {A};'],
        ['declare-module', 'declare module "mod" { const x: number; export = x; }'],
        ['augment', 'export {}; declare global { interface Window { x: number; } }'],
        ['default-value', 'export default {a: 1, b: "x"};'],
        ['default-literal', 'export default "café";'],
        ['default-function', 'export default function f(x = 1) { return x; }'],
        ['default-arrow', 'export default (x: number) => x + 1;'],
        ['export-equals', 'const x = {a: 1}; export = x;'],
        ['default-class', 'export default class { readonly x = 1; constructor(public y: string) {} }'],
        ['class-expression', 'export default (class Thing { x = 1; next(): Thing { return this; } });'],
        ['class-heritage', 'class B { x = 1; } export class C extends B implements I { y = "x"; } interface I { y: string; }'],
        ['class-mixin', 'declare function mix(): {new(): {a: number}}; export class C extends mix() { b = true; }'],
        ['extends-null', 'export class C extends null { x = 1; }'],
        ['computed', 'declare const key: unique symbol; export class C { [key] = 1; ["text"] = 2; [1] = "one"; }'],
        ['computed-dynamic', 'declare const name: string; export class C { [name] = 1; [(() => "x")()] = 2; }'],
        ['using', 'declare function get(): any; export const x = 1; using y = get(); export {y};'],
        ['strip-internal', '/** visible */ export class C { /** @internal */ x = 1; y = 2; /** @internal */ m() {} } /** @internal */ export const hidden = 1; export const shown = 2;'],
        ['strip-parameter', 'export class C { constructor(/** @internal */ public x = 1, /** @internal */ public y = 2, public z = 3) {} }'],
        ['comments', '// header\n/** function doc */\nexport function f(/** parameter */ x = 1) { // body\n return x; }\n/** tail */'],
        ['private-return', 'class C { private x = 1; } export const c = new C(); export function f() { return c; }'],
        ['function-types', 'export type F<T> = <U extends T>(x: U, y?: T) => U; export type C = abstract new<T>(x: T) => {a: T};'],
        ['unresolved', 'export const a: Missing = null!; export function f(x: Other): Missing { return x; }'],
        ['imports-inferred', 'import {Shape, Other} from "./other"; declare const input: Shape; export function get() { return input; }'],
        ['imports-explicit', 'import type {Shape, Other} from "./other"; export interface I { shape: Shape; }'],
        ['imports-default', 'import Default, {Shape, Other} from "./other"; export function get(x: Default): Shape { return x; }'],
        ['imports-namespace', 'import * as NS from "./other"; export const value: NS.Shape = {x: 1};'],
        ['imports-side-effect', 'import "./other"; export const x = 1;'],
        ['imports-unused', 'import Default, {Other} from "./other"; export const x = 1;'],
        ['reexports', 'export type {Shape} from "./other"; export * from "./other"; export * as ns from "./other";'],
        ['import-type', 'export type Shape = import("./other").Shape; export const value: typeof import("./other") = null!;'],
        ['multiple-return', 'export function f(x: boolean) { if (x) return 1; return "a"; }'],
        ['inferred-return', 'export const one = 1; export function f() { return one; } export const make = () => one + 1;'],
        ['inferred-object', 'const x = 1; export const value = {x}; export const other = {...value, y: 2};'],
        ['inferred-arrays', 'const a = [1, 2]; export const x = [1, "x"]; export const y = [1, "x"] as const; export const z = [...a] as const;'],
        ['inferred-assertions', 'declare const any: any; export const a = any as {x: number}; export const b = {x: 1} satisfies {x: number};'],
        ['inferred-accessors', 'export class C { get x() { return {a: 1}; } set y(value) {} get z() { const value = 1; return value; } }'],
        ['optional-parameters', 'export function f(x = 1, y: string, z?: number) { return y; } export function g({x}: {x: number} = {x: 1}, y: number) { return x; }'],
        ['private-overloads', 'export class C { private f(x: number): number; private f(x: string): string; private f(x: any): any { return x; } constructor(x: number); constructor(x: any) {} }'],
        ['namespace-private', 'export namespace N { interface Hidden {x: number} export function f(): Hidden {return {x: 1}} } export const value = N.f();'],
        ['namespace-private-class', 'namespace N { class Hidden {private x = 1} export const value = new Hidden(); } export const value = N.value;'],
        ['this-type', 'export class C { value = {get: () => this}; get() { return {value: this}; } }'],
        ['unique-symbol', 'const key: unique symbol = Symbol(); export const value = {key}; export const own = Symbol();'],
        ['class-private-base', 'export const value = class {private x = 1; protected y = 2;};'],
        ['computed-signatures', 'declare const key: unique symbol; export interface I {[key](): number; [-1]: string; ["x"]: boolean;}'],
        ['static-constructor', 'export abstract class C {static {const x = 1;} abstract f<T extends object = {}>(x: T): T; public constructor() {}}'],
        ['namespace-merged', 'export function f() {} export namespace f { export const x = 1; } export enum E {A} export namespace E {export const x = 2;}'],
        ['readonly-literals', 'const x = "x"; export class C {readonly a = x; readonly b = -1; readonly c = 1n; readonly d = `a`; private readonly e = 2;}'],
        ['empty-declarations', 'export interface I {} export class C {} export enum E {} export namespace N {}'],
        ['invalid-jsdoc-types', 'export type A = ?string; export type B = !number; export type C = *; export type D = ...string;'],
    ];
    const cases = [];
    for (const [name, text] of samples) for (const isolatedDeclarations of [false, true]) for (const map of [false, true]) {
        cases.push({name: `${name}-${isolatedDeclarations}-${map}`, text, map,
            options: {strict: true, target: 'esnext', isolatedDeclarations, stripInternal: name.startsWith('strip-')},
            files: {'/source/other.ts': 'export interface Shape {x: number} export interface Other {y: string} export default class Default { x = 1; }'}});
    }
    const javascript = [
        ['cjs-value', 'module.exports = {a: 1, b: "x"};'],
        ['cjs-function', 'module.exports = function f(x) { return x + 1; };'],
        ['cjs-arrow', 'module.exports = (x = 1) => x;'],
        ['cjs-class', 'module.exports = class Thing { constructor(x = 1) { this.x = x; } m() { return this.x; } };'],
        ['cjs-named', 'exports.x = 1; exports.y = "x"; module.exports.z = true;'],
        ['cjs-alias', 'const x = 1; function f(x) { return x; } exports.x = x; exports.func = f;'],
        ['cjs-default', 'exports.default = {a: 1}; exports["strange-name"] = 2; exports["while"] = 3;'],
        ['cjs-collision', 'const x = "local"; exports.x = 1; exports.y = x;'],
        ['cjs-nested', 'if (true) { exports.x = 1; } function f() { module.exports.y = 2; } exports.x = 3;'],
        ['cjs-multiple', 'module.exports = 1; module.exports = "two";'],
        ['cjs-self-class', 'exports.C = class C { make() { return new C(); } };'],
        ['cjs-renamed-class', 'exports.C = class Inner { x = 1; };'],
        ['cjs-anonymous-class', 'exports.C = class { x = 1; }; exports["strange-name"] = class { y = 2; };'],
        ['cjs-extra', 'module.exports = function f(x) { return x; }; module.exports.extra = 1;'],
        ['cjs-define', 'Object.defineProperty(exports, "x", {value: 1}); Object.defineProperty(exports, "y", {get() { return "x"; }});'],
        ['require', 'const dep = require("./other"); exports.value = dep;'],
        ['require-destructure', 'const {value, other: renamed} = require("./other"); exports.value = value; exports.renamed = renamed;'],
        ['require-unused', 'const dep = require("./other"), other = 1; exports.other = other;'],
        ['expando-function', 'export function f(x = 1) { return x; } f.value = 1; f.other = "x";'],
        ['expando-arrow', 'export const f = (x = 1) => x; f.value = 1;'],
        ['expando-alias', 'const value = 1; export function f() {} f.value = value; f.other = "x";'],
        ['expando-alias-after-variable', 'const value = 1; export function f() {} f.first = "x"; f.value = value;'],
        ['expando-default', 'export default function f(x = 1) { return x; } f.value = 1;'],
        ['expando-collision', 'const value = 0; export function f() {} f.value = 1; f.other = 2;'],
        ['expando-late', 'function f(x = 1) { return x; } f.value = 1; export const alias = f;'],
        ['expando-recursive', 'export function f(x = 1) { return x; } f.recursive = () => f;'],
        ['expando-index', 'export function f() {} f["x"] = 1; f["a-b"] = 2; f["default"] = 3;'],
        ['this-properties', 'export class C { constructor(x = 1) { this.x = x; this["y"] = "x"; this[1] = true; } method() { this.z = 2; } static { this.value = 1; } }'],
        ['this-scopes', 'export class C { constructor() { this.x = 1; (() => { this.y = 2; })(); function f() { this.z = 3; } } static method() { this.value = 4; } }'],
        ['this-duplicate', 'export class C { x = 1; constructor() { this.x = 2; this.x = 3; } static x = 4; static { this.x = 5; } }'],
        ['this-computed-name', 'const key = "value"; export class C { [key] = 1; constructor() { this.key = 2; } }'],
        ['this-negative-key', 'export class C { [-1] = 1; constructor() { this[-1] = 2; this[-1] = 3; } }'],
        ['this-inherited', 'class B { get x() { return 1; } m() {} y = 1; } export class C extends B { constructor() { super(); this.x = 2; this.y = 3; this.z = "x"; } }'],
        ['jsdoc-function', '/** @template T @param {T} x @returns {T} */ export function f(x) { return x; }'],
        ['jsdoc-typedef', '/** @typedef {{x: number, y?: string}} Shape */\n/** @type {Shape} */ export const shape = {x: 1};'],
        ['jsdoc-types', '/** @type {?string} */ export let a; /** @type {!number} */ export let b; /** @param {...string} args */ export function f(...args) {}'],
        ['jsdoc-class', '/** @template T */ export class C { /** @param {T} x */ constructor(x) { /** property */ this.x = x; } /** @returns {T} */ get() { return this.x; } }'],
        ['jsdoc-properties', '/** @typedef {object} Shape\n * @property {number} x first\n * @property {string} [y] second\n */\n/** @type {Shape} */ export let value;'],
        ['jsdoc-import', '/** @import {Shape} from "./shape" */\n/** @param {Shape} x */ export function f(x) { return x; }'],
    ];
    for (const [name, text] of javascript) for (const map of [false, true]) {
        cases.push({name: `js-${name}-${map}`, file: '/source/input.js', text, map,
            options: {strict: true, allowJs: true, checkJs: true, target: 'esnext'},
            files: {'/source/other.js': 'exports.value = 1; exports.other = "x";', '/source/shape.ts': 'export interface Shape {x: number}'}});
        if (name.startsWith('expando-')) cases.push({name: `ts-${name}-${map}`, text, map, options: {strict: true, target: 'esnext', isolatedDeclarations: true}});
    }
    const references = [
        ['path', '/// <reference path="./other.ts" preserve="true" />\nexport const x = 1;', {}],
        ['path-extensionless', '/// <reference path="./other" preserve="true" />\nexport const x = 1;', {}],
        ['path-dts', '/// <reference path="./types.d.ts" preserve="true" />\nexport const x = 1;', {}],
        ['path-missing', '/// <reference path="./missing.ts" preserve="true" />\nexport const x = 1;', {}],
        ['path-unpreserved', '/// <reference path="./other.ts" />\nexport const x = 1;', {}],
        ['path-mts', '/// <reference path="./other.mts" preserve="true" />\nexport const x = 1;', {}],
        ['path-cts', '/// <reference path="./other.cts" preserve="true" />\nexport const x = 1;', {}],
        ['path-parent', '/// <reference path="../other.ts" preserve="true" />\nexport const x = 1;', {}],
        ['path-declaration-dir', '/// <reference path="./other.ts" preserve="true" />\nexport const x = 1;', {declarationDir: '/types'}],
        ['type-lib', '/// <reference types="example" preserve="true" resolution-mode="import" />\n/// <reference lib="es2020" preserve="true" />\nexport const x = 1;', {}],
        ['type-lib-unpreserved', '/// <reference types="example" />\n/// <reference lib="es2020" />\nexport const x = 1;', {}],
        ['no-default-lib', '/// <reference no-default-lib="true" />\nexport const x = 1;', {}],
    ];
    for (const [name, text, options] of references) for (const map of [false, true]) for (const removeComments of [false, true])
        cases.push({name: `reference-${name}-${map}-${removeComments}`, text, map, options: {removeComments, ...options},
            files: {'/source/other.ts': 'export const y = 1;', '/source/other.mts': 'export const y = 1;', '/source/other.cts': 'export const y = 1;',
                '/source/types.d.ts': 'declare const y: number;', '/other.ts': 'export const y = 1;'}});
    const documentationImports = [
        '/** @import {Shape} from "./shape" */', '/** @import {Shape} from "./shape"   */', '/** @import {Shape} from "./shape" description */',
        '/**\n * @import {Shape} from "./shape"\n */', '/** @import {Shape} from "./shape" with {"resolution-mode": "import"} */',
        '/** @import * as ns from "./shape" */', '/** @import Shape from "./shape" */', '/** @import {Shape}\n * from "./shape"\n * description\n */'
    ];
    for (const [index, comment] of documentationImports.entries()) for (const map of [false, true])
        cases.push({name: `jsdoc-import-form-${index}-${map}`, text: comment + '\n/** @param {' + (comment.includes('* as ns') ? 'ns.Shape' : 'Shape') + '} x */ export function f(x) { return x; }',
            file: '/source/input.js', map, options: {allowJs: true}, files: {'/source/shape.ts': 'export interface Shape { x: number } export default Shape;'}});
    return cases;
}
