// Repetitive Unicode property data only; regex grammar and recovery are handwritten.
import {
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";

const bytes = await readFile(path.join(root, "tsc/internal/scanner/unicodeproperties.go"));
const source = bytes.toString();
const lines = ["// <auto-generated />", `// Source SHA256 ${sha256(bytes)}`, "using System.Collections.Frozen;", "namespace TypeScript.Compiler.Syntax;", "internal static partial class RegularExpressionUnicodeProperties", "{"];
const aliases = source.match(/var nonBinaryUnicodeProperties = map\[string\]string\{([\s\S]*?)\n\}/)[1];
lines.push("    internal static readonly FrozenDictionary<string, string> NonBinary = new Dictionary<string, string>(StringComparer.Ordinal)", "    {");
for (const [, key, value] of aliases.matchAll(/"([^"]+)":\s*"([^"]+)"/g)) lines.push(`        ["${key}"] = "${value}",`);
lines.push("    }.ToFrozenDictionary(StringComparer.Ordinal);");
for (
    const [field, pattern] of [
        ["Binary", /var binaryUnicodeProperties = collections.NewSetFromItems\(([\s\S]*?)\n\)/],
        ["Strings", /var binaryUnicodePropertiesOfStrings = collections.NewSetFromItems\(([\s\S]*?)\n\)/],
        ["Script", /var scriptValues = collections.NewSetFromItems\(([\s\S]*?)\n\)/],
        ["GeneralCategory", /"General_Category": collections.NewSetFromItems\(([\s\S]*?)\n\s*\)/],
    ]
) {
    const values = [...source.match(pattern)[1].matchAll(/"([^"]+)"/g)].map(m => m[1]);
    if (!values.length) throw new Error(`No values for ${field}`);
    lines.push(`    internal static readonly FrozenSet<string> ${field} = new string[]`, "    {");
    for (let i = 0; i < values.length; i += 6) lines.push(`        ${values.slice(i, i + 6).map(v => JSON.stringify(v)).join(", ")},`);
    lines.push("    }.ToFrozenSet(StringComparer.Ordinal);");
}
lines.push("}");
const text = lines.join("\n") + "\n";
const target = path.join(root, "csharp/src/TypeScript.Compiler/Syntax/RegularExpressionUnicodeProperties.generated.cs");
if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw new Error("Stale regex Unicode properties");
}
else await writeFile(target, text);
