// The first generator slice deliberately emits kind identities and schema
// audit data only. A field omitted here is not silently treated as ported.
import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    json,
    root,
    sha256,
} from "./common.mjs";

const schemaPath = "tools/scripts/tsc/ast.json";
const source = await readFile(path.join(root, schemaPath));
const schema = JSON.parse(source);
const kinds = schema.kinds.elements.map(element => typeof element === "string" ? element : element.name).filter(Boolean);
const lines = ["// <auto-generated />", `// ${schemaPath}; SHA256 ${sha256(source)}`, "namespace TypeScript.Compiler.Syntax;", "", "public enum SyntaxKind : uint", "{"];
kinds.forEach((kind, value) => lines.push(`    ${kind} = ${value},`));
for (const marker of schema.kinds.markers) lines.push(`    ${marker.name} = ${marker.value},`);
lines.push("    NodeList = uint.MaxValue,", "}", "");
const generated = path.join(root, "csharp/src/TypeScript.Compiler/Syntax/SyntaxKind.generated.cs");
await mkdir(path.dirname(generated), { recursive: true });
if (process.argv.includes("--check")) {
    if ((await readFile(generated, "utf8")).replaceAll("\r\n", "\n") !== lines.join("\n")) throw new Error("Stale C# syntax kinds; run generate-schema.mjs");
}
else await writeFile(generated, lines.join("\n"));
const flags = [];
function audit(value, location = "$") {
    if (!value || typeof value !== "object") return;
    for (const [key, child] of Object.entries(value)) {
        if (["goOnly", "noGo", "noTS", "handWritten", "handWrittenVisitor", "noFactory", "private"].includes(key)) {
            flags.push({ location: `${location}.${key}`, value: child, disposition: "requires explicit C# field/hook mapping before syntax port completion" });
        }
        audit(child, `${location}.${key}`);
    }
}
audit(schema);
if (!process.argv.includes("--check")) {
    await json(path.join(root, "csharp/compatibility/schema.generated.json"), {
        source: schemaPath,
        sha256: sha256(source),
        kinds: kinds.length,
        definitions: Object.keys(schema.nodes.definitions),
        flags,
    });
}
console.log(`Verified ${kinds.length} kinds and ${flags.length} schema exceptions`);
