import {
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";
const snapshot = JSON.parse(await readFile(path.join(root, "csharp/data/locales.json"), "utf8"));
const data = snapshot.data;
const lines = ["// <auto-generated />", "#nullable enable", `// golang.org/x/text ${snapshot.version}; registry SHA256 ${sha256(JSON.stringify(data))}`, "using System.Collections.Frozen;", "", "namespace TypeScript.Compiler.Configuration;", "", "internal static partial class LocaleIdentifier", "{"];
for (const [name, values] of Object.entries(data)) {
    values.sort();
    lines.push(`    private static readonly FrozenSet<Utf8String> ${name} = Utf8String.Copy("""`);
    for (let i = 0; i < values.length; i += 24) lines.push("        " + values.slice(i, i + 24).join(" "));
    lines.push('        """u8).SplitAny(" \\t\\r\\n"u8, StringSplitOptions.RemoveEmptyEntries).ToFrozenSet(Utf8StringComparer.Ordinal);', "");
}
lines.pop();
lines.push("}", "");
const target = path.join(root, "csharp/src/TypeScript.Compiler/Configuration/LocaleIdentifier.generated.cs");
const text = lines.join("\n");
if (process.argv.includes("--check")) { if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error("Stale locale registry"); }
else await writeFile(target, text);
console.log(Object.fromEntries(Object.entries(data).map(([k, v]) => [k, v.length])));
