import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import { root } from "./common.mjs";
const groups = { Compiler: "declscompiler.go", Build: "declsbuild.go", Watch: "declswatch.go", TypeAcquisition: "declstypeacquisition.go" };
const maps = await readFile(path.join(root, "tsc/internal/tsoptions/enummaps.go"), "utf8");
const enumNames = { target: "targetOptionMap", module: "moduleOptionMap", moduleResolution: "moduleResolutionOptionMap", moduleDetection: "moduleDetectionOptionMap", jsx: "jsxOptionMap", newLine: "newLineOptionMap", lib: "LibMap", watchFile: "watchFileEnumMap", watchDirectory: "watchDirectoryEnumMap", fallbackPolling: "fallbackEnumMap" };
const enums = {};
const identities = {};
for (const [name, variable] of Object.entries(enumNames)) {
    const start = maps.indexOf(`var ${variable} = `);
    if (start < 0) throw new Error(`Missing enum ${variable}`);
    const section = maps.slice(start).split(/\r?\n\}\)/)[0];
    enums[name] = [...section.matchAll(/Key:\s*"([^"]+)"/g)].map(m => m[1]);
    identities[name] = [...section.matchAll(/Key:\s*"([^"]+)",\s*Value:\s*([^}\r\n]+)\}/g)].map(m => m[2].trim().replace(/,$/, ""));
    if (identities[name].length !== enums[name].length) throw new Error(`Unmapped enum values ${name}`);
}
const rows = [];
for (const [group, file] of Object.entries(groups)) {
    const text = await readFile(path.join(root, "tsc/internal/tsoptions", file), "utf8");
    for (const match of text.matchAll(/\bName:\s*"([^"]+)"/g)) {
        const name = match[1], start = text.lastIndexOf("{", match.index);
        const body = text.slice(start, text.indexOf("}", match.index));
        const rawKind = body.match(/Kind:\s*CommandLineOptionType(\w+)/)?.[1] ?? body.match(/Kind:\s*"(\w+)"/)?.[1];
        const kind = rawKind && rawKind[0].toUpperCase() + rawKind.slice(1);
        if (!kind) throw new Error(`Missing kind ${file}:${name}`);
        const short = body.match(/ShortName:\s*"([^"]+)"/)?.[1] ?? "";
        const flag = key => new RegExp(`${key}:\\s*true`).test(body);
        const vary = ["Boolean", "Enum"].includes(kind) && !flag("IsCommandLineOnly") && (/Affects\w+:\s*true/.test(body) || ["noEmit", "isolatedModules"].includes(name));
        const row = `        new(${JSON.stringify(name)}, ${JSON.stringify(short)}, OptionGroup.${group}, OptionKind.${kind}, ${flag("IsFilePath")}, ${flag("IsTSConfigOnly")}, ${flag("IsCommandLineOnly")}, [${(enums[name] ?? []).map(s => JSON.stringify(s)).join(", ")}], [${(identities[name] ?? []).map(s => JSON.stringify(s)).join(", ")}], ${vary}),`;
        rows.push(row);
        if (group === "Compiler" && match.index < text.indexOf("var optionsForCompiler")) rows.push(row.replace("OptionGroup.Compiler", "OptionGroup.Build"));
    }
}
const text = ["// <auto-generated />", "namespace TypeScript.Compiler.Configuration;", "public static partial class OptionDefinitions", "{", "    public static IReadOnlyList<OptionDefinition> All { get; } = Array.AsReadOnly<OptionDefinition>([", ...rows, "    ]);", "}", ""].join("\n");
const target = path.join(root, "csharp/src/TypeScript.Compiler/Configuration/Options.generated.cs");
await mkdir(path.dirname(target), { recursive: true });
if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw new Error("Stale options schema");
}
else await writeFile(target, text);
console.log(`Generated ${rows.length} option declarations`);
