import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";
const bytes = await readFile(path.join(root, "tsc/internal/stringutil/js_case_generated.go")), source = bytes.toString();
const lines = ["// <auto-generated />", "#nullable enable", "// Unicode 15.1.0, from the pinned TypeScript stringutil tables.", `// Source SHA256 ${sha256(bytes)}`, "using System.Collections.Frozen;", "using TypeScript.Compiler.Text;", "namespace TypeScript.Compiler.Semantics;", "internal static partial class JsCase", "{", "    private readonly record struct Mapping(Utf8String Lower, Utf8String Upper, Utf8String? FinalLower = null);", "    private static readonly FrozenDictionary<int, Mapping> Mappings = new Dictionary<int, Mapping>", "    {"];
let mappings = 0;
for (const m of source.matchAll(/^\s*(0x[0-9A-F]+):\s*\{lower: ("[^"]*"), upper: ("[^"]*")(?:, conditionalLower: ("[^"]*"))?, condition: specialCasingCondition\w+\},/gm)) {
    lines.push(`        [${m[1]}] = new(${m[2]}u8, ${m[3]}u8${m[4] ? ", Utf8String.Copy(" + m[4] + "u8)" : ""}),`);
    mappings++;
}
if (mappings < 2900) throw Error("Incomplete casing map");
lines.push("    }.ToFrozenDictionary();");
for (const [name, input] of [["Cased", "unicodeCasedRanges"], ["CaseIgnorable", "unicodeCaseIgnorableRanges"]]) {
    const start = source.indexOf(`var ${input} =`), end = source.indexOf("\nvar ", start + 1);
    const data = source.slice(start, end < 0 ? undefined : end);
    lines.push(`    private static ReadOnlySpan<int> ${name} =>`, "    [");
    for (const m of data.matchAll(/\{(0x[0-9A-F]+), (0x[0-9A-F]+), (\d+)\}/g)) lines.push(`        ${m[1]}, ${m[2]}, ${m[3]},`);
    lines.push("    ];");
}
lines.push("}", "");
const file = path.join(root, "csharp/src/TypeScript.Compiler/Semantics/JsCase.generated.cs"), text = lines.join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error(`Stale ${file}`);
}
else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, text);
}
