import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";

// Generate constant schemas only. Semantic algorithms are ported and reviewed separately.
const groups = {
    "types.go": ["TypeFlags", "ObjectFlags", "SignatureFlags", "ElementFlags", "AccessFlags", "IndexFlags", "VarianceFlags", "NodeCheckFlags", "TypePredicateKind", "SignatureKind", "Ternary", "ContextFlags"],
    "checker.go": ["TypeSystemPropertyName", "UnionReduction", "IntersectionFlags", "MappedTypeModifiers", "MappedTypeNameTypeKind", "TypeFacts", "InferenceFlags", "InferencePriority", "CheckMode", "WideningKind"],
    "relater.go": ["SignatureCheckMode", "MinArgumentCountFlags", "IntersectionState", "RecursionFlags", "ExpandingFlags", "RelationComparisonResult"],
};
const lines = ["// <auto-generated />", "namespace TypeScript.Compiler.Checking;", ""];
for (const [file, names] of Object.entries(groups)) {
    const bytes = await readFile(path.join(root, "tsc/internal/checker", file));
    lines.push(`// ${file} SHA256 ${sha256(bytes)}`);
    const source = bytes.toString().replaceAll(/\/\/[^\n]*/g, "").replaceAll(/\|\s*\n\s*/g, "| ");
    for (const name of names) {
        const block = [...source.matchAll(/const\s*\(([\s\S]*?)\n\)/g)].find(m => new RegExp(`\\b${name}\\w+\\b`).test(m[1]));
        if (!block) throw Error(`Missing ${name}`);
        const flags = name.endsWith("Flags") || ["MappedTypeModifiers", "SignatureCheckMode", "IntersectionState", "RelationComparisonResult", "TypeFacts", "InferencePriority", "CheckMode"].includes(name), backing = name === "Ternary" ? "sbyte" : name === "InferencePriority" ? "int" : flags ? "uint" : "int";
        if (flags) lines.push("[Flags]");
        lines.push(`public enum ${name} : ${backing}`, "{");
        let index = 0, previous;
        for (const row of block[1].split("\n").map(s => s.trim()).filter(Boolean)) {
            const match = row.match(new RegExp(`^${name}(\\w+)(?:\\s+${name})?(?:\\s*=\\s*(.*))?$`));
            if (!match) throw Error(`Unrecognized ${name} constant: ${row}`);
            const expression = match[2] ?? previous;
            if (!expression) throw Error(`Missing expression: ${row}`);
            previous = expression;
            let value = expression.replaceAll("iota", String(index++)).replaceAll(name, "").replaceAll(/&\s*\^/g, "& ~");
            if (backing === "uint") value = value.replaceAll(/\b1\s*<</g, "1u <<");
            lines.push(`    ${match[1]} = ${value},`);
        }
        lines.push("}", "");
    }
}
const file = path.join(root, "csharp/src/TypeScript.Compiler/Checking/Flags.generated.cs"), text = lines.join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error(`Stale ${file}`);
}
else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, text);
}
