// Typed payloads and dispatch for the phase-1 grammar. Member names and order
// come from the shared schema; this explicit selection does not mark other
// grammar or handwritten hooks as implemented.
import {
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    json,
    root,
    sha256,
} from "./common.mjs";

const source = await readFile(path.join(root, "tools/scripts/tsc/ast.json"));
const schema = JSON.parse(source);
const selected = {
    SourceFile: ["Statements", "EndOfFileToken"],
    Identifier: ["Text:string"],
    KeywordTypeNode: [],
    Token: [],
    StringLiteral: ["Text:string", "TokenFlags:uint"],
    NumericLiteral: ["Text:string", "TokenFlags:uint"],
    LiteralTypeNode: ["Literal"],
    UnionTypeNode: ["Types"],
    ParenthesizedTypeNode: ["Type"],
    TypeReferenceNode: ["TypeName", "TypeArguments"],
    TypeAliasDeclaration: ["modifiers", "name", "TypeParameters", "Type"],
    ImportDeclaration: ["modifiers", "ImportClause", "ModuleSpecifier", "Attributes"],
    ImportClause: ["PhaseModifier:SyntaxKind", "name", "NamedBindings"],
    NamedImports: ["Elements"],
    ImportSpecifier: ["IsTypeOnly:bool", "PropertyName", "name"],
    VariableStatement: ["modifiers", "DeclarationList"],
    VariableDeclarationList: ["Declarations"],
    VariableDeclaration: ["name", "ExclamationToken", "Type", "Initializer"],
    PrefixUnaryExpression: ["Operator:SyntaxKind", "Operand"],
};
const lines = ["// <auto-generated />", `// ast.json SHA256 ${sha256(source)}`, "using TypeScript.Compiler.Storage;", "namespace TypeScript.Compiler.Syntax;", ""];
let tag = 1;
for (const [name, fields] of Object.entries(selected)) {
    const members = schema.nodes.definitions[name].members ?? [];
    for (const field of fields) if (!members.some(member => member.name === field.split(":")[0])) throw new Error(`Unmapped schema field ${name}.${field}`);
    const args = fields.map(field => {
        const [name, type = "NodeId"] = field.split(":");
        return `${type} ${name[0].toUpperCase()}${name.slice(1)}`;
    });
    const children = fields.filter(field => !field.includes(":")).map(field => field[0].toUpperCase() + field.slice(1));
    lines.push(`public readonly record struct ${name}Data(${args.join(", ")}) : INodePayload<${name}Data>`, "{", `    public static int Tag => ${tag++};`, `    public int ChildSlots => ${children.length};`, "    public NodeId ChildAt(int slot) => slot switch", "    {");
    children.forEach((name, index) => lines.push(`        ${index} => ${name},`));
    lines.push("        _ => throw new ArgumentOutOfRangeException(nameof(slot)),", "    };", "}", "");
}
lines.push("public static class SliceSchema", "{", `    public const int PayloadCount = ${tag + 1};`, "    public static string KeywordText(SyntaxKind kind) => kind switch", "    {");
for (const kind of schema.kinds.elements.filter(kind => typeof kind === "string" && kind.endsWith("Keyword"))) lines.push(`        SyntaxKind.${kind} => "${kind.slice(0, -7).toLowerCase()}",`);
lines.push('        _ => throw new InvalidDataException("Expected keyword"),', "    };", "    public static int ChildSlots<TStore>(TStore store, NodeId id) where TStore : INodeStore => store.Tag(id) switch", "    {");
tag = 1;
for (const name of Object.keys(selected)) lines.push(`        ${tag++} => store.Get<${name}Data>(id).ChildSlots,`);
lines.push("        0 => store.Get<NodeListData>(id).Nodes.Length,", '        _ => throw new InvalidDataException("Unknown syntax payload"),', "    };", "    public static NodeId ChildAt<TStore>(TStore store, NodeId id, int slot) where TStore : INodeStore => store.Tag(id) switch", "    {");
tag = 1;
for (const name of Object.keys(selected)) lines.push(`        ${tag++} => store.Get<${name}Data>(id).ChildAt(slot),`);
lines.push("        0 => store.Get<NodeListData>(id).Nodes[slot],", '        _ => throw new InvalidDataException("Unknown syntax payload"),', "    };", "    public static NodeId Copy<TSource, TTarget>(TSource source, TTarget target, NodeId id, IReadOnlyDictionary<NodeId, NodeId> copies) where TSource : INodeStore where TTarget : INodeStore", "    {", "        NodeId Map(NodeId child) => child.IsNull ? default : copies[child];", "        switch (source.Tag(id))", "        {");
tag = 1;
for (const [name, fields] of Object.entries(selected)) {
    const children = fields.filter(field => !field.includes(":")).map(field => field[0].toUpperCase() + field.slice(1));
    lines.push(`            case ${tag++}:`, "            {", `                var payload = source.Get<${name}Data>(id);`, `                return target.Add(source.Header(id), payload${children.length ? ` with { ${children.map(child => `${child} = Map(payload.${child})`).join(", ")} }` : ""});`, "            }");
}
lines.push("            case 0:", "            {", "                var payload = source.Get<NodeListData>(id);", "                return target.Add(source.Header(id), payload with { Nodes = Array.ConvertAll(payload.Nodes, Map) });", "            }", '            default: throw new InvalidDataException("Unknown syntax payload");', "        }", "    }", "}", "");
const file = path.join(root, "csharp/src/TypeScript.Compiler/Syntax/SliceSchema.generated.cs");
if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== lines.join("\n")) throw new Error("Stale slice schema");
}
else await writeFile(file, lines.join("\n"));
if (!process.argv.includes("--check")) {
    await json(path.join(root, "csharp/compatibility/phase1-scope.generated.json"), {
        schemaSha256: sha256(source),
        productions: selected,
        representation: "One generated payload model, generic typed class wrappers and typed managed arenas; child dispatch and cloning are generated from the same selection.",
        hooks: {
            SourceFile: "Source ownership, text/hash/path, imports and external-module metadata handled by SliceFile/SliceEncoder; top-level statements remain in schema order.",
            privateNames: "Selected name fields are explicit NodeId payload members; binding/identity belongs to the snapshot, not a duplicated hidden node field.",
            Kind: "Token and keyword type kinds live in NodeHeader; no runtime generic construction.",
        },
        outsidePhase1: "Other grammar, full AST generation, package/global resolution, control flow, JSDoc, transforms, declaration emit, source maps, language services and all-target shipping are later phases, not implied by these experiment passes.",
    });
}
console.log(`Verified ${Object.keys(selected).length} typed payloads and child dispatch tables`);
