import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    output,
    root,
    run,
    sha256,
} from "./common.mjs";
const option = (key, fallback) => process.argv.includes(key) ? process.argv[process.argv.indexOf(key) + 1] : fallback;
const go = option("--go", "D:/go1.27.1-20260904.9.windows-amd64/go/bin/go.exe");
const env = { ...process.env, GOWORK: "off", GOTOOLCHAIN: "local" };
const reference = JSON.parse(await readFile(path.join(output, "reference.json"), "utf8"));
const cwd = path.join(output, reference.sourceRelativePath, "tsc");
const module = JSON.parse(await run(go, ["list", "-m", "-json", "golang.org/x/text"], { cwd, env }));
const directory = path.join(output, "locale-generator");
await mkdir(directory, { recursive: true });
const program = `package main
import("encoding/json";"fmt";"os";"golang.org/x/text/language")
func main(){
 data:=map[string][]string{"Languages":{},"Scripts":{},"Regions":{}}
 for a:='a';a<='z';a++ {for b:='a';b<='z';b++ {
  s:=string([]rune{a,b});if _,e:=language.ParseBase(s);e==nil{data["Languages"]=append(data["Languages"],s)}
  if _,e:=language.ParseRegion(s);e==nil{data["Regions"]=append(data["Regions"],s)}
  for c:='a';c<='z';c++ {
   s:=string([]rune{a,b,c});if _,e:=language.ParseBase(s);e==nil{data["Languages"]=append(data["Languages"],s)}
   for d:='a';d<='z';d++ {s:=string([]rune{a,b,c,d});if _,e:=language.ParseScript(s);e==nil{data["Scripts"]=append(data["Scripts"],s)}}
  }
 }}
 for i:=0;i<1000;i++ {s:=fmt.Sprintf("%03d",i);if _,e:=language.ParseRegion(s);e==nil{data["Regions"]=append(data["Regions"],s)}}
 if e:=json.NewEncoder(os.Stdout).Encode(data);e!=nil{panic(e)}
}`;
const source = path.join(directory, "main.go");
await writeFile(source, program);
const data = JSON.parse(await run(go, ["run", source], { cwd, env }));
const tables = await readFile(path.join(module.Dir, "internal/language/tables.go"), "utf8");
const lookup = await readFile(path.join(module.Dir, "internal/language/lookup.go"), "utf8");
data.Variants = [...tables.split("var variantIndex = ")[1].split("\n}")[0].matchAll(/"([a-z0-9]+)":/g)].map(m => m[1]);
data.Grandfathered = [...lookup.split("grandfatheredMap = ")[1].split("\n\t}")[0].matchAll(/\[maxLen\]byte\{([^}]+)\}/g)].map(m => [...m[1].matchAll(/'(.)'/g)].map(c => c[1]).join(""));
const lines = ["// <auto-generated />", "#nullable enable", `// golang.org/x/text ${module.Version}; registry SHA256 ${sha256(JSON.stringify(data))}`, "using System.Collections.Frozen;", "", "namespace TypeScript.Compiler.Configuration;", "", "internal static partial class LocaleIdentifier", "{"];
for (const [name, values] of Object.entries(data)) {
    values.sort();
    lines.push(`    private static readonly FrozenSet<Utf8String> ${name} = Utf8String.Copy("""`);
    for (let i = 0; i < values.length; i += 24) lines.push("        " + values.slice(i, i + 24).join(" "));
    lines.push('        """u8).SplitAny(" \\t\\r\\n"u8, StringSplitOptions.RemoveEmptyEntries).ToFrozenSet(Utf8StringComparer.Ordinal);', "");
}
lines.pop();
lines.push("}", "");
const target = path.join(root, "csharp/src/TypeScript.Compiler/Configuration/LocaleIdentifier.generated.cs");
const text = lines.join("\n");
if (process.argv.includes("--check")) { if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error("Stale locale registry"); }
else await writeFile(target, text);
await writeFile(path.join(directory, "registry.json"), JSON.stringify(data));
console.log(Object.fromEntries(Object.entries(data).map(([k, v]) => [k, v.length])));
