import { spawnSync } from "node:child_process";
import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";
for (const [name, input] of [["SymbolFlags", "symbolflags.go"], ["FlowFlags", "flow.go"]]) {
    const bytes = await readFile(path.join(root, "tsc/internal/ast", input));
    const lines = ["// <auto-generated />", `// Source SHA256 ${sha256(bytes)}`, "namespace TypeScript.Compiler.Binding;", "[Flags]", `public enum ${name} : uint`, "{"];
    for (const m of bytes.toString().matchAll(new RegExp(`^\\s*${name}(\\w+)\\s+(?:${name}\\s+)?=([^\\n]+)`, "gm"))) lines.push(`    ${m[1]} = ${m[2].split("//")[0].trim().replaceAll(name, "").replaceAll("^", "~").replace("1<<30 - 1", "(1u << 30) - 1")},`);
    lines.push("}");
    const file = path.join(root, `csharp/src/TypeScript.Compiler/Binding/${name}.generated.cs`), text = lines.join("\n") + "\n";
    if (process.argv.includes("--check")) {
        if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error(`Stale ${file}`);
    }
    else {
        await mkdir(path.dirname(file), { recursive: true });
        await writeFile(file, text);
    }
}

// Test-only typed syntax interchange lets the pinned binder run on the candidate parser's tree.
// This isolates binding rules from the deliberately different phase-2 recovery/JSDoc trees.
const schemaBytes = await readFile(path.join(root, "tools/scripts/tsc/ast.json"));
const schema = JSON.parse(schemaBytes), names = new Set(Object.keys(schema.nodes.definitions));
const upper = text => text[0].toUpperCase() + text.slice(1);
const className = name => name.endsWith("Node") ? name : name + "Node";
function inherited(name, fields = new Map()) {
    for (const parent of schema.bases[name].extends ?? []) inherited(parent, fields);
    for (const [key, field] of Object.entries(schema.bases[name].fields ?? {})) if (!field.noGo) fields.set(key, { name: key, ...field });
    return fields;
}
function members(definition) {
    const fields = new Map();
    for (const base of definition.extends ?? []) inherited(base, fields);
    return (definition.members ?? []).map(f => ({ ...fields.get(f.name), ...f })).filter(f => f.name !== "Kind" && !f.goOnly && !f.noGo);
}
function scalar(field) {
    if (field.list) return field.list === "raw" && field.type === "string" ? "strings" : null;
    if (["string", "bool", "any", "NodeFlags", "TokenFlags"].includes(field.type)) return field.type;
    if (["TKind", "ImportPhaseModifierSyntaxKind"].includes(field.type) || Array.isArray(field.type) && field.type.every(t => t.startsWith("SyntaxKind."))) return "Kind";
    return null;
}
const cs = [
    "// <auto-generated />",
    `// ast.json SHA256 ${sha256(schemaBytes)}; development probe only.`,
    "#nullable enable",
    "using System.Text.Json;",
    "using TypeScript.Compiler.Ast;",
    "using TypeScript.Compiler.Text;",
    "namespace TypeScript.Compatibility;",
    "internal static class BindingSyntax",
    "{",
    "    internal static void Write(Utf8JsonWriter writer, SourceFileNode file)",
    "    {",
    "        var nodes = file.DescendantsAndSelf().ToArray();",
    "        var ids = nodes.Select((n, i) => (n, Id: i + 1)).ToDictionary(p => p.n, p => p.Id);",
    "        writer.WriteStartObject();",
    '        writer.WriteNumber("external", file.ExternalModuleIndicator is { } indicator ? ids[indicator] : 0);',
    '        writer.WriteNumber("parseErrors", file.ParseDiagnostics.Count);',
    '        writer.WriteStartArray("nodes");',
    "        foreach (var node in nodes)",
    "        {",
    "            writer.WriteStartObject();",
    '            writer.WriteNumber("kind", (uint)node.Kind);',
    '            writer.WriteNumber("flags", (uint)node.Flags);',
    '            writer.WriteNumber("pos", node.Pos);',
    '            writer.WriteNumber("end", node.End);',
    '            writer.WriteNumber("parent", node.Parent is { } parent ? ids.GetValueOrDefault(parent) : 0);',
    "            switch (node)",
    "            {",
];
const go = [
    "// Code generated by csharp/tools/generate-binding.mjs; DO NOT EDIT.",
    `// ast.json SHA256 ${sha256(schemaBytes)}; development probe only.`,
    "package ast",
    "",
    "import (",
    '"encoding/json"',
    '"encoding/base64"',
    "",
    '"github.com/microsoft/TypeScript/tsc/internal/core"',
    ")",
    "type CSharpSyntaxNode struct { Type string; Kind Kind; Flags NodeFlags; Pos, End, Parent int; Fields map[string]json.RawMessage }",
    "type CSharpSyntaxTree struct { Nodes []CSharpSyntaxNode; External, ParseErrors int }",
    "type csharpSyntaxList struct { Pos, End int; Nodes []int }",
    "func csharpDecode[T any](raw json.RawMessage) (value T) { if err:=json.Unmarshal(raw,&value);err!=nil{panic(err)};return }",
    "",
    "func csharpString(raw json.RawMessage) string { bytes,err:=base64.StdEncoding.DecodeString(csharpDecode[string](raw));if err!=nil{panic(err)};return string(bytes) }",
    "",
    "func CSharpLoadSyntax(root *SourceFile, tree CSharpSyntaxTree) []*Node {",
    "    nodes:=make([]*Node,len(tree.Nodes)+1)",
    "    for i,row:=range tree.Nodes { switch row.Type {",
    '    case "SourceFile": nodes[i+1]=root.AsNode()',
];
for (const [name] of Object.entries(schema.nodes.definitions)) if (name !== "SourceFile") go.push(`    case ${JSON.stringify(name)}: nodes[i+1]=newNode(row.Kind,&${name}{},NodeFactoryHooks{})`);
go.push('    default: panic("Unknown syntax type "+row.Type)', "    } }", "    node:=func(raw json.RawMessage)*Node { return nodes[csharpDecode[int](raw)] }", '    list:=func(raw json.RawMessage)*NodeList { if string(raw)=="null"{return nil};value:=csharpDecode[csharpSyntaxList](raw);items:=make([]*Node,len(value.Nodes));for i,id:=range value.Nodes{items[i]=nodes[id]};return &NodeList{Loc:core.NewTextRange(value.Pos,value.End),Nodes:items} }', "    modifiers:=func(raw json.RawMessage)*ModifierList { l:=list(raw);if l==nil{return nil};return &ModifierList{NodeList:*l,ModifierFlags:ModifiersToFlags(l.Nodes)} }", "    for i,row:=range tree.Nodes { current:=nodes[i+1];current.Flags=row.Flags;current.Loc=core.NewTextRange(row.Pos,row.End);current.Parent=nodes[row.Parent];switch row.Type {");
for (const [name, definition] of Object.entries(schema.nodes.definitions)) {
    const fields = members(definition);
    cs.push(`                case ${className(name)} n:`, "                {", `                    writer.WriteString("type", ${JSON.stringify(name)});`, '                    writer.WriteStartObject("fields");');
    if (fields.length) go.push(`    case ${JSON.stringify(name)}:`, `        n:=current.As${name}()`);
    for (const field of fields) {
        const key = upper(field.name), access = "n." + key, target = "n." + field.name, raw = `row.Fields[${JSON.stringify(key)}]`, kind = scalar(field);
        if (kind === "string") {
            cs.push(`                    writer.WriteBase64String(${JSON.stringify(key)}, Wtf8.Encode(${access}));`);
            go.push(`        ${target}=csharpString(${raw})`);
        }
        else if (kind === "bool") {
            cs.push(`                    writer.WriteBoolean(${JSON.stringify(key)}, ${access});`);
            go.push(`        ${target}=csharpDecode[bool](${raw})`);
        }
        else if (kind === "strings") {
            cs.push(`                    writer.WriteStartArray(${JSON.stringify(key)});`, `                    foreach(var value in ${access}) writer.WriteBase64StringValue(Wtf8.Encode(value));`, "                    writer.WriteEndArray();");
            go.push(`        for _,raw:=range csharpDecode[[]json.RawMessage](${raw}){${target}=append(${target},csharpString(raw))}`);
        }
        else if (kind === "any") {
            cs.push(`                    writer.WriteNull(${JSON.stringify(key)});`);
            go.push(`        ${target}=nil`);
        }
        else if (kind) {
            cs.push(`                    writer.WriteNumber(${JSON.stringify(key)}, (uint)${access});`);
            go.push(`        ${target}=csharpDecode[${kind}](${raw})`);
        }
        else if (field.list) {
            if (field.list === "raw") {
                cs.push(`                    writer.WriteStartArray(${JSON.stringify(key)});`, `                    foreach (var value in ${access}) writer.WriteNumberValue(ids[value]);`, "                    writer.WriteEndArray();");
                go.push(`        for _,id:=range csharpDecode[[]int](${raw}){${target}=append(${target},nodes[id])}`);
            }
            else {
                cs.push(`                    writer.WritePropertyName(${JSON.stringify(key)});`, `                    List(writer, ${access}, ids);`);
                go.push(`        ${target}=${field.list === "ModifierList" ? "modifiers" : "list"}(${raw})`);
            }
        }
        else {
            cs.push(`                    writer.WriteNumber(${JSON.stringify(key)}, ${access} is { } value${key} ? ids[value${key}] : 0);`);
            go.push(`        ${target}=node(${raw})`);
        }
    }
    cs.push("                    writer.WriteEndObject();", "                    break;", "                }");
}
cs.push('                default: throw new InvalidDataException("Unknown syntax node");', "            }", "            writer.WriteEndObject();", "        }", "        writer.WriteEndArray();", "        writer.WriteEndObject();", "    }", "    private static void List(Utf8JsonWriter writer, NodeList? list, Dictionary<SyntaxNode, int> ids)", "    {", "        if (list is null) { writer.WriteNullValue(); return; }", '        writer.WriteStartObject(); writer.WriteNumber("pos", list.Pos); writer.WriteNumber("end", list.End); writer.WriteStartArray("nodes");', "        foreach (var node in list) writer.WriteNumberValue(ids[node]); writer.WriteEndArray(); writer.WriteEndObject();", "    }", "}");
go.push("    } }", "    root.ExternalModuleIndicator=nodes[tree.External]", "    return nodes", "}");
for (const [relative, lines] of [["csharp/tests/TypeScript.Compatibility/BindingSyntax.generated.cs", cs], ["csharp/oracle/binding/syntax.generated.go", go]]) {
    const file = path.join(root, relative);
    let text = lines.join("\n") + "\n";
    if (relative.endsWith(".go")) {
        const formatted = spawnSync(process.env.GOFMT ?? "D:/go1.27.1-20260904.9.windows-amd64/go/bin/gofmt.exe", [], { input: text, encoding: "utf8", windowsHide: true });
        if (formatted.status !== 0) throw Error(formatted.stderr || "Cannot format the development-only Go oracle");
        text = formatted.stdout;
    }
    if (process.argv.includes("--check")) { if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error(`Stale ${file}`); }
    else await writeFile(file, text);
}
