import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";

const input = await readFile(path.join(root, "tools/scripts/tsc/ast.json"));
const schema = JSON.parse(input);
const definitions = schema.nodes.definitions;
const names = new Set(Object.keys(definitions));
const kinds = new Set(schema.kinds.elements.map(k => typeof k === "string" ? k : k.name).filter(Boolean));
const scalar = new Map([["string", "Utf8String"], ["bool", "bool"], ["NodeFlags", "NodeFlags"], ["TokenFlags", "TokenFlags"], ["ImportPhaseModifierSyntaxKind", "SyntaxKind"], ["TKind", "SyntaxKind"], ["any", "object?"]]);
const upper = s => s[0].toUpperCase() + s.slice(1);
const classNameOf = name => name.endsWith("Node") ? name : name + "Node";
function inherited(base, fields = new Map()) {
    for (const parent of schema.bases[base].extends ?? []) inherited(parent, fields);
    for (const [name, field] of Object.entries(schema.bases[base].fields ?? {})) if (!field.noGo) fields.set(name, { name, ...field });
    return fields;
}
function baseNames(definition, result = new Set()) {
    for (const name of definition.extends ?? []) {
        result.add(name);
        baseNames(schema.bases[name], result);
    }
    return result;
}
function bindingFields(definition, kind, options, name) {
    const bases = baseNames(definition), kinds = new Set(options ?? [kind]), fields = [];
    const hasKind = (...values) => values.some(value => kinds.has(value));
    if (bases.has("DeclarationBase")) fields.push(["Symbol", "Symbol?"], ["LocalSymbol", "Symbol?"]);
    if (bases.has("FlowNodeBase") || bases.has("ExpressionBase") || bases.has("DeclarationBase"))
        fields.push(["Flow", "FlowNode?"]);
    if (bases.has("LocalsContainerBase") || bases.has("FunctionLikeBase")
        || hasKind("ClassDeclaration", "ClassExpression", "EnumDeclaration", "ObjectLiteralExpression", "TypeLiteral",
            "JsxAttributes", "InterfaceDeclaration", "ModuleDeclaration", "TypeAliasDeclaration", "JSTypeAliasDeclaration",
            "MappedType", "ConditionalType", "ClassStaticBlockDeclaration", "IndexSignature"))
        fields.push(["Locals", "SymbolTable?"]);
    if (bases.has("FunctionLikeWithBodyBase") || hasKind("ClassStaticBlockDeclaration") || name === "CaseOrDefaultClause")
        fields.push(["EndFlow", "FlowNode?"]);
    if (bases.has("FunctionLikeWithBodyBase") || hasKind("ClassStaticBlockDeclaration")) fields.push(["ReturnFlow", "FlowNode?"]);
    return fields;
}
function members(definition) {
    const fields = new Map();
    for (const base of definition.extends ?? []) inherited(base, fields);
    return (definition.members ?? []).map(field => ({ ...fields.get(field.name), ...field })).filter(m => m.name !== "Kind" && !m.goOnly && !m.noGo);
}
function type(m) {
    if (m.list === "raw") return m.type === "string" ? "Utf8String[]" : "SyntaxNode[]";
    if (m.list) return "NodeList?";
    if (Array.isArray(m.type) && m.type.every(t => t.startsWith("SyntaxKind."))) return "SyntaxKind";
    if (scalar.has(m.type)) return scalar.get(m.type);
    if (!m.type) throw new Error(`Unresolved member ${JSON.stringify(m)}`);
    return names.has(m.type) ? `${classNameOf(m.type)}?` : "SyntaxNode?";
}
function isChild(m) {
    return type(m).endsWith("Node?") || type(m) === "SyntaxNode[]" || m.list && m.list !== "raw";
}
const lines = ["// <auto-generated />", "#nullable enable", `// ast.json SHA256 ${sha256(input)}`, "using TypeScript.Compiler.Syntax;", "using TypeScript.Compiler.Text;", "using TypeScript.Compiler.Binding;", "namespace TypeScript.Compiler.Ast;", ""];
const factories = ["public sealed partial class NodeFactory", "{"];
const scalarLines = [
    "// <auto-generated />",
    "#nullable enable",
    `// ast.json SHA256 ${sha256(input)}`,
    "using System.Text.Json;",
    "using TypeScript.Compiler.Text;",
    "namespace TypeScript.Compiler.Ast;",
    "",
    "public static class AstScalarProperties",
    "{",
    "    public static void Write(Utf8JsonWriter writer, SyntaxNode node)",
    "    {",
    "        writer.WriteStartObject();",
    "        switch (node)",
    "        {",
];
const goScalars = [
    "// Code generated by csharp/tools/generate-ast.mjs; DO NOT EDIT.",
    `// ast.json SHA256 ${sha256(input)}`,
    "// Development oracle instrumentation only; not part of the shipped compiler.",
    "package ast",
    "",
    'import "encoding/base64"',
    "",
    "func CSharpScalarProperties(node *Node) map[string]any {",
    "\tresult := map[string]any{}",
    "\tswitch node.Kind {",
];
const listLines = [
    "",
    "    public static void WriteLists(Utf8JsonWriter writer, SyntaxNode node, Func<int, int> position)",
    "    {",
    "        writer.WriteStartObject();",
    "        switch (node)",
    "        {",
];
const goLists = [
    "",
    "func CSharpListProperties(node *Node, position func(int) int) map[string]any {",
    "\tresult := map[string]any{}",
    "\tlistValue := func(list *NodeList) any {",
    "\t\tif list == nil {",
    "\t\t\treturn nil",
    "\t\t}",
    "\t\treturn []any{len(list.Nodes), position(list.Pos()), position(list.End()), list.HasTrailingComma()}",
    "\t}",
    "\tswitch node.Kind {",
];
let scalarFieldCount = 0;
let listFieldCount = 0;
for (const [name, definition] of Object.entries(definitions)) {
    const fields = members(definition);
    const className = classNameOf(name);
    let kind = definition.kind ?? (kinds.has(name) ? name : undefined);
    const kindMember = definition.members?.find(m => m.name === "Kind");
    const options = Array.isArray(kind) ? kind : Array.isArray(kindMember?.type) ? kindMember.type.map(k => k.replace("SyntaxKind.", "")) : undefined;
    if (name === "KeywordExpression" || name === "KeywordTypeNode" || name === "Token" || options) kind = undefined;
    if (!kind && !kindMember && !options) throw new Error(`Unmapped syntax kind ${name}`);
    const listFields = fields.filter(m => m.list && m.list !== "raw").sort((a, b) => upper(a.name) < upper(b.name) ? -1 : upper(a.name) > upper(b.name) ? 1 : 0);
    if (listFields.length) {
        if (!kind && !options) throw new Error(`List node has no concrete kinds: ${name}`);
        listFieldCount += listFields.length;
        listLines.push(`            case ${className} n:`);
        goLists.push(`\tcase ${(options ?? [kind]).map(k => `Kind${k}`).join(", ")}:`, `\t\tn := node.As${name}()`);
        for (const field of listFields) {
            const property = upper(field.name), go = `n.${field.name}`;
            listLines.push(`                writer.WritePropertyName("${property}");`, `                WriteList(writer, n.${property}, position);`);
            if (field.list === "ModifierList") goLists.push(`\t\tif ${go} == nil {`, `\t\t\tresult["${property}"] = nil`, "\t\t} else {", `\t\t\tresult["${property}"] = listValue(&${go}.NodeList)`, "\t\t}");
            else goLists.push(`\t\tresult["${property}"] = listValue(${go})`);
        }
        listLines.push("                break;");
    }
    const scalarFields = fields.filter(m => !isChild(m) && m.name !== "Flags").sort((a, b) => upper(a.name) < upper(b.name) ? -1 : upper(a.name) > upper(b.name) ? 1 : 0);
    if (scalarFields.length) {
        if (!kind && !options) throw new Error(`Scalar node has no concrete kinds: ${name}`);
        scalarFieldCount += scalarFields.length;
        scalarLines.push(`            case ${className} n:`);
        goScalars.push(`\tcase ${(options ?? [kind]).map(k => `Kind${k}`).join(", ")}:`, `\t\tn := node.As${name}()`);
        for (const field of scalarFields) {
            const property = upper(field.name), cs = `n.${property}`, go = `n.${field.name}`;
            const t = type(field);
            if (t === "Utf8String[]") {
                scalarLines.push(`                writer.WriteStartArray("${property}");`, `                foreach (Utf8String value in ${cs}) writer.WriteBase64StringValue(value.Span);`, "                writer.WriteEndArray();");
                goScalars.push(`\t\t${field.name} := make([]string, len(${go}))`, `\t\tfor i, value := range ${go} {`, `\t\t\t${field.name}[i] = base64.StdEncoding.EncodeToString([]byte(value))`, "\t\t}", `\t\tresult["${property}"] = ${field.name}`);
            }
            else if (t === "Utf8String") {
                scalarLines.push(`                writer.WriteBase64String("${property}", ${cs}.Span);`);
                goScalars.push(`\t\tresult["${property}"] = base64.StdEncoding.EncodeToString([]byte(${go}))`);
            }
            else if (t === "bool") {
                scalarLines.push(`                writer.WriteBoolean("${property}", ${cs});`);
                goScalars.push(`\t\tresult["${property}"] = ${go}`);
            }
            else if (t === "object?") {
                scalarLines.push(`                if (${cs} is not null) throw new InvalidOperationException("Cannot serialize semantic state ${name}.${property} as parser syntax.");`, `                writer.WriteNull("${property}");`);
                goScalars.push(`\t\tif ${go} != nil {`, `\t\t\tpanic("Cannot serialize semantic state ${name}.${property} as parser syntax")`, "\t\t}", `\t\tresult["${property}"] = nil`);
            }
            else if (t === "SyntaxKind" || t === "NodeFlags" || t === "TokenFlags") {
                scalarLines.push(`                writer.WriteNumber("${property}", (${t === "SyntaxKind" ? "int" : "uint"})${cs});`);
                goScalars.push(`\t\tresult["${property}"] = ${t === "SyntaxKind" ? "int" : "uint32"}(${go})`);
            }
            else throw new Error(`Unmapped scalar property ${name}.${property}: ${t}`);
        }
        scalarLines.push("                break;");
    }
    const has = (name, expected) => fields.some(m => upper(m.name) === name && type(m) === expected);
    const interfaces = [];
    if (has("Type", "SyntaxNode?")) interfaces.push("ITypedNode");
    if (has("Initializer", "SyntaxNode?")) interfaces.push("IInitializedNode");
    if (has("FullSignature", "SyntaxNode?")) interfaces.push("IFullSignatureNode");
    if (has("TypeExpression", "SyntaxNode?")) interfaces.push("ITypeExpressionNode");
    if (has("TypeParameters", "NodeList?") && has("Parameters", "NodeList?") && has("Type", "SyntaxNode?")) interfaces.push("IFunctionSignature");
    if (has("Modifiers", "NodeList?")) interfaces.push("IModifiedNode");
    const nameField = fields.find(m => upper(m.name) === "Name" && isChild(m) && !m.list);
    if (nameField) interfaces.push("INamedNode");
    lines.push(`public sealed partial class ${className} : SyntaxNode${interfaces.length ? ", " + interfaces.join(", ") : ""}`, "{");
    lines.push(`    public ${className}(${kind ? "" : "SyntaxKind kind"}) : base(${kind ? `SyntaxKind.${kind}` : "kind"})`, "    {");
    if (options) lines.push(`        if (kind is not (${options.map(k => `SyntaxKind.${k}`).join(" or ")})) throw new ArgumentOutOfRangeException(nameof(kind));`);
    lines.push("    }");
    for (const m of fields) {
        if (m.name === "Flags") continue;
        const t = type(m);
        lines.push(`    public ${t} ${upper(m.name)} { get; set; }${t.endsWith("[]") ? " = [];" : ""}`);
    }
    const binding = bindingFields(definition, kind, options, name);
    for (const [property, fieldType] of binding)
        lines.push(`    internal override ${fieldType} Binding${property} { get; set; }`);
    if (binding.length) {
        lines.push("    internal override void ClearBindingState()", "    {", "        base.ClearBindingState();");
        for (const [property] of binding) lines.push(`        Binding${property} = null;`);
        lines.push("    }");
    }
    if (nameField) lines.push("    SyntaxNode? INamedNode.Name => Name;", "    internal override SyntaxNode? DeclarationName => Name;");
    if (interfaces.includes("IModifiedNode")) lines.push("    internal override NodeList? ModifierList => Modifiers;");
    if (interfaces.includes("IFunctionSignature")) lines.push("    internal override bool HasFunctionSignature => true;");
    if (baseNames(definition).has("DeclarationBase")) lines.push("    internal override bool IsDeclarationNode => true;");
    const children = fields.filter(isChild);
    if (children.length) {
        lines.push("    internal override void SetChildParents()", "    {");
        for (const m of children) {
            const n = upper(m.name);
            if (m.list) lines.push(`        if (${n} is { } list${n})`, `            foreach (var child in list${n}) child.Parent = this;`);
            else lines.push(`        if (${n} is { } child${n}) child${n}.Parent = this;`);
        }
        lines.push("    }");
    }
    lines.push(`    public override int ChildCount => ${children.length ? children.map(m => m.list === "raw" ? `${upper(m.name)}.Length` : m.list ? `(${upper(m.name)}?.Count ?? 0)` : `(${upper(m.name)} is null ? 0 : 1)`).join(" + ") : "0"};`);
    lines.push("    public override SyntaxNode GetChild(int index)", "    {");
    // The schema marks this Go visitor as hand-written: tag spelling decides
    // whether a parameter's name or type appears first in traversal.
    const visitChildren = name === "JSDocParameterOrPropertyTag" ? [
        children.find(m => m.name === "TagName"),
        { ...children.find(m => m.name === "name"), condition: "IsNameFirst", local: "childNameFirst" },
        children.find(m => m.name === "TypeExpression"),
        { ...children.find(m => m.name === "name"), condition: "!IsNameFirst", local: "childNameLast" },
        children.find(m => m.name === "Comment"),
    ] : children;
    for (const m of visitChildren) {
        const n = upper(m.name);
        if (m.list) lines.push(`        if (${n} is { } list${n})`, "        {", `            if ((uint)index < (uint)list${n}.${m.list === "raw" ? "Length" : "Count"}) return list${n}[index];`, `            index -= list${n}.${m.list === "raw" ? "Length" : "Count"};`, "        }");
        else lines.push(`        if (${m.condition ? m.condition + " && " : ""}${n} is { } ${m.local ?? "child" + n} && index-- == 0) return ${m.local ?? "child" + n};`);
    }
    lines.push("        throw new ArgumentOutOfRangeException(nameof(index));", "    }");
    if (children.some(m => upper(m.name) === "Comment" && m.list && m.list !== "raw"))
        lines.push("    internal override NodeList? DocumentationComment => Comment;");
    if (children.length) {
        lines.push("    internal override void GetChildGroups(List<SyntaxChild> result)", "    {");
        // Navigation follows VisitEachChild, whose JSDoc parameter order differs
        // from the ForEachChild order used by GetChild above.
        for (const m of children) {
            const n = upper(m.name);
            if (m.list === "raw") lines.push(`        foreach (var child in ${n}) result.Add(new(child, null));`);
            else if (m.list) lines.push(`        if (${n} is not null) result.Add(new(null, ${n}));`);
            else lines.push(`        if (${m.condition ? m.condition + " && " : ""}${n} is not null) result.Add(new(${n}, null));`);
        }
        lines.push("    }");
    }
    lines.push("    internal override void RewriteChildren(IReadOnlyDictionary<SyntaxNode, SyntaxNode> copies)", "    {");
    for (const m of children) {
        const n = upper(m.name);
        lines.push(m.list === "raw" ? `        ${n} = Array.ConvertAll(${n}, n => copies[n]);` : m.list ? `        if (${n} is not null) ${n} = ${n}.Map(copies);` : `        if (${n} is not null) ${n} = (${type(m).replace("?", "")})copies[${n}];`);
    }
    for (const m of fields.filter(m => type(m).endsWith("[]") && !isChild(m))) lines.push(`        ${upper(m.name)} = (${type(m)})${upper(m.name)}.Clone();`);
    lines.push("    }", "}", "");
    // Escaping every parameter also covers C# keywords such as 'operator' and 'event'.
    const args = fields.map(m => "@" + (m.name[0].toLowerCase() + m.name.slice(1)));
    const declarations = fields.map((m, i) => `${type(m)} ${args[i]}`);
    factories.push(`    public ${className} New${name}(${[...(!kind ? ["SyntaxKind kind"] : []), ...declarations].join(", ")}) => Created(new ${className}(${kind ? "" : "kind"})`, "    {");
    fields.forEach((m, i) => factories.push(`        ${upper(m.name)} = ${args[i]},`));
    factories.push("    });");
}
factories.push("}");
lines.push(...factories);
scalarLines.push("        }", "        writer.WriteEndObject();", "    }");
listLines.push("        }", "        writer.WriteEndObject();", "    }", "", "    private static void WriteList(Utf8JsonWriter writer, NodeList? list, Func<int, int> position)", "    {", "        if (list is null) { writer.WriteNullValue(); return; }", "        writer.WriteStartArray();", "        writer.WriteNumberValue(list.Count);", "        writer.WriteNumberValue(position(list.Pos));", "        writer.WriteNumberValue(position(list.End));", "        writer.WriteBooleanValue(list.HasTrailingComma);", "        writer.WriteEndArray();", "    }");
scalarLines.push(...listLines, "}");
goScalars.push("\t}", "\treturn result", "}");
goLists.push("\t}", "\treturn result", "}");
goScalars.push(...goLists);
const target = path.join(root, "csharp/src/TypeScript.Compiler/Ast/Nodes.generated.cs");
await mkdir(path.dirname(target), { recursive: true });
const text = lines.join("\n") + "\n";
if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw new Error("Stale full AST schema");
}
else await writeFile(target, text);
for (
    const [file, content] of [
        ["csharp/src/TypeScript.Compiler/Ast/ScalarProperties.generated.cs", scalarLines.join("\n") + "\n"],
        ["csharp/oracle/syntax/scalars.generated.go", goScalars.join("\n") + "\n"],
    ]
) {
    const destination = path.join(root, file);
    if (process.argv.includes("--check")) {
        if ((await readFile(destination, "utf8")).replaceAll("\r\n", "\n") !== content) throw new Error(`Stale AST scalar serializer: ${file}`);
    }
    else await writeFile(destination, content);
}
console.log(`Generated ${names.size} typed AST classes, factories and traversal/clone dispatch; ${scalarFieldCount} scalar and ${listFieldCount} list fields`);
