import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";

const input = await readFile(path.join(root, "tools/scripts/tsc/ast.json"));
const schema = JSON.parse(input);
const definitions = schema.nodes.definitions;
const names = new Set(Object.keys(definitions));
const kinds = new Set(schema.kinds.elements.map(k => typeof k === "string" ? k : k.name).filter(Boolean));
const scalar = new Map([["string", "string"], ["bool", "bool"], ["NodeFlags", "NodeFlags"], ["TokenFlags", "TokenFlags"], ["ImportPhaseModifierSyntaxKind", "SyntaxKind"], ["TKind", "SyntaxKind"], ["any", "object?"]]);
const upper = s => s[0].toUpperCase() + s.slice(1);
const classNameOf = name => name.endsWith("Node") ? name : name + "Node";
function inherited(base, fields = new Map()) {
    for (const parent of schema.bases[base].extends ?? []) inherited(parent, fields);
    for (const [name, field] of Object.entries(schema.bases[base].fields ?? {})) if (!field.noGo) fields.set(name, { name, ...field });
    return fields;
}
function members(definition) {
    const fields = new Map();
    for (const base of definition.extends ?? []) inherited(base, fields);
    return (definition.members ?? []).map(field => ({ ...fields.get(field.name), ...field })).filter(m => m.name !== "Kind" && !m.goOnly && !m.noGo);
}
function type(m) {
    if (m.list === "raw") return m.type === "string" ? "string[]" : "SyntaxNode[]";
    if (m.list) return "NodeList?";
    if (Array.isArray(m.type) && m.type.every(t => t.startsWith("SyntaxKind."))) return "SyntaxKind";
    if (scalar.has(m.type)) return scalar.get(m.type);
    if (!m.type) throw new Error(`Unresolved member ${JSON.stringify(m)}`);
    return names.has(m.type) ? `${classNameOf(m.type)}?` : "SyntaxNode?";
}
function isChild(m) {
    return type(m).endsWith("Node?") || type(m) === "SyntaxNode[]" || m.list && m.list !== "raw";
}
const lines = ["// <auto-generated />", "#nullable enable", `// ast.json SHA256 ${sha256(input)}`, "using TypeScript.Compiler.Syntax;", "namespace TypeScript.Compiler.Ast;", ""];
const factories = ["public sealed partial class NodeFactory", "{"];
for (const [name, definition] of Object.entries(definitions)) {
    const fields = members(definition);
    const className = classNameOf(name);
    let kind = definition.kind ?? (kinds.has(name) ? name : undefined);
    const kindMember = definition.members?.find(m => m.name === "Kind");
    const options = Array.isArray(kind) ? kind : Array.isArray(kindMember?.type) ? kindMember.type.map(k => k.replace("SyntaxKind.", "")) : undefined;
    if (name === "KeywordExpression" || name === "KeywordTypeNode" || name === "Token" || options) kind = undefined;
    if (!kind && !kindMember && !options) throw new Error(`Unmapped syntax kind ${name}`);
    const has = (name, expected) => fields.some(m => upper(m.name) === name && type(m) === expected);
    const interfaces = [];
    if (has("Type", "SyntaxNode?")) interfaces.push("ITypedNode");
    if (has("Initializer", "SyntaxNode?")) interfaces.push("IInitializedNode");
    if (has("FullSignature", "SyntaxNode?")) interfaces.push("IFullSignatureNode");
    if (has("TypeExpression", "SyntaxNode?")) interfaces.push("ITypeExpressionNode");
    if (has("TypeParameters", "NodeList?") && has("Parameters", "NodeList?") && has("Type", "SyntaxNode?")) interfaces.push("IFunctionSignature");
    if (has("Modifiers", "NodeList?")) interfaces.push("IModifiedNode");
    const nameField = fields.find(m => upper(m.name) === "Name" && isChild(m) && !m.list);
    if (nameField) interfaces.push("INamedNode");
    lines.push(`public sealed partial class ${className} : SyntaxNode${interfaces.length ? ", " + interfaces.join(", ") : ""}`, "{");
    lines.push(`    public ${className}(${kind ? "" : "SyntaxKind kind"}) : base(${kind ? `SyntaxKind.${kind}` : "kind"})`, "    {");
    if (options) lines.push(`        if (kind is not (${options.map(k => `SyntaxKind.${k}`).join(" or ")})) throw new ArgumentOutOfRangeException(nameof(kind));`);
    lines.push("    }");
    for (const m of fields) {
        if (m.name === "Flags") continue;
        const t = type(m);
        lines.push(`    public ${t} ${upper(m.name)} { get; set; }${t === "string" ? ' = "";' : t.endsWith("[]") ? " = [];" : ""}`);
    }
    if (nameField) lines.push("    SyntaxNode? INamedNode.Name => Name;");
    const children = fields.filter(isChild);
    lines.push(`    public override int ChildCount => ${children.length ? children.map(m => m.list === "raw" ? `${upper(m.name)}.Length` : m.list ? `(${upper(m.name)}?.Count ?? 0)` : `(${upper(m.name)} is null ? 0 : 1)`).join(" + ") : "0"};`);
    lines.push("    public override SyntaxNode GetChild(int index)", "    {");
    for (const m of children) {
        const n = upper(m.name);
        if (m.list) lines.push(`        if (${n} is { } list${n})`, "        {", `            if ((uint)index < (uint)list${n}.${m.list === "raw" ? "Length" : "Count"}) return list${n}[index];`, `            index -= list${n}.${m.list === "raw" ? "Length" : "Count"};`, "        }");
        else lines.push(`        if (${n} is { } child${n} && index-- == 0) return child${n};`);
    }
    lines.push("        throw new ArgumentOutOfRangeException(nameof(index));", "    }");
    lines.push("    internal override void RewriteChildren(IReadOnlyDictionary<SyntaxNode, SyntaxNode> copies)", "    {");
    for (const m of children) {
        const n = upper(m.name);
        lines.push(m.list === "raw" ? `        ${n} = Array.ConvertAll(${n}, n => copies[n]);` : m.list ? `        if (${n} is not null) ${n} = ${n}.Map(copies);` : `        if (${n} is not null) ${n} = (${type(m).replace("?", "")})copies[${n}];`);
    }
    for (const m of fields.filter(m => type(m).endsWith("[]") && !isChild(m))) lines.push(`        ${upper(m.name)} = (${type(m)})${upper(m.name)}.Clone();`);
    lines.push("    }", "    internal override void ConvertPositions(Func<int, int> convert)", "    {", "        base.ConvertPositions(convert);");
    for (const m of children.filter(m => m.list && m.list !== "raw")) lines.push(`        ${upper(m.name)}?.ConvertPositions(convert);`);
    lines.push("    }", "}", "");
    // Escaping every parameter also covers C# keywords such as 'operator' and 'event'.
    const args = fields.map(m => "@" + (m.name[0].toLowerCase() + m.name.slice(1)));
    const declarations = fields.map((m, i) => `${type(m)} ${args[i]}`);
    factories.push(`    public ${className} New${name}(${[...(!kind ? ["SyntaxKind kind"] : []), ...declarations].join(", ")}) => Created(new ${className}(${kind ? "" : "kind"})`, "    {");
    fields.forEach((m, i) => factories.push(`        ${upper(m.name)} = ${args[i]},`));
    factories.push("    });");
}
factories.push("}");
lines.push(...factories);
const target = path.join(root, "csharp/src/TypeScript.Compiler/Ast/Nodes.generated.cs");
await mkdir(path.dirname(target), { recursive: true });
const text = lines.join("\n") + "\n";
if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")).replaceAll("\r\n", "\n") !== text) throw new Error("Stale full AST schema");
}
else await writeFile(target, text);
console.log(`Generated ${names.size} typed AST classes, factories and traversal/clone dispatch`);
