import {
    mkdir,
    readFile,
    writeFile,
} from "node:fs/promises";
import path from "node:path";
import {
    root,
    sha256,
} from "./common.mjs";

// Generate constant schemas only. Semantic algorithms are ported and reviewed separately.
const groups = {
    "types.go": ["TypeFlags", "ObjectFlags", "SignatureFlags", "ElementFlags", "AccessFlags", "IndexFlags", "VarianceFlags", "NodeCheckFlags", "TypePredicateKind", "SignatureKind", "Ternary", "ContextFlags", "SymbolFormatFlags"],
    "checker.go": ["TypeSystemPropertyName", "UnionReduction", "IntersectionFlags", "MappedTypeModifiers", "MappedTypeNameTypeKind", "TypeFacts", "InferenceFlags", "InferencePriority", "CheckMode", "WideningKind", "IterationUse", "IterationTypeKind", "DeclarationSpaces"],
    "relater.go": ["SignatureCheckMode", "MinArgumentCountFlags", "IntersectionState", "RecursionFlags", "ExpandingFlags", "RelationComparisonResult"],
};
const lines = ["// <auto-generated />", "namespace TypeScript.Compiler.Checking;", ""];
for (const [file, names] of Object.entries(groups)) {
    const bytes = await readFile(path.join(root, "tsc/internal/checker", file));
    lines.push(`// ${file} SHA256 ${sha256(bytes)}`);
    const source = bytes.toString().replaceAll(/\/\*[\s\S]*?\*\//g, "").replaceAll(/\/\/[^\n]*/g, "").replaceAll(/\|\s*\n\s*/g, "| ");
    for (const name of names) {
        const block = [...source.matchAll(/const\s*\(([\s\S]*?)\n\)/g)].find(m => new RegExp(`\\b${name}\\w+\\b`).test(m[1]));
        if (!block) throw Error(`Missing ${name}`);
        const flags = name.endsWith("Flags") || ["MappedTypeModifiers", "SignatureCheckMode", "IntersectionState", "RelationComparisonResult", "TypeFacts", "InferencePriority", "CheckMode", "IterationUse", "DeclarationSpaces"].includes(name), backing = name === "Ternary" ? "sbyte" : name === "InferencePriority" ? "int" : flags ? "uint" : "int";
        if (flags) lines.push("[Flags]");
        lines.push(`public enum ${name} : ${backing}`, "{");
        let index = 0, previous;
        for (const row of block[1].split("\n").map(s => s.trim()).filter(Boolean)) {
            const match = row.match(new RegExp(`^${name}(\\w+)(?:\\s+${name})?(?:\\s*=\\s*(.*))?$`));
            if (!match) throw Error(`Unrecognized ${name} constant: ${row}`);
            const expression = match[2] ?? previous;
            if (!expression) throw Error(`Missing expression: ${row}`);
            previous = expression;
            let value = expression.replaceAll("iota", String(index++)).replaceAll(name, "").replaceAll(/&\s*\^/g, "& ~");
            if (backing === "uint") value = value.replaceAll(/\b1\s*<</g, "1u <<");
            lines.push(`    ${match[1]} = ${value},`);
        }
        lines.push("}", "");
    }
}
const file = path.join(root, "csharp/src/TypeScript.Compiler/Checking/Flags.generated.cs"), text = lines.join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")).replaceAll("\r\n", "\n") !== text) throw Error(`Stale ${file}`);
}
else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, text);
}

const utilities = await readFile(path.join(root, "tsc/internal/checker/utilities.go"));
const utilitySource = utilities.toString().replaceAll("\r\n", "\n");
const featureStart = utilitySource.indexOf("var getFeatureMap =");
const featureMap = utilitySource.slice(featureStart, utilitySource.indexOf("\n})", featureStart));
const features = ["// <auto-generated />", "#nullable enable", `// utilities.go SHA256 ${sha256(utilities)}`, "namespace TypeScript.Compiler.Checking;", "", "internal static class LibraryFeatures", "{", "    internal static string? PropertyLibrary(string? type, string property) => (type, property) switch", "    {"];
const typePattern = /\t\t"([^"]+)": \{([\s\S]*?)\n\t\t\},/g;
const entryPattern = /\{lib: "([^"]+)", props: \[\]string\{([\s\S]*?)\}\},/g;
let featureTypes = 0;
const nameLibraries = [];
for (const type of featureMap.matchAll(typePattern)) {
    featureTypes++;
    if (type[2].replaceAll(entryPattern, "").trim()) throw Error(`Unrecognized feature entries for ${type[1]}`);
    const entries = [...type[2].matchAll(entryPattern)];
    if (!entries.length) throw Error(`Empty feature entries for ${type[1]}`);
    nameLibraries.push(`        ${JSON.stringify(type[1])} => ${JSON.stringify(entries[0][1])},`);
    for (const entry of entries) {
        const properties = [...entry[2].matchAll(/"([^"]+)"/g)].map(p => JSON.stringify(p[1]));
        if (entry[2].replaceAll(/"[^"]+"|[\s,]/g, "")) throw Error(`Unrecognized feature properties for ${type[1]}`);
        if (properties.length) features.push(`        (${JSON.stringify(type[1])}, ${properties.join(" or ")}) => ${JSON.stringify(entry[1])},`);
    }
}
if (!featureTypes || featureMap.replaceAll(typePattern, "").replace(/^var getFeatureMap = sync.OnceValue\(func\(\) map\[string\]\[\]FeatureMapEntry \{\s*return map\[string\]\[\]FeatureMapEntry\{/, "").replaceAll(/[\s}]/g, "")) throw Error("Unrecognized library feature map");
features.push("        _ => null", "    };", "", "    internal static string? NameLibrary(string name) => name switch", "    {", ...nameLibraries, "        _ => null", "    };", "}", "");
const featureFile = path.join(root, "csharp/src/TypeScript.Compiler/Checking/LibraryFeatures.generated.cs"), featureText = features.join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(featureFile, "utf8")).replaceAll("\r\n", "\n") !== featureText) throw Error(`Stale ${featureFile}`);
}
else await writeFile(featureFile, featureText);

const compilerProgram = await readFile(path.join(root, "tsc/internal/compiler/program.go"));
const plainBlock = compilerProgram.toString().match(/var plainJSErrors = collections.NewSetFromItems\(([\s\S]*?)\n\)/)?.[1];
if (!plainBlock) throw Error("Missing plain JavaScript diagnostic policy");
const messageSource = await readFile(path.join(root, "csharp/src/TypeScript.Compiler/Diagnostics/Messages.generated.cs"), "utf8");
const diagnosticNames = [...plainBlock.matchAll(/diagnostics\.(\w+)\.Code\(\),/g)].map(m => m[1]);
if (plainBlock.replaceAll(/\/\/[^\n]*|diagnostics\.\w+\.Code\(\),|\s/g, "")) throw Error("Unrecognized plain JavaScript diagnostic policy");
const plainCodes = diagnosticNames.map(name => {
    const code = messageSource.match(new RegExp(`\\b${name} = new\\((\\d+),`))?.[1];
    if (!code) throw Error(`Missing diagnostic ${name}`);
    return code;
});
const jsFile = path.join(root, "csharp/src/TypeScript.Compiler/Checking/JavaScriptDiagnostics.generated.cs");
const jsText = ["// <auto-generated />", `// compiler/program.go SHA256 ${sha256(compilerProgram)}`, "namespace TypeScript.Compiler.Checking;", "", "internal static class JavaScriptDiagnostics", "{", "    internal static bool IsPlainError(int code) => code is", ...plainCodes.map((code, i) => `        ${i ? "or " : ""}${code}${i === plainCodes.length - 1 ? ";" : ""}`), "}", ""].join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(jsFile, "utf8")).replaceAll("\r\n", "\n") !== jsText) throw Error(`Stale ${jsFile}`);
}
else await writeFile(jsFile, jsText);

const nodeModulesSource = await readFile(path.join(root, "tsc/internal/core/nodemodules.go"));
function nodeModuleNames(group) {
    const block = nodeModulesSource.toString().match(new RegExp(`var ${group} = map\\[string\\]bool\\{([\\s\\S]*?)\\n\\}`))?.[1];
    if (!block || block.replaceAll(/"[^"]+":\s*true,|\s/g, "")) throw Error(`Unrecognized ${group}`);
    return [...block.matchAll(/"([^"]+)":\s*true,/g)].map(m => m[1]);
}
const unprefixed = nodeModuleNames("UnprefixedNodeCoreModules");
const nodeModules = [...new Set([...unprefixed, ...unprefixed.map(name => "node:" + name), ...nodeModuleNames("ExclusivelyPrefixedNodeCoreModules")])].sort();
const nodeModulesFile = path.join(root, "csharp/src/TypeScript.Compiler/Checking/NodeCoreModules.generated.cs");
const nodeModulesText = ["// <auto-generated />", `// core/nodemodules.go SHA256 ${sha256(nodeModulesSource)}`, "namespace TypeScript.Compiler.Checking;", "", "internal static class NodeCoreModules", "{", "    internal static bool Contains(string name) => name is", ...nodeModules.map((name, i) => `        ${i ? "or " : ""}${JSON.stringify(name)}${i === nodeModules.length - 1 ? ";" : ""}`), "}", ""].join("\n");
if (process.argv.includes("--check")) {
    if ((await readFile(nodeModulesFile, "utf8")).replaceAll("\r\n", "\n") !== nodeModulesText) throw Error(`Stale ${nodeModulesFile}`);
}
else await writeFile(nodeModulesFile, nodeModulesText);
