<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NuGetLockFilePath Condition="'$(PublishAot)' == 'true'">packages.aot.lock.json</NuGetLockFilePath>
    <OutputType>Exe</OutputType>
    <AssemblyName>tsgo-cs</AssemblyName>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TypeScript.Compiler/TypeScript.Compiler.csproj" />
  </ItemGroup>
</Project>
