// <auto-generated />
#nullable enable
// ast.json SHA256 9ab3dfc6a2ff155ec1e315c6fee3deba8fe77c74256761ed38f475296a569574
using System.Text.Json;
using TypeScript.Compiler.Text;
namespace TypeScript.Compiler.Ast;

public static class AstScalarProperties
{
    public static void Write(Utf8JsonWriter writer, SyntaxNode node)
    {
        writer.WriteStartObject();
        switch (node)
        {
            case IdentifierNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case PrivateIdentifierNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case BlockNode n:
                writer.WriteBoolean("MultiLine", n.MultiLine);
                break;
            case HeritageClauseNode n:
                writer.WriteNumber("Token", (int)n.Token);
                break;
            case ExportAssignmentNode n:
                writer.WriteBoolean("IsExportEquals", n.IsExportEquals);
                break;
            case ExportSpecifierNode n:
                writer.WriteBoolean("IsTypeOnly", n.IsTypeOnly);
                break;
            case StringLiteralNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                writer.WriteNumber("TokenFlags", (uint)n.TokenFlags);
                break;
            case NumericLiteralNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                writer.WriteNumber("TokenFlags", (uint)n.TokenFlags);
                break;
            case BigIntLiteralNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                writer.WriteNumber("TokenFlags", (uint)n.TokenFlags);
                break;
            case RegularExpressionLiteralNode n:
                writer.WriteBase64String("Text", n.Text.Span);
                writer.WriteNumber("TokenFlags", (uint)n.TokenFlags);
                break;
            case NoSubstitutionTemplateLiteralNode n:
                writer.WriteNumber("TemplateFlags", (uint)n.TemplateFlags);
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case PrefixUnaryExpressionNode n:
                writer.WriteNumber("Operator", (int)n.Operator);
                break;
            case PostfixUnaryExpressionNode n:
                writer.WriteNumber("Operator", (int)n.Operator);
                break;
            case MetaPropertyNode n:
                writer.WriteNumber("KeywordToken", (int)n.KeywordToken);
                break;
            case ArrayLiteralExpressionNode n:
                writer.WriteBoolean("MultiLine", n.MultiLine);
                break;
            case ObjectLiteralExpressionNode n:
                writer.WriteBoolean("MultiLine", n.MultiLine);
                break;
            case TypeOperatorNode n:
                writer.WriteNumber("Operator", (int)n.Operator);
                break;
            case ImportAttributesNode n:
                writer.WriteBoolean("MultiLine", n.MultiLine);
                writer.WriteNumber("Token", (int)n.Token);
                break;
            case TemplateHeadNode n:
                writer.WriteBase64String("RawText", n.RawText.Span);
                writer.WriteNumber("TemplateFlags", (uint)n.TemplateFlags);
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case TemplateMiddleNode n:
                writer.WriteBase64String("RawText", n.RawText.Span);
                writer.WriteNumber("TemplateFlags", (uint)n.TemplateFlags);
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case TemplateTailNode n:
                writer.WriteBase64String("RawText", n.RawText.Span);
                writer.WriteNumber("TemplateFlags", (uint)n.TemplateFlags);
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case SyntheticExpressionNode n:
                writer.WriteBoolean("IsSpread", n.IsSpread);
                if (n.Type is not null) throw new InvalidOperationException("Cannot serialize semantic state SyntheticExpression.Type as parser syntax.");
                writer.WriteNull("Type");
                break;
            case JsxTextNode n:
                writer.WriteBoolean("ContainsOnlyTriviaWhiteSpaces", n.ContainsOnlyTriviaWhiteSpaces);
                writer.WriteBase64String("Text", n.Text.Span);
                break;
            case ModuleDeclarationNode n:
                writer.WriteNumber("Keyword", (int)n.Keyword);
                break;
            case ImportEqualsDeclarationNode n:
                writer.WriteBoolean("IsTypeOnly", n.IsTypeOnly);
                break;
            case ExportDeclarationNode n:
                writer.WriteBoolean("IsTypeOnly", n.IsTypeOnly);
                break;
            case ImportTypeNode n:
                writer.WriteBoolean("IsTypeOf", n.IsTypeOf);
                break;
            case ImportClauseNode n:
                writer.WriteNumber("PhaseModifier", (int)n.PhaseModifier);
                break;
            case ImportSpecifierNode n:
                writer.WriteBoolean("IsTypeOnly", n.IsTypeOnly);
                break;
            case JSDocTextNode n:
                writer.WriteStartArray("Text");
                foreach (Utf8String value in n.Text) writer.WriteBase64StringValue(value.Span);
                writer.WriteEndArray();
                break;
            case JSDocLinkNode n:
                writer.WriteStartArray("Text");
                foreach (Utf8String value in n.Text) writer.WriteBase64StringValue(value.Span);
                writer.WriteEndArray();
                break;
            case JSDocLinkPlainNode n:
                writer.WriteStartArray("Text");
                foreach (Utf8String value in n.Text) writer.WriteBase64StringValue(value.Span);
                writer.WriteEndArray();
                break;
            case JSDocLinkCodeNode n:
                writer.WriteStartArray("Text");
                foreach (Utf8String value in n.Text) writer.WriteBase64StringValue(value.Span);
                writer.WriteEndArray();
                break;
            case JSDocTypeLiteralNode n:
                writer.WriteBoolean("IsArrayType", n.IsArrayType);
                break;
            case JSDocParameterOrPropertyTagNode n:
                writer.WriteBoolean("IsBracketed", n.IsBracketed);
                writer.WriteBoolean("IsNameFirst", n.IsNameFirst);
                break;
        }
        writer.WriteEndObject();
    }

    public static void WriteLists(Utf8JsonWriter writer, SyntaxNode node, Func<int, int> position)
    {
        writer.WriteStartObject();
        switch (node)
        {
            case CaseBlockNode n:
                writer.WritePropertyName("Clauses");
                WriteList(writer, n.Clauses, position);
                break;
            case CaseOrDefaultClauseNode n:
                writer.WritePropertyName("Statements");
                WriteList(writer, n.Statements, position);
                break;
            case BlockNode n:
                writer.WritePropertyName("Statements");
                WriteList(writer, n.Statements, position);
                break;
            case VariableStatementNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case VariableDeclarationListNode n:
                writer.WritePropertyName("Declarations");
                WriteList(writer, n.Declarations, position);
                break;
            case BindingPatternNode n:
                writer.WritePropertyName("Elements");
                WriteList(writer, n.Elements, position);
                break;
            case ParameterDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case MissingDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case FunctionDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case ClassDeclarationNode n:
                writer.WritePropertyName("HeritageClauses");
                WriteList(writer, n.HeritageClauses, position);
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case ClassExpressionNode n:
                writer.WritePropertyName("HeritageClauses");
                WriteList(writer, n.HeritageClauses, position);
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case HeritageClauseNode n:
                writer.WritePropertyName("Types");
                WriteList(writer, n.Types, position);
                break;
            case InterfaceDeclarationNode n:
                writer.WritePropertyName("HeritageClauses");
                WriteList(writer, n.HeritageClauses, position);
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case TypeAliasDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case EnumDeclarationNode n:
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ModuleBlockNode n:
                writer.WritePropertyName("Statements");
                WriteList(writer, n.Statements, position);
                break;
            case ImportDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case NamedImportsNode n:
                writer.WritePropertyName("Elements");
                WriteList(writer, n.Elements, position);
                break;
            case ExportAssignmentNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case NamespaceExportDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case NamedExportsNode n:
                writer.WritePropertyName("Elements");
                WriteList(writer, n.Elements, position);
                break;
            case CallSignatureDeclarationNode n:
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case ConstructSignatureDeclarationNode n:
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case ConstructorDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case GetAccessorDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case SetAccessorDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case IndexSignatureDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                break;
            case MethodSignatureDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case MethodDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case PropertySignatureDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case PropertyDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ClassStaticBlockDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case BinaryExpressionNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ArrowFunctionNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case FunctionExpressionNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case CallExpressionNode n:
                writer.WritePropertyName("Arguments");
                WriteList(writer, n.Arguments, position);
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case NewExpressionNode n:
                writer.WritePropertyName("Arguments");
                WriteList(writer, n.Arguments, position);
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case TemplateExpressionNode n:
                writer.WritePropertyName("TemplateSpans");
                WriteList(writer, n.TemplateSpans, position);
                break;
            case TaggedTemplateExpressionNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case ArrayLiteralExpressionNode n:
                writer.WritePropertyName("Elements");
                WriteList(writer, n.Elements, position);
                break;
            case ObjectLiteralExpressionNode n:
                writer.WritePropertyName("Properties");
                WriteList(writer, n.Properties, position);
                break;
            case PropertyAssignmentNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ShorthandPropertyAssignmentNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case UnionTypeNode n:
                writer.WritePropertyName("Types");
                WriteList(writer, n.Types, position);
                break;
            case IntersectionTypeNode n:
                writer.WritePropertyName("Types");
                WriteList(writer, n.Types, position);
                break;
            case TypeReferenceNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case ExpressionWithTypeArgumentsNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case ImportAttributesNode n:
                writer.WritePropertyName("Attributes");
                WriteList(writer, n.Attributes, position);
                break;
            case TypeQueryNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case MappedTypeNode n:
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                break;
            case TypeLiteralNode n:
                writer.WritePropertyName("Members");
                WriteList(writer, n.Members, position);
                break;
            case TupleTypeNode n:
                writer.WritePropertyName("Elements");
                WriteList(writer, n.Elements, position);
                break;
            case FunctionTypeNode n:
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case ConstructorTypeNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case TemplateLiteralTypeNode n:
                writer.WritePropertyName("TemplateSpans");
                WriteList(writer, n.TemplateSpans, position);
                break;
            case JsxElementNode n:
                writer.WritePropertyName("Children");
                WriteList(writer, n.Children, position);
                break;
            case JsxAttributesNode n:
                writer.WritePropertyName("Properties");
                WriteList(writer, n.Properties, position);
                break;
            case JsxOpeningElementNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case JsxSelfClosingElementNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case JsxFragmentNode n:
                writer.WritePropertyName("Children");
                WriteList(writer, n.Children, position);
                break;
            case JSDocNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                writer.WritePropertyName("Tags");
                WriteList(writer, n.Tags, position);
                break;
            case JSDocTypeTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocUnknownTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocTemplateTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case JSDocReturnTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocPublicTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocPrivateTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocProtectedTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocReadonlyTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocOverrideTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocDeprecatedTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocSeeTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocImplementsTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocAugmentsTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocSatisfiesTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocThrowsTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocThisTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocImportTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocCallbackTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocOverloadTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocTypedefTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
            case JSDocSignatureNode n:
                writer.WritePropertyName("Parameters");
                WriteList(writer, n.Parameters, position);
                writer.WritePropertyName("TypeParameters");
                WriteList(writer, n.TypeParameters, position);
                break;
            case SourceFileNode n:
                writer.WritePropertyName("Statements");
                WriteList(writer, n.Statements, position);
                break;
            case ModuleDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ImportEqualsDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ExportDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case ImportTypeNode n:
                writer.WritePropertyName("TypeArguments");
                WriteList(writer, n.TypeArguments, position);
                break;
            case TypeParameterDeclarationNode n:
                writer.WritePropertyName("Modifiers");
                WriteList(writer, n.Modifiers, position);
                break;
            case JSDocParameterOrPropertyTagNode n:
                writer.WritePropertyName("Comment");
                WriteList(writer, n.Comment, position);
                break;
        }
        writer.WriteEndObject();
    }

    private static void WriteList(Utf8JsonWriter writer, NodeList? list, Func<int, int> position)
    {
        if (list is null) { writer.WriteNullValue(); return; }
        writer.WriteStartArray();
        writer.WriteNumberValue(list.Count);
        writer.WriteNumberValue(position(list.Pos));
        writer.WriteNumberValue(position(list.End));
        writer.WriteBooleanValue(list.HasTrailingComma);
        writer.WriteEndArray();
    }
}
