// <auto-generated />
namespace TypeScript.Compiler.Checking;

// types.go SHA256 01391a463e16ec9fa8e4a3317b6a6c77fe2a39c740a85ddd660f8548bf162c6d
[Flags]
public enum TypeFlags : uint
{
    None = 0,
    Any = 1u << 0,
    Unknown = 1u << 1,
    Undefined = 1u << 2,
    Null = 1u << 3,
    Void = 1u << 4,
    String = 1u << 5,
    Number = 1u << 6,
    BigInt = 1u << 7,
    Boolean = 1u << 8,
    ESSymbol = 1u << 9,
    StringLiteral = 1u << 10,
    NumberLiteral = 1u << 11,
    BigIntLiteral = 1u << 12,
    BooleanLiteral = 1u << 13,
    UniqueESSymbol = 1u << 14,
    EnumLiteral = 1u << 15,
    Enum = 1u << 16,
    NonPrimitive = 1u << 17,
    Never = 1u << 18,
    TypeParameter = 1u << 19,
    Object = 1u << 20,
    Index = 1u << 21,
    TemplateLiteral = 1u << 22,
    StringMapping = 1u << 23,
    Substitution = 1u << 24,
    IndexedAccess = 1u << 25,
    Conditional = 1u << 26,
    Union = 1u << 27,
    Intersection = 1u << 28,
    Reserved1 = 1u << 29,
    Reserved2 = 1u << 30,
    Reserved3 = 1u << 31,
    AnyOrUnknown = Any | Unknown,
    Nullable = Undefined | Null,
    Literal = StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral,
    Unit = Enum | Literal | UniqueESSymbol | Nullable,
    Freshable = Enum | Literal,
    StringOrNumberLiteral = StringLiteral | NumberLiteral,
    StringOrNumberLiteralOrUnique = StringLiteral | NumberLiteral | UniqueESSymbol,
    DefinitelyFalsy = StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral | Void | Undefined | Null,
    PossiblyFalsy = DefinitelyFalsy | String | Number | BigInt | Boolean,
    Intrinsic = Any | Unknown | String | Number | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive,
    StringLike = String | StringLiteral | TemplateLiteral | StringMapping,
    NumberLike = Number | NumberLiteral | Enum,
    BigIntLike = BigInt | BigIntLiteral,
    BooleanLike = Boolean | BooleanLiteral,
    EnumLike = Enum | EnumLiteral,
    ESSymbolLike = ESSymbol | UniqueESSymbol,
    VoidLike = Void | Undefined,
    Primitive = StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | VoidLike | Null,
    DefinitelyNonNullable = StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | Object | NonPrimitive,
    DisjointDomains = NonPrimitive | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbolLike | VoidLike | Null,
    UnionOrIntersection = Union | Intersection,
    StructuredType = Object | Union | Intersection,
    TypeVariable = TypeParameter | IndexedAccess,
    InstantiableNonPrimitive = TypeVariable | Conditional | Substitution,
    InstantiablePrimitive = Index | TemplateLiteral | StringMapping,
    Instantiable = InstantiableNonPrimitive | InstantiablePrimitive,
    StructuredOrInstantiable = StructuredType | Instantiable,
    ObjectFlagsType = Any | Nullable | Never | Object | Union | Intersection,
    Simplifiable = IndexedAccess | Conditional | Index,
    Singleton = Any | Unknown | String | Number | Boolean | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive,
    Narrowable = Any | Unknown | StructuredOrInstantiable | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbol | UniqueESSymbol | NonPrimitive,
    IncludesMask = Any | Unknown | Primitive | Never | Object | Union | Intersection | NonPrimitive | TemplateLiteral | StringMapping,
    IncludesMissingType = TypeParameter,
    IncludesNonWideningType = Index,
    IncludesWildcard = IndexedAccess,
    IncludesEmptyObject = Conditional,
    IncludesInstantiable = Substitution,
    IncludesConstrainedTypeVariable = Reserved1,
    IncludesError = Reserved2,
    NotPrimitiveUnion = Any | Unknown | Void | Never | Object | Intersection | IncludesInstantiable,
}

[Flags]
public enum ObjectFlags : uint
{
    None = 0,
    Class = 1u << 0,
    Interface = 1u << 1,
    Reference = 1u << 2,
    Tuple = 1u << 3,
    Anonymous = 1u << 4,
    Mapped = 1u << 5,
    Instantiated = 1u << 6,
    ObjectLiteral = 1u << 7,
    EvolvingArray = 1u << 8,
    ObjectLiteralPatternWithComputedProperties = 1u << 9,
    ReverseMapped = 1u << 10,
    JsxAttributes = 1u << 11,
    JSLiteral = 1u << 12,
    FreshLiteral = 1u << 13,
    ArrayLiteral = 1u << 14,
    PrimitiveUnion = 1u << 15,
    ContainsWideningType = 1u << 16,
    ContainsObjectOrArrayLiteral = 1u << 17,
    NonInferrableType = 1u << 18,
    CouldContainTypeVariablesComputed = 1u << 19,
    CouldContainTypeVariables = 1u << 20,
    MembersResolved = 1u << 21,
    ClassOrInterface = Class | Interface,
    RequiresWidening = ContainsWideningType | ContainsObjectOrArrayLiteral,
    PropagatingFlags = ContainsWideningType | ContainsObjectOrArrayLiteral | NonInferrableType,
    InstantiatedMapped = Mapped | Instantiated,
    ObjectTypeKindMask = ClassOrInterface | Reference | Tuple | Anonymous | Mapped | ReverseMapped | EvolvingArray | InstantiationExpressionType | SingleSignatureType,
    ContainsSpread = 1u << 22,
    ObjectRestType = 1u << 23,
    InstantiationExpressionType = 1u << 24,
    SingleSignatureType = 1u << 25,
    IsClassInstanceClone = 1u << 26,
    IdenticalBaseTypeCalculated = 1u << 27,
    IdenticalBaseTypeExists = 1u << 28,
    UnresolvedMembers = 1u << 29,
    FromTypeNode = 1u << 30,
    IsGenericTypeComputed = 1u << 22,
    IsGenericObjectType = 1u << 23,
    IsGenericIndexType = 1u << 24,
    IsGenericType = IsGenericObjectType | IsGenericIndexType,
    ContainsIntersections = 1u << 25,
    IsUnknownLikeUnionComputed = 1u << 26,
    IsUnknownLikeUnion = 1u << 27,
    IsUniformEnumComputed = 1u << 28,
    IsUniformEnum = 1u << 29,
    IsNeverIntersectionComputed = 1u << 25,
    IsNeverIntersection = 1u << 26,
    IsConstrainedTypeVariable = 1u << 27,
}

[Flags]
public enum SignatureFlags : uint
{
    None = 0,
    HasRestParameter = 1u << 0,
    HasLiteralTypes = 1u << 1,
    Construct = 1u << 2,
    Abstract = 1u << 3,
    IsInnerCallChain = 1u << 4,
    IsOuterCallChain = 1u << 5,
    IsUntypedSignatureInJSFile = 1u << 6,
    IsNonInferrable = 1u << 7,
    IsSignatureCandidateForOverloadFailure = 1u << 8,
    PropagatingFlags = HasRestParameter | HasLiteralTypes | Construct | Abstract | IsUntypedSignatureInJSFile | IsSignatureCandidateForOverloadFailure,
    CallChainFlags = IsInnerCallChain | IsOuterCallChain,
}

[Flags]
public enum ElementFlags : uint
{
    None = 0,
    Required = 1u << 0,
    Optional = 1u << 1,
    Rest = 1u << 2,
    Variadic = 1u << 3,
    Fixed = Required | Optional,
    Variable = Rest | Variadic,
    NonRequired = Optional | Rest | Variadic,
    NonRest = Required | Optional | Variadic,
}

[Flags]
public enum AccessFlags : uint
{
    None = 0,
    IncludeUndefined = 1u << 0,
    NoIndexSignatures = 1u << 1,
    Writing = 1u << 2,
    CacheSymbol = 1u << 3,
    AllowMissing = 1u << 4,
    ExpressionPosition = 1u << 5,
    ReportDeprecated = 1u << 6,
    SuppressNoImplicitAnyError = 1u << 7,
    Contextual = 1u << 8,
    Persistent = IncludeUndefined,
}

[Flags]
public enum IndexFlags : uint
{
    None = 0,
    StringsOnly = 1u << 0,
    NoIndexSignatures = 1u << 1,
    NoReducibleCheck = 1u << 2,
}

[Flags]
public enum VarianceFlags : uint
{
    Invariant = 0,
    Covariant = 1u << 0,
    Contravariant = 1u << 1,
    Bivariant = Covariant | Contravariant,
    Independent = 1u << 2,
    VarianceMask = Invariant | Covariant | Contravariant | Independent,
    Unmeasurable = 1u << 3,
    Unreliable = 1u << 4,
    AllowsStructuralFallback = Unmeasurable | Unreliable,
}

[Flags]
public enum NodeCheckFlags : uint
{
    None = 0,
    TypeChecked = 1u << 0,
    ContextChecked = 1u << 6,
    EnumValuesComputed = 1u << 10,
    AssignmentsMarked = 1u << 17,
    ContainsClassWithPrivateIdentifiers = 1u << 20,
    ContainsSuperPropertyInStaticInitializer = 1u << 21,
    InCheckIdentifier = 1u << 22,
    InitializerIsUndefined = 1u << 24,
    InitializerIsUndefinedComputed = 1u << 25,
}

public enum TypePredicateKind : int
{
    This = 0,
    Identifier = 1,
    AssertsThis = 2,
    AssertsIdentifier = 3,
}

public enum SignatureKind : int
{
    Call = 0,
    Construct = 1,
}

public enum Ternary : sbyte
{
    False = 0,
    Unknown = 1,
    Maybe = 3,
    True = -1,
}

// checker.go SHA256 f6dbbfd2d0816458155609717ebb0325e6b7751654df69a426a98d682e6cdd17
public enum TypeSystemPropertyName : int
{
    Type = 0,
    ResolvedBaseConstructorType = 1,
    DeclaredType = 2,
    ResolvedReturnType = 3,
    ResolvedBaseConstraint = 4,
    ResolvedTypeArguments = 5,
    ResolvedBaseTypes = 6,
    WriteType = 7,
    InitializerIsUndefined = 8,
    AliasTarget = 9,
}

public enum UnionReduction : int
{
    None = 0,
    Literal = 1,
    Subtype = 2,
}

[Flags]
public enum IntersectionFlags : uint
{
    None = 0,
    NoSupertypeReduction = 1u << 0,
    NoConstraintReduction = 1u << 1,
}
