// <auto-generated />
namespace TypeScript.Compiler.Checking;

// types.go SHA256 01391a463e16ec9fa8e4a3317b6a6c77fe2a39c740a85ddd660f8548bf162c6d
[Flags]
public enum TypeFlags : uint
{
    None = 0,
    Any = 1u << 0,
    Unknown = 1u << 1,
    Undefined = 1u << 2,
    Null = 1u << 3,
    Void = 1u << 4,
    String = 1u << 5,
    Number = 1u << 6,
    BigInt = 1u << 7,
    Boolean = 1u << 8,
    ESSymbol = 1u << 9,
    StringLiteral = 1u << 10,
    NumberLiteral = 1u << 11,
    BigIntLiteral = 1u << 12,
    BooleanLiteral = 1u << 13,
    UniqueESSymbol = 1u << 14,
    EnumLiteral = 1u << 15,
    Enum = 1u << 16,
    NonPrimitive = 1u << 17,
    Never = 1u << 18,
    TypeParameter = 1u << 19,
    Object = 1u << 20,
    Index = 1u << 21,
    TemplateLiteral = 1u << 22,
    StringMapping = 1u << 23,
    Substitution = 1u << 24,
    IndexedAccess = 1u << 25,
    Conditional = 1u << 26,
    Union = 1u << 27,
    Intersection = 1u << 28,
    Reserved1 = 1u << 29,
    Reserved2 = 1u << 30,
    Reserved3 = 1u << 31,
    AnyOrUnknown = Any | Unknown,
    Nullable = Undefined | Null,
    Literal = StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral,
    Unit = Enum | Literal | UniqueESSymbol | Nullable,
    Freshable = Enum | Literal,
    StringOrNumberLiteral = StringLiteral | NumberLiteral,
    StringOrNumberLiteralOrUnique = StringLiteral | NumberLiteral | UniqueESSymbol,
    DefinitelyFalsy = StringLiteral | NumberLiteral | BigIntLiteral | BooleanLiteral | Void | Undefined | Null,
    PossiblyFalsy = DefinitelyFalsy | String | Number | BigInt | Boolean,
    Intrinsic = Any | Unknown | String | Number | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive,
    StringLike = String | StringLiteral | TemplateLiteral | StringMapping,
    NumberLike = Number | NumberLiteral | Enum,
    BigIntLike = BigInt | BigIntLiteral,
    BooleanLike = Boolean | BooleanLiteral,
    EnumLike = Enum | EnumLiteral,
    ESSymbolLike = ESSymbol | UniqueESSymbol,
    VoidLike = Void | Undefined,
    Primitive = StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | VoidLike | Null,
    DefinitelyNonNullable = StringLike | NumberLike | BigIntLike | BooleanLike | EnumLike | ESSymbolLike | Object | NonPrimitive,
    DisjointDomains = NonPrimitive | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbolLike | VoidLike | Null,
    UnionOrIntersection = Union | Intersection,
    StructuredType = Object | Union | Intersection,
    TypeVariable = TypeParameter | IndexedAccess,
    InstantiableNonPrimitive = TypeVariable | Conditional | Substitution,
    InstantiablePrimitive = Index | TemplateLiteral | StringMapping,
    Instantiable = InstantiableNonPrimitive | InstantiablePrimitive,
    StructuredOrInstantiable = StructuredType | Instantiable,
    ObjectFlagsType = Any | Nullable | Never | Object | Union | Intersection,
    Simplifiable = IndexedAccess | Conditional | Index,
    Singleton = Any | Unknown | String | Number | Boolean | BigInt | ESSymbol | Void | Undefined | Null | Never | NonPrimitive,
    Narrowable = Any | Unknown | StructuredOrInstantiable | StringLike | NumberLike | BigIntLike | BooleanLike | ESSymbol | UniqueESSymbol | NonPrimitive,
    IncludesMask = Any | Unknown | Primitive | Never | Object | Union | Intersection | NonPrimitive | TemplateLiteral | StringMapping,
    IncludesMissingType = TypeParameter,
    IncludesNonWideningType = Index,
    IncludesWildcard = IndexedAccess,
    IncludesEmptyObject = Conditional,
    IncludesInstantiable = Substitution,
    IncludesConstrainedTypeVariable = Reserved1,
    IncludesError = Reserved2,
    NotPrimitiveUnion = Any | Unknown | Void | Never | Object | Intersection | IncludesInstantiable,
}

[Flags]
public enum ObjectFlags : uint
{
    None = 0,
    Class = 1u << 0,
    Interface = 1u << 1,
    Reference = 1u << 2,
    Tuple = 1u << 3,
    Anonymous = 1u << 4,
    Mapped = 1u << 5,
    Instantiated = 1u << 6,
    ObjectLiteral = 1u << 7,
    EvolvingArray = 1u << 8,
    ObjectLiteralPatternWithComputedProperties = 1u << 9,
    ReverseMapped = 1u << 10,
    JsxAttributes = 1u << 11,
    JSLiteral = 1u << 12,
    FreshLiteral = 1u << 13,
    ArrayLiteral = 1u << 14,
    PrimitiveUnion = 1u << 15,
    ContainsWideningType = 1u << 16,
    ContainsObjectOrArrayLiteral = 1u << 17,
    NonInferrableType = 1u << 18,
    CouldContainTypeVariablesComputed = 1u << 19,
    CouldContainTypeVariables = 1u << 20,
    MembersResolved = 1u << 21,
    ClassOrInterface = Class | Interface,
    RequiresWidening = ContainsWideningType | ContainsObjectOrArrayLiteral,
    PropagatingFlags = ContainsWideningType | ContainsObjectOrArrayLiteral | NonInferrableType,
    InstantiatedMapped = Mapped | Instantiated,
    ObjectTypeKindMask = ClassOrInterface | Reference | Tuple | Anonymous | Mapped | ReverseMapped | EvolvingArray | InstantiationExpressionType | SingleSignatureType,
    ContainsSpread = 1u << 22,
    ObjectRestType = 1u << 23,
    InstantiationExpressionType = 1u << 24,
    SingleSignatureType = 1u << 25,
    IsClassInstanceClone = 1u << 26,
    IdenticalBaseTypeCalculated = 1u << 27,
    IdenticalBaseTypeExists = 1u << 28,
    UnresolvedMembers = 1u << 29,
    FromTypeNode = 1u << 30,
    IsGenericTypeComputed = 1u << 22,
    IsGenericObjectType = 1u << 23,
    IsGenericIndexType = 1u << 24,
    IsGenericType = IsGenericObjectType | IsGenericIndexType,
    ContainsIntersections = 1u << 25,
    IsUnknownLikeUnionComputed = 1u << 26,
    IsUnknownLikeUnion = 1u << 27,
    IsUniformEnumComputed = 1u << 28,
    IsUniformEnum = 1u << 29,
    IsNeverIntersectionComputed = 1u << 25,
    IsNeverIntersection = 1u << 26,
    IsConstrainedTypeVariable = 1u << 27,
}

[Flags]
public enum SignatureFlags : uint
{
    None = 0,
    HasRestParameter = 1u << 0,
    HasLiteralTypes = 1u << 1,
    Construct = 1u << 2,
    Abstract = 1u << 3,
    IsInnerCallChain = 1u << 4,
    IsOuterCallChain = 1u << 5,
    IsUntypedSignatureInJSFile = 1u << 6,
    IsNonInferrable = 1u << 7,
    IsSignatureCandidateForOverloadFailure = 1u << 8,
    PropagatingFlags = HasRestParameter | HasLiteralTypes | Construct | Abstract | IsUntypedSignatureInJSFile | IsSignatureCandidateForOverloadFailure,
    CallChainFlags = IsInnerCallChain | IsOuterCallChain,
}

[Flags]
public enum ElementFlags : uint
{
    None = 0,
    Required = 1u << 0,
    Optional = 1u << 1,
    Rest = 1u << 2,
    Variadic = 1u << 3,
    Fixed = Required | Optional,
    Variable = Rest | Variadic,
    NonRequired = Optional | Rest | Variadic,
    NonRest = Required | Optional | Variadic,
}

[Flags]
public enum AccessFlags : uint
{
    None = 0,
    IncludeUndefined = 1u << 0,
    NoIndexSignatures = 1u << 1,
    Writing = 1u << 2,
    CacheSymbol = 1u << 3,
    AllowMissing = 1u << 4,
    ExpressionPosition = 1u << 5,
    ReportDeprecated = 1u << 6,
    SuppressNoImplicitAnyError = 1u << 7,
    Contextual = 1u << 8,
    Persistent = IncludeUndefined,
}

[Flags]
public enum IndexFlags : uint
{
    None = 0,
    StringsOnly = 1u << 0,
    NoIndexSignatures = 1u << 1,
    NoReducibleCheck = 1u << 2,
}

[Flags]
public enum VarianceFlags : uint
{
    Invariant = 0,
    Covariant = 1u << 0,
    Contravariant = 1u << 1,
    Bivariant = Covariant | Contravariant,
    Independent = 1u << 2,
    VarianceMask = Invariant | Covariant | Contravariant | Independent,
    Unmeasurable = 1u << 3,
    Unreliable = 1u << 4,
    AllowsStructuralFallback = Unmeasurable | Unreliable,
}

[Flags]
public enum NodeCheckFlags : uint
{
    None = 0,
    TypeChecked = 1u << 0,
    ContextChecked = 1u << 6,
    EnumValuesComputed = 1u << 10,
    AssignmentsMarked = 1u << 17,
    ContainsClassWithPrivateIdentifiers = 1u << 20,
    ContainsSuperPropertyInStaticInitializer = 1u << 21,
    InCheckIdentifier = 1u << 22,
    InitializerIsUndefined = 1u << 24,
    InitializerIsUndefinedComputed = 1u << 25,
}

public enum TypePredicateKind : int
{
    This = 0,
    Identifier = 1,
    AssertsThis = 2,
    AssertsIdentifier = 3,
}

public enum SignatureKind : int
{
    Call = 0,
    Construct = 1,
}

public enum Ternary : sbyte
{
    False = 0,
    Unknown = 1,
    Maybe = 3,
    True = -1,
}

[Flags]
public enum ContextFlags : uint
{
    None = 0,
    Signature = 1u << 0,
    NoConstraints = 1u << 1,
    IgnoreNodeInferences = 1u << 2,
    SkipBindingPatterns = 1u << 3,
}

[Flags]
public enum SymbolFormatFlags : uint
{
    None = 0,
    WriteTypeParametersOrArguments = 1u << 0,
    UseOnlyExternalAliasing = 1u << 1,
    AllowAnyNodeKind = 1u << 2,
    UseAliasDefinedOutsideCurrentScope = 1u << 3,
    WriteComputedProps = 1u << 4,
    DoNotIncludeSymbolChain = 1u << 5,
}

// checker.go SHA256 f6dbbfd2d0816458155609717ebb0325e6b7751654df69a426a98d682e6cdd17
public enum TypeSystemPropertyName : int
{
    Type = 0,
    ResolvedBaseConstructorType = 1,
    DeclaredType = 2,
    ResolvedReturnType = 3,
    ResolvedBaseConstraint = 4,
    ResolvedTypeArguments = 5,
    ResolvedBaseTypes = 6,
    WriteType = 7,
    InitializerIsUndefined = 8,
    AliasTarget = 9,
}

public enum UnionReduction : int
{
    None = 0,
    Literal = 1,
    Subtype = 2,
}

[Flags]
public enum IntersectionFlags : uint
{
    None = 0,
    NoSupertypeReduction = 1u << 0,
    NoConstraintReduction = 1u << 1,
}

[Flags]
public enum MappedTypeModifiers : uint
{
    IncludeReadonly = 1u << 0,
    ExcludeReadonly = 1u << 1,
    IncludeOptional = 1u << 2,
    ExcludeOptional = 1u << 3,
}

public enum MappedTypeNameTypeKind : int
{
    None = 0,
    Filtering = 1,
    Remapping = 2,
}

[Flags]
public enum TypeFacts : uint
{
    None = 0,
    TypeofEQString = 1u << 0,
    TypeofEQNumber = 1u << 1,
    TypeofEQBigInt = 1u << 2,
    TypeofEQBoolean = 1u << 3,
    TypeofEQSymbol = 1u << 4,
    TypeofEQObject = 1u << 5,
    TypeofEQFunction = 1u << 6,
    TypeofEQHostObject = 1u << 7,
    TypeofNEString = 1u << 8,
    TypeofNENumber = 1u << 9,
    TypeofNEBigInt = 1u << 10,
    TypeofNEBoolean = 1u << 11,
    TypeofNESymbol = 1u << 12,
    TypeofNEObject = 1u << 13,
    TypeofNEFunction = 1u << 14,
    TypeofNEHostObject = 1u << 15,
    EQUndefined = 1u << 16,
    EQNull = 1u << 17,
    EQUndefinedOrNull = 1u << 18,
    NEUndefined = 1u << 19,
    NENull = 1u << 20,
    NEUndefinedOrNull = 1u << 21,
    Truthy = 1u << 22,
    Falsy = 1u << 23,
    IsUndefined = 1u << 24,
    IsNull = 1u << 25,
    IsUndefinedOrNull = IsUndefined | IsNull,
    All = (1u << 27) - 1,
    BaseStringStrictFacts = TypeofEQString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | NEUndefined | NENull | NEUndefinedOrNull,
    BaseStringFacts = BaseStringStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    StringStrictFacts = BaseStringStrictFacts | Truthy | Falsy,
    StringFacts = BaseStringFacts | Truthy,
    EmptyStringStrictFacts = BaseStringStrictFacts | Falsy,
    EmptyStringFacts = BaseStringFacts,
    NonEmptyStringStrictFacts = BaseStringStrictFacts | Truthy,
    NonEmptyStringFacts = BaseStringFacts | Truthy,
    BaseNumberStrictFacts = TypeofEQNumber | TypeofNEString | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | NEUndefined | NENull | NEUndefinedOrNull,
    BaseNumberFacts = BaseNumberStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    NumberStrictFacts = BaseNumberStrictFacts | Truthy | Falsy,
    NumberFacts = BaseNumberFacts | Truthy,
    ZeroNumberStrictFacts = BaseNumberStrictFacts | Falsy,
    ZeroNumberFacts = BaseNumberFacts,
    NonZeroNumberStrictFacts = BaseNumberStrictFacts | Truthy,
    NonZeroNumberFacts = BaseNumberFacts | Truthy,
    BaseBigIntStrictFacts = TypeofEQBigInt | TypeofNEString | TypeofNENumber | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | NEUndefined | NENull | NEUndefinedOrNull,
    BaseBigIntFacts = BaseBigIntStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    BigIntStrictFacts = BaseBigIntStrictFacts | Truthy | Falsy,
    BigIntFacts = BaseBigIntFacts | Truthy,
    ZeroBigIntStrictFacts = BaseBigIntStrictFacts | Falsy,
    ZeroBigIntFacts = BaseBigIntFacts,
    NonZeroBigIntStrictFacts = BaseBigIntStrictFacts | Truthy,
    NonZeroBigIntFacts = BaseBigIntFacts | Truthy,
    BaseBooleanStrictFacts = TypeofEQBoolean | TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | NEUndefined | NENull | NEUndefinedOrNull,
    BaseBooleanFacts = BaseBooleanStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    BooleanStrictFacts = BaseBooleanStrictFacts | Truthy | Falsy,
    BooleanFacts = BaseBooleanFacts | Truthy,
    FalseStrictFacts = BaseBooleanStrictFacts | Falsy,
    FalseFacts = BaseBooleanFacts,
    TrueStrictFacts = BaseBooleanStrictFacts | Truthy,
    TrueFacts = BaseBooleanFacts | Truthy,
    SymbolStrictFacts = TypeofEQSymbol | TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | NEUndefined | NENull | NEUndefinedOrNull | Truthy,
    SymbolFacts = SymbolStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    ObjectStrictFacts = TypeofEQObject | TypeofEQHostObject | TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEFunction | NEUndefined | NENull | NEUndefinedOrNull | Truthy,
    ObjectFacts = ObjectStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    FunctionStrictFacts = TypeofEQFunction | TypeofEQHostObject | TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | NEUndefined | NENull | NEUndefinedOrNull | Truthy,
    FunctionFacts = FunctionStrictFacts | EQUndefined | EQNull | EQUndefinedOrNull | Falsy,
    VoidFacts = TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | EQUndefined | EQUndefinedOrNull | NENull | Falsy,
    UndefinedFacts = TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | TypeofNEHostObject | EQUndefined | EQUndefinedOrNull | NENull | Falsy | IsUndefined,
    NullFacts = TypeofEQObject | TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEFunction | TypeofNEHostObject | EQNull | EQUndefinedOrNull | NEUndefined | Falsy | IsNull,
    EmptyObjectStrictFacts = All & ~(EQUndefined | EQNull | EQUndefinedOrNull | IsUndefinedOrNull),
    EmptyObjectFacts = All & ~IsUndefinedOrNull,
    UnknownFacts = All & ~IsUndefinedOrNull,
    AllTypeofNE = TypeofNEString | TypeofNENumber | TypeofNEBigInt | TypeofNEBoolean | TypeofNESymbol | TypeofNEObject | TypeofNEFunction | NEUndefined,
    OrFactsMask = TypeofEQFunction | TypeofNEObject,
    AndFactsMask = All & ~OrFactsMask,
}

[Flags]
public enum InferenceFlags : uint
{
    None = 0,
    NoDefault = 1u << 0,
    AnyDefault = 1u << 1,
    SkippedGenericFunction = 1u << 2,
    NoConstraintChecks = 1u << 3,
}

[Flags]
public enum InferencePriority : int
{
    None = 0,
    NakedTypeVariable = 1 << 0,
    SpeculativeTuple = 1 << 1,
    SubstituteSource = 1 << 2,
    HomomorphicMappedType = 1 << 3,
    PartialHomomorphicMappedType = 1 << 4,
    MappedTypeConstraint = 1 << 5,
    ContravariantConditional = 1 << 6,
    ReturnType = 1 << 7,
    LiteralKeyof = 1 << 8,
    NoConstraints = 1 << 9,
    AlwaysStrict = 1 << 10,
    MaxValue = 1 << 11,
    Circularity = -1,
    PriorityImpliesCombination = ReturnType | MappedTypeConstraint | LiteralKeyof,
}

[Flags]
public enum CheckMode : uint
{
    Normal = 0,
    Contextual = 1u << 0,
    Inferential = 1u << 1,
    SkipContextSensitive = 1u << 2,
    SkipGenericFunctions = 1u << 3,
    IsForSignatureHelp = 1u << 4,
    RestBindingElement = 1u << 5,
    TypeOnly = 1u << 6,
    ForceTuple = 1u << 7,
}

public enum WideningKind : int
{
    Normal = 0,
    FunctionReturn = 1,
    GeneratorNext = 2,
    GeneratorYield = 3,
}

[Flags]
public enum IterationUse : uint
{
    AllowsSyncIterablesFlag = 1u << 0,
    AllowsAsyncIterablesFlag = 1u << 1,
    AllowsStringInputFlag = 1u << 2,
    ForOfFlag = 1u << 3,
    YieldStarFlag = 1u << 4,
    SpreadFlag = 1u << 5,
    DestructuringFlag = 1u << 6,
    PossiblyOutOfBounds = 1u << 7,
    Element = AllowsSyncIterablesFlag,
    Spread = AllowsSyncIterablesFlag | SpreadFlag,
    Destructuring = AllowsSyncIterablesFlag | DestructuringFlag,
    ForOf = AllowsSyncIterablesFlag | AllowsStringInputFlag | ForOfFlag,
    ForAwaitOf = AllowsSyncIterablesFlag | AllowsAsyncIterablesFlag | AllowsStringInputFlag | ForOfFlag,
    YieldStar = AllowsSyncIterablesFlag | YieldStarFlag,
    AsyncYieldStar = AllowsSyncIterablesFlag | AllowsAsyncIterablesFlag | YieldStarFlag,
    GeneratorReturnType = AllowsSyncIterablesFlag,
    AsyncGeneratorReturnType = AllowsAsyncIterablesFlag,
    CacheFlags = AllowsSyncIterablesFlag | AllowsAsyncIterablesFlag | ForOfFlag,
}

public enum IterationTypeKind : int
{
    Yield = 0,
    Return = 1,
    Next = 2,
}

[Flags]
public enum DeclarationSpaces : uint
{
    None = 0,
    ExportValue = 1u << 0,
    ExportType = 1u << 1,
    ExportNamespace = 1u << 2,
}

// relater.go SHA256 e191ef007847b5827a87d0310838594ec53bce1fca12bfb736637ea5299e99e3
[Flags]
public enum SignatureCheckMode : uint
{
    None = 0,
    BivariantCallback = 1u << 0,
    StrictCallback = 1u << 1,
    IgnoreReturnTypes = 1u << 2,
    StrictArity = 1u << 3,
    StrictTopSignature = 1u << 4,
    Callback = BivariantCallback | StrictCallback,
}

[Flags]
public enum MinArgumentCountFlags : uint
{
    None = 0,
    StrongArityForUntypedJS = 1u << 0,
    VoidIsNonOptional = 1u << 1,
}

[Flags]
public enum IntersectionState : uint
{
    None = 0,
    Source = 1u << 0,
    Target = 1u << 1,
}

[Flags]
public enum RecursionFlags : uint
{
    None = 0,
    Source = 1u << 0,
    Target = 1u << 1,
    Both = Source | Target,
}

[Flags]
public enum ExpandingFlags : uint
{
    None = 0,
    Source = 1u << 0,
    Target = 1u << 1,
    Both = Source | Target,
}

[Flags]
public enum RelationComparisonResult : uint
{
    None = 0,
    Succeeded = 1u << 0,
    Failed = 1u << 1,
    ReportsUnmeasurable = 1u << 3,
    ReportsUnreliable = 1u << 4,
    ComplexityOverflow = 1u << 5,
    ReportsMask = ReportsUnmeasurable | ReportsUnreliable,
    Overflow = ComplexityOverflow,
}

// ../nodebuilder/types.go SHA256 1cbbf774332b79f7747e71b20bffac1095f16a5cb4a8db87c6031cbd5707ea2e
[Flags]
public enum NodeBuilderFlags : uint
{
    None = 0,
    NoTruncation = 1u << 0,
    WriteArrayAsGenericType = 1u << 1,
    GenerateNamesForShadowedTypeParams = 1u << 2,
    UseStructuralFallback = 1u << 3,
    ForbidIndexedAccessSymbolReferences = 1u << 4,
    WriteTypeArgumentsOfSignature = 1u << 5,
    UseFullyQualifiedType = 1u << 6,
    UseOnlyExternalAliasing = 1u << 7,
    SuppressAnyReturnType = 1u << 8,
    WriteTypeParametersInQualifiedName = 1u << 9,
    MultilineObjectLiterals = 1u << 10,
    WriteClassExpressionAsTypeLiteral = 1u << 11,
    UseTypeOfFunction = 1u << 12,
    OmitParameterModifiers = 1u << 13,
    UseAliasDefinedOutsideCurrentScope = 1u << 14,
    UseSingleQuotesForStringLiteralType = 1u << 28,
    NoTypeReduction = 1u << 29,
    UseInstantiationExpressions = 1u << 30,
    OmitThisParameter = 1u << 25,
    WriteCallStyleSignature = 1u << 27,
    AllowThisInObjectLiteral = 1u << 15,
    AllowQualifiedNameInPlaceOfIdentifier = 1u << 16,
    AllowAnonymousIdentifier = 1u << 17,
    AllowEmptyUnionOrIntersection = 1u << 18,
    AllowEmptyTuple = 1u << 19,
    AllowUniqueESSymbolType = 1u << 20,
    AllowEmptyIndexInfoType = 1u << 21,
    AllowNodeModulesRelativePaths = 1u << 26,
    IgnoreErrors = AllowThisInObjectLiteral | AllowQualifiedNameInPlaceOfIdentifier | AllowAnonymousIdentifier | AllowEmptyUnionOrIntersection | AllowEmptyTuple | AllowEmptyIndexInfoType | AllowNodeModulesRelativePaths,
    InObjectTypeLiteral = 1u << 22,
    InTypeAlias = 1u << 23,
    InInitialEntityName = 1u << 24,
}

// ../printer/emitresolver.go SHA256 fca5be1776634a74e643e565ea599876be2c88c0bb5ac47bac70ddfdb19031c4
public enum TypeReferenceSerializationKind : int
{
    Unknown = 0,
    TypeWithConstructSignatureAndValue = 1,
    VoidNullableOrNeverType = 2,
    NumberLikeType = 3,
    BigIntLikeType = 4,
    StringLikeType = 5,
    BooleanType = 6,
    ArrayLikeType = 7,
    ESSymbolType = 8,
    Promise = 9,
    TypeWithCallSignature = 10,
    ObjectType = 11,
}

// ../ast/modifierflags.go SHA256 50506485a8ff50b536d1cac387cf031a82133b7507a0e5a0a09cd257b50d67c8
[Flags]
public enum ModifierFlags : uint
{
    None = 0,
    Public = 1u << 0,
    Private = 1u << 1,
    Protected = 1u << 2,
    Readonly = 1u << 3,
    Override = 1u << 4,
    Export = 1u << 5,
    Abstract = 1u << 6,
    Ambient = 1u << 7,
    Static = 1u << 8,
    Accessor = 1u << 9,
    Async = 1u << 10,
    Default = 1u << 11,
    Const = 1u << 12,
    In = 1u << 13,
    Out = 1u << 14,
    Decorator = 1u << 15,
    Deprecated = 1u << 16,
    JSDocPublic = 1u << 23,
    JSDocPrivate = 1u << 24,
    JSDocProtected = 1u << 25,
    JSDocReadonly = 1u << 26,
    JSDocOverride = 1u << 27,
    HasComputedJSDocModifiers = 1u << 28,
    HasComputedFlags = 1u << 29,
    SyntacticOrJSDocModifiers = Public | Private | Protected | Readonly | Override,
    SyntacticOnlyModifiers = Export | Ambient | Abstract | Static | Accessor | Async | Default | Const | In | Out | Decorator,
    SyntacticModifiers = SyntacticOrJSDocModifiers | SyntacticOnlyModifiers,
    JSDocCacheOnlyModifiers = JSDocPublic | JSDocPrivate | JSDocProtected | JSDocReadonly | JSDocOverride,
    JSDocOnlyModifiers = Deprecated,
    NonCacheOnlyModifiers = SyntacticOrJSDocModifiers | SyntacticOnlyModifiers | JSDocOnlyModifiers,
    AccessibilityModifier = Public | Private | Protected,
    ParameterPropertyModifier = AccessibilityModifier | Readonly | Override,
    NonPublicAccessibilityModifier = Private | Protected,
    TypeScriptModifier = Ambient | Public | Private | Protected | Readonly | Abstract | Const | Override | In | Out,
    ExportDefault = Export | Default,
    All = Export | Ambient | Public | Private | Protected | Static | Readonly | Abstract | Accessor | Async | Default | Const | Deprecated | Override | In | Out | Decorator,
    Modifier = All & ~Decorator,
    JavaScript = Export | Static | Accessor | Async | Default,
}
