// <auto-generated />
#nullable enable
// utilities.go SHA256 0c0dfcbccf2128a1290a74a33cbf090b78c313b143151443b3e16326201ae302
using TypeScript.Compiler.Text;
namespace TypeScript.Compiler.Checking;

internal static class LibraryFeatures
{
    internal static string? PropertyLibrary(TextSlice? type, ReadOnlySpan<char> property) => type.GetValueOrDefault().Span switch
    {
        "Array" => property switch
        {
            "find" or "findIndex" or "fill" or "copyWithin" or "entries" or "keys" or "values" => "es2015",
            "includes" => "es2016",
            "flat" or "flatMap" => "es2019",
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Iterator" => property switch
        {
            _ => null
        },
        "AsyncIterator" => property switch
        {
            _ => null
        },
        "ArrayBuffer" => property switch
        {
            "maxByteLength" or "resizable" or "resize" or "detached" or "transfer" or "transferToFixedLength" => "es2024",
            _ => null
        },
        "Atomics" => property switch
        {
            "add" or "and" or "compareExchange" or "exchange" or "isLockFree" or "load" or "or" or "store" or "sub" or "wait" or "notify" or "xor" => "es2017",
            "waitAsync" => "es2024",
            _ => null
        },
        "SharedArrayBuffer" => property switch
        {
            "byteLength" or "slice" => "es2017",
            "growable" or "maxByteLength" or "grow" => "es2024",
            _ => null
        },
        "AsyncIterable" => property switch
        {
            _ => null
        },
        "AsyncIterableIterator" => property switch
        {
            _ => null
        },
        "AsyncGenerator" => property switch
        {
            _ => null
        },
        "AsyncGeneratorFunction" => property switch
        {
            _ => null
        },
        "RegExp" => property switch
        {
            "flags" or "sticky" or "unicode" => "es2015",
            "dotAll" => "es2018",
            "unicodeSets" => "es2024",
            _ => null
        },
        "RegExpConstructor" => property switch
        {
            "escape" => "es2025",
            _ => null
        },
        "Reflect" => property switch
        {
            "apply" or "construct" or "defineProperty" or "deleteProperty" or "get" or "getOwnPropertyDescriptor" or "getPrototypeOf" or "has" or "isExtensible" or "ownKeys" or "preventExtensions" or "set" or "setPrototypeOf" => "es2015",
            _ => null
        },
        "ArrayConstructor" => property switch
        {
            "from" or "of" => "es2015",
            "fromAsync" => "esnext",
            _ => null
        },
        "ObjectConstructor" => property switch
        {
            "assign" or "getOwnPropertySymbols" or "keys" or "is" or "setPrototypeOf" => "es2015",
            "values" or "entries" or "getOwnPropertyDescriptors" => "es2017",
            "fromEntries" => "es2019",
            "hasOwn" => "es2022",
            "groupBy" => "es2024",
            _ => null
        },
        "NumberConstructor" => property switch
        {
            "isFinite" or "isInteger" or "isNaN" or "isSafeInteger" or "parseFloat" or "parseInt" => "es2015",
            _ => null
        },
        "Math" => property switch
        {
            "clz32" or "imul" or "sign" or "log10" or "log2" or "log1p" or "expm1" or "cosh" or "sinh" or "tanh" or "acosh" or "asinh" or "atanh" or "hypot" or "trunc" or "fround" or "cbrt" => "es2015",
            "f16round" => "es2025",
            _ => null
        },
        "Map" => property switch
        {
            "entries" or "keys" or "values" => "es2015",
            "getOrInsert" or "getOrInsertComputed" => "esnext",
            _ => null
        },
        "MapConstructor" => property switch
        {
            "groupBy" => "es2024",
            _ => null
        },
        "Set" => property switch
        {
            "entries" or "keys" or "values" => "es2015",
            "union" or "intersection" or "difference" or "symmetricDifference" or "isSubsetOf" or "isSupersetOf" or "isDisjointFrom" => "es2025",
            _ => null
        },
        "PromiseConstructor" => property switch
        {
            "all" or "race" or "reject" or "resolve" => "es2015",
            "allSettled" => "es2020",
            "any" => "es2021",
            "withResolvers" => "es2024",
            "try" => "es2025",
            _ => null
        },
        "Symbol" => property switch
        {
            "for" or "keyFor" => "es2015",
            "description" => "es2019",
            _ => null
        },
        "WeakMap" => property switch
        {
            "getOrInsert" or "getOrInsertComputed" => "esnext",
            _ => null
        },
        "WeakSet" => property switch
        {
            _ => null
        },
        "String" => property switch
        {
            "codePointAt" or "includes" or "endsWith" or "normalize" or "repeat" or "startsWith" or "anchor" or "big" or "blink" or "bold" or "fixed" or "fontcolor" or "fontsize" or "italics" or "link" or "small" or "strike" or "sub" or "sup" => "es2015",
            "padStart" or "padEnd" => "es2017",
            "trimStart" or "trimEnd" or "trimLeft" or "trimRight" => "es2019",
            "matchAll" => "es2020",
            "replaceAll" => "es2021",
            "at" => "es2022",
            "isWellFormed" or "toWellFormed" => "es2024",
            _ => null
        },
        "StringConstructor" => property switch
        {
            "fromCodePoint" or "raw" => "es2015",
            _ => null
        },
        "DateTimeFormat" => property switch
        {
            "formatToParts" => "es2017",
            _ => null
        },
        "Promise" => property switch
        {
            "finally" => "es2018",
            _ => null
        },
        "RegExpMatchArray" => property switch
        {
            "groups" => "es2018",
            _ => null
        },
        "RegExpExecArray" => property switch
        {
            "groups" => "es2018",
            _ => null
        },
        "Intl" => property switch
        {
            "PluralRules" => "es2018",
            "RelativeTimeFormat" or "Locale" or "DisplayNames" => "es2020",
            "ListFormat" or "DateTimeFormat" => "es2021",
            "Segmenter" => "es2022",
            "DurationFormat" => "es2025",
            _ => null
        },
        "NumberFormat" => property switch
        {
            "formatToParts" => "es2018",
            _ => null
        },
        "SymbolConstructor" => property switch
        {
            "matchAll" => "es2020",
            "metadata" or "dispose" or "asyncDispose" => "esnext",
            _ => null
        },
        "DataView" => property switch
        {
            "setBigInt64" or "setBigUint64" or "getBigInt64" or "getBigUint64" => "es2020",
            "setFloat16" or "getFloat16" => "es2025",
            _ => null
        },
        "BigInt" => property switch
        {
            _ => null
        },
        "RelativeTimeFormat" => property switch
        {
            "format" or "formatToParts" or "resolvedOptions" => "es2020",
            _ => null
        },
        "Int8Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Uint8Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Uint8ClampedArray" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Int16Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Uint16Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Int32Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Uint32Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Float16Array" => property switch
        {
            _ => null
        },
        "Float32Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Float64Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "BigInt64Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "BigUint64Array" => property switch
        {
            "at" => "es2022",
            "findLastIndex" or "findLast" or "toReversed" or "toSorted" or "toSpliced" or "with" => "es2023",
            _ => null
        },
        "Error" => property switch
        {
            "cause" => "es2022",
            _ => null
        },
        "ErrorConstructor" => property switch
        {
            "isError" => "esnext",
            _ => null
        },
        "Uint8ArrayConstructor" => property switch
        {
            "fromBase64" or "fromHex" => "esnext",
            _ => null
        },
        "DisposableStack" => property switch
        {
            _ => null
        },
        "AsyncDisposableStack" => property switch
        {
            _ => null
        },
        "Date" => property switch
        {
            "toTemporalInstant" => "esnext",
            _ => null
        },
        _ => null
    };

    internal static string? NameLibrary(ReadOnlySpan<char> name) => name switch
    {
        "Array" => "es2015",
        "Iterator" => "es2015",
        "AsyncIterator" => "es2015",
        "ArrayBuffer" => "es2024",
        "Atomics" => "es2017",
        "SharedArrayBuffer" => "es2017",
        "AsyncIterable" => "es2018",
        "AsyncIterableIterator" => "es2018",
        "AsyncGenerator" => "es2018",
        "AsyncGeneratorFunction" => "es2018",
        "RegExp" => "es2015",
        "RegExpConstructor" => "es2025",
        "Reflect" => "es2015",
        "ArrayConstructor" => "es2015",
        "ObjectConstructor" => "es2015",
        "NumberConstructor" => "es2015",
        "Math" => "es2015",
        "Map" => "es2015",
        "MapConstructor" => "es2024",
        "Set" => "es2015",
        "PromiseConstructor" => "es2015",
        "Symbol" => "es2015",
        "WeakMap" => "es2015",
        "WeakSet" => "es2015",
        "String" => "es2015",
        "StringConstructor" => "es2015",
        "DateTimeFormat" => "es2017",
        "Promise" => "es2015",
        "RegExpMatchArray" => "es2018",
        "RegExpExecArray" => "es2018",
        "Intl" => "es2018",
        "NumberFormat" => "es2018",
        "SymbolConstructor" => "es2020",
        "DataView" => "es2020",
        "BigInt" => "es2020",
        "RelativeTimeFormat" => "es2020",
        "Int8Array" => "es2022",
        "Uint8Array" => "es2022",
        "Uint8ClampedArray" => "es2022",
        "Int16Array" => "es2022",
        "Uint16Array" => "es2022",
        "Int32Array" => "es2022",
        "Uint32Array" => "es2022",
        "Float16Array" => "es2025",
        "Float32Array" => "es2022",
        "Float64Array" => "es2022",
        "BigInt64Array" => "es2020",
        "BigUint64Array" => "es2020",
        "Error" => "es2022",
        "ErrorConstructor" => "esnext",
        "Uint8ArrayConstructor" => "esnext",
        "DisposableStack" => "esnext",
        "AsyncDisposableStack" => "esnext",
        "Date" => "esnext",
        _ => null
    };
}
