// <auto-generated />
// emitflags.go SHA256 9381afd50eb7e56849400ad7bff6150a2d792b7d0dad3988a6a43c00feb6b02e
namespace TypeScript.Compiler.Emission;

[Flags]
public enum EmitFlags : uint
{
    None = 0,
    SingleLine = 1 << 0,
    MultiLine = 1 << 1,
    NoLeadingSourceMap = 1 << 2,
    NoTrailingSourceMap = 1 << 3,
    NoNestedSourceMaps = 1 << 4,
    NoTokenLeadingSourceMaps = 1 << 5,
    NoTokenTrailingSourceMaps = 1 << 6,
    NoLeadingComments = 1 << 7,
    NoTrailingComments = 1 << 8,
    NoNestedComments = 1 << 9,
    HelperName = 1 << 10,
    ExportName = 1 << 11,
    LocalName = 1 << 12,
    Indented = 1 << 13,
    NoIndentation = 1 << 14,
    ReuseTempVariableScope = 1 << 15,
    CustomPrologue = 1 << 16,
    NoAsciiEscaping = 1 << 17,
    ExternalHelpers = 1 << 18,
    StartOnNewLine = 1 << 19,
    IndirectCall = 1 << 20,
    AsyncFunctionBody = 1 << 21,
    NoLexicalArguments = 1 << 22,
    TransformPrivateStaticElements = 1 << 23,
    NoLexicalThis = 1 << 24,
    NoSourceMap = NoLeadingSourceMap | NoTrailingSourceMap,
    NoTokenSourceMaps = NoTokenLeadingSourceMaps | NoTokenTrailingSourceMaps,
    NoComments = NoLeadingComments | NoTrailingComments,
}
