// <auto-generated />
// tsc/internal/format/rules.go; SHA256 6042e71a404d16cb1e305454811fec00babe75f56c34897dde185bb407de6ac8
using K = TypeScript.Compiler.Syntax.SyntaxKind;

namespace TypeScript.Compiler.LanguageServices;

internal static partial class FormattingRules
{
    private static RuleSpec[] CreateRules()
    {
        var allTokens = Range(K.FirstToken, K.LastToken).Tokens.Where(kind => kind != K.EndOfFile).ToArray();
        var anyToken = new TokenSet(allTokens, false);
        TokenSet Except(params K[] excluded) => new(allTokens.Where(kind => !excluded.Contains(kind)).ToArray(), false);
        var anyTokenIncludingMultilineComments = Tokens([.. allTokens, K.MultiLineCommentTrivia]);
        var anyTokenIncludingEOF = Tokens([.. allTokens, K.EndOfFile]);
        var binaryKeywordOperators = Tokens(K.InKeyword, K.InstanceOfKeyword, K.OfKeyword, K.AsKeyword, K.IsKeyword, K.SatisfiesKeyword);
        var unaryPrefixOperators = Tokens(K.PlusPlusToken, K.MinusToken, K.TildeToken, K.ExclamationToken);
        var unaryPrefixExpressions = Tokens(K.NumericLiteral, K.BigIntLiteral, K.Identifier, K.OpenParenToken, K.OpenBracketToken, K.OpenBraceToken, K.ThisKeyword, K.NewKeyword);
        var unaryPreincrementExpressions = Tokens(K.Identifier, K.OpenParenToken, K.ThisKeyword, K.NewKeyword);
        var unaryPostincrementExpressions = Tokens(K.Identifier, K.CloseParenToken, K.CloseBracketToken, K.NewKeyword);
        var unaryPredecrementExpressions = Tokens(K.Identifier, K.OpenParenToken, K.ThisKeyword, K.NewKeyword);
        var unaryPostdecrementExpressions = Tokens(K.Identifier, K.CloseParenToken, K.CloseBracketToken, K.NewKeyword);
        var comments = Tokens(K.SingleLineCommentTrivia, K.MultiLineCommentTrivia);
        var typeKeywords = Tokens(K.AnyKeyword, K.AssertsKeyword, K.BigIntKeyword, K.BooleanKeyword, K.FalseKeyword, K.InferKeyword, K.KeyOfKeyword, K.NeverKeyword, K.NullKeyword, K.NumberKeyword, K.ObjectKeyword, K.ReadonlyKeyword, K.StringKeyword, K.SymbolKeyword, K.TypeOfKeyword, K.TrueKeyword, K.VoidKeyword, K.UndefinedKeyword, K.UniqueKeyword, K.UnknownKeyword);
        var keywords = Range(K.FirstKeyword, K.LastKeyword);
        var binaryOperators = Range(K.FirstBinaryOperator, K.LastBinaryOperator);
        var typeScriptOpenBraceLeftTokenRange = Tokens(K.Identifier, K.GreaterThanToken, K.MultiLineCommentTrivia, K.ClassKeyword, K.ExportKeyword, K.ImportKeyword);
        var controlOpenBraceLeftTokenRange = Tokens(K.CloseParenToken, K.MultiLineCommentTrivia, K.DoKeyword, K.TryKeyword, K.FinallyKeyword, K.ElseKeyword, K.CatchKeyword);
        var typeNames = Tokens([K.Identifier, .. typeKeywords.Tokens]);
        var functionOpenBraceLeftTokenRange = anyTokenIncludingMultilineComments;
        return
        [
            R("IgnoreBeforeComment", anyToken, comments, [], FormattingAction.StopProcessingSpaceActions),
            R("IgnoreAfterLineComment", K.SingleLineCommentTrivia, anyToken, [], FormattingAction.StopProcessingSpaceActions),
            R("NotSpaceBeforeColon", anyToken, K.ColonToken, [P(IsNonJsxSameLineTokenContext), P(IsNotBinaryOpContext), P(IsNotTypeAnnotationContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterColon", K.ColonToken, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsNotBinaryOpContext), P(IsNextTokenParentNotJsxNamespacedName)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeQuestionMark", anyToken, K.QuestionToken, [P(IsNonJsxSameLineTokenContext), P(IsNotBinaryOpContext), P(IsNotTypeAnnotationContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterQuestionMarkInConditionalOperator", K.QuestionToken, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsConditionalOperatorContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterQuestionMark", K.QuestionToken, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsNonOptionalPropertyContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeDot", anyToken, Tokens(K.DotToken, K.QuestionDotToken), [P(IsNonJsxSameLineTokenContext), P(IsNotPropertyAccessOnIntegerLiteral)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterDot", Tokens(K.DotToken, K.QuestionDotToken), anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBetweenImportParenInImportType", K.ImportKeyword, K.OpenParenToken, [P(IsNonJsxSameLineTokenContext), P(IsImportTypeContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterUnaryPrefixOperator", unaryPrefixOperators, unaryPrefixExpressions, [P(IsNonJsxSameLineTokenContext), P(IsNotBinaryOpContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterUnaryPreincrementOperator", K.PlusPlusToken, unaryPreincrementExpressions, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterUnaryPredecrementOperator", K.MinusMinusToken, unaryPredecrementExpressions, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeUnaryPostincrementOperator", unaryPostincrementExpressions, K.PlusPlusToken, [P(IsNonJsxSameLineTokenContext), P(IsNotStatementConditionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeUnaryPostdecrementOperator", unaryPostdecrementExpressions, K.MinusMinusToken, [P(IsNonJsxSameLineTokenContext), P(IsNotStatementConditionContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterPostincrementWhenFollowedByAdd", K.PlusPlusToken, K.PlusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterAddWhenFollowedByUnaryPlus", K.PlusToken, K.PlusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterAddWhenFollowedByPreincrement", K.PlusToken, K.PlusPlusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterPostdecrementWhenFollowedBySubtract", K.MinusMinusToken, K.MinusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterSubtractWhenFollowedByUnaryMinus", K.MinusToken, K.MinusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterSubtractWhenFollowedByPredecrement", K.MinusToken, K.MinusMinusToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterCloseBrace", K.CloseBraceToken, Tokens(K.CommaToken, K.SemicolonToken), [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NewLineBeforeCloseBraceInBlockContext", anyTokenIncludingMultilineComments, K.CloseBraceToken, [P(IsMultilineBlockContext)], FormattingAction.InsertNewLine),
            R("SpaceAfterCloseBrace", K.CloseBraceToken, Except(K.CloseParenToken), [P(IsNonJsxSameLineTokenContext), P(IsAfterCodeBlockContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenCloseBraceAndElse", K.CloseBraceToken, K.ElseKeyword, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenCloseBraceAndWhile", K.CloseBraceToken, K.WhileKeyword, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenEmptyBraceBrackets", K.OpenBraceToken, K.CloseBraceToken, [P(IsNonJsxSameLineTokenContext), P(IsObjectContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterConditionalClosingParen", K.CloseParenToken, K.OpenBracketToken, [P(IsControlDeclContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenFunctionKeywordAndStar", K.FunctionKeyword, K.AsteriskToken, [P(IsFunctionDeclarationOrFunctionExpressionContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterStarInGeneratorDeclaration", K.AsteriskToken, K.Identifier, [P(IsFunctionDeclarationOrFunctionExpressionContext)], FormattingAction.InsertSpace),
            R("SpaceAfterFunctionInFuncDecl", K.FunctionKeyword, anyToken, [P(IsFunctionDeclContext)], FormattingAction.InsertSpace),
            R("NewLineAfterOpenBraceInBlockContext", K.OpenBraceToken, anyToken, [P(IsMultilineBlockContext)], FormattingAction.InsertNewLine),
            R("SpaceAfterGetSetInMember", Tokens(K.GetKeyword, K.SetKeyword), K.Identifier, [P(IsFunctionDeclContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenYieldKeywordAndStar", K.YieldKeyword, K.AsteriskToken, [P(IsNonJsxSameLineTokenContext), P(IsYieldOrYieldStarWithOperand)], FormattingAction.DeleteSpace),
            R("SpaceBetweenYieldOrYieldStarAndOperand", Tokens(K.YieldKeyword, K.AsteriskToken), anyToken, [P(IsNonJsxSameLineTokenContext), P(IsYieldOrYieldStarWithOperand)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenReturnAndSemicolon", K.ReturnKeyword, K.SemicolonToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterCertainKeywords", Tokens(K.VarKeyword, K.ThrowKeyword, K.NewKeyword, K.DeleteKeyword, K.ReturnKeyword, K.TypeOfKeyword, K.AwaitKeyword), anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceAfterLetConstInVariableDeclaration", Tokens(K.LetKeyword, K.ConstKeyword), anyToken, [P(IsNonJsxSameLineTokenContext), P(IsStartOfVariableDeclarationList)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeOpenParenInFuncCall", anyToken, K.OpenParenToken, [P(IsNonJsxSameLineTokenContext), P(IsFunctionCallOrNewContext), P(IsPreviousTokenNotComma)], FormattingAction.DeleteSpace),
            R("SpaceBeforeBinaryKeywordOperator", anyToken, binaryKeywordOperators, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterBinaryKeywordOperator", binaryKeywordOperators, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterVoidOperator", K.VoidKeyword, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsVoidOpContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenAsyncAndOpenParen", K.AsyncKeyword, K.OpenParenToken, [P(IsArrowFunctionContext), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenAsyncAndFunctionKeyword", K.AsyncKeyword, Tokens(K.FunctionKeyword, K.Identifier), [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenTagAndTemplateString", Tokens(K.Identifier, K.CloseParenToken), Tokens(K.NoSubstitutionTemplateLiteral, K.TemplateHead), [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeJsxAttribute", anyToken, K.Identifier, [P(IsNextTokenParentJsxAttribute), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeSlashInJsxOpeningElement", anyToken, K.SlashToken, [P(IsJsxSelfClosingElementContext), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeGreaterThanTokenInJsxOpeningElement", K.SlashToken, K.GreaterThanToken, [P(IsJsxSelfClosingElementContext), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeEqualInJsxAttribute", anyToken, K.EqualsToken, [P(IsJsxAttributeContext), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterEqualInJsxAttribute", K.EqualsToken, anyToken, [P(IsJsxAttributeContext), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeJsxNamespaceColon", K.Identifier, K.ColonToken, [P(IsNextTokenParentJsxNamespacedName)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterJsxNamespaceColon", K.ColonToken, K.Identifier, [P(IsNextTokenParentJsxNamespacedName)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterModuleImport", Tokens(K.ModuleKeyword, K.RequireKeyword), K.OpenParenToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterCertainTypeScriptKeywords", Tokens(K.AbstractKeyword, K.AccessorKeyword, K.ClassKeyword, K.DeclareKeyword, K.DefaultKeyword, K.EnumKeyword, K.ExportKeyword, K.ExtendsKeyword, K.GetKeyword, K.ImplementsKeyword, K.ImportKeyword, K.InterfaceKeyword, K.ModuleKeyword, K.NamespaceKeyword, K.OverrideKeyword, K.PrivateKeyword, K.PublicKeyword, K.ProtectedKeyword, K.ReadonlyKeyword, K.SetKeyword, K.StaticKeyword, K.TypeKeyword, K.FromKeyword, K.KeyOfKeyword, K.InferKeyword), anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeCertainTypeScriptKeywords", anyToken, Tokens(K.ExtendsKeyword, K.ImplementsKeyword, K.FromKeyword), [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceAfterModuleName", K.StringLiteral, K.OpenBraceToken, [P(IsModuleDeclContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeArrow", anyToken, K.EqualsGreaterThanToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceAfterArrow", K.EqualsGreaterThanToken, anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterEllipsis", K.DotDotDotToken, K.Identifier, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterOptionalParameters", K.QuestionToken, Tokens(K.CloseParenToken, K.CommaToken), [P(IsNonJsxSameLineTokenContext), P(IsNotBinaryOpContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBetweenEmptyInterfaceBraceBrackets", K.OpenBraceToken, K.CloseBraceToken, [P(IsNonJsxSameLineTokenContext), P(IsObjectTypeContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeOpenAngularBracket", typeNames, K.LessThanToken, [P(IsNonJsxSameLineTokenContext), P(IsTypeArgumentOrParameterOrAssertionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBetweenCloseParenAndAngularBracket", K.CloseParenToken, K.LessThanToken, [P(IsNonJsxSameLineTokenContext), P(IsTypeArgumentOrParameterOrAssertionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterOpenAngularBracket", K.LessThanToken, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsTypeArgumentOrParameterOrAssertionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeCloseAngularBracket", anyToken, K.GreaterThanToken, [P(IsNonJsxSameLineTokenContext), P(IsTypeArgumentOrParameterOrAssertionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterCloseAngularBracket", K.GreaterThanToken, Tokens(K.OpenParenToken, K.OpenBracketToken, K.GreaterThanToken, K.CommaToken), [P(IsNonJsxSameLineTokenContext), P(IsTypeArgumentOrParameterOrAssertionContext), P(IsNotFunctionDeclContext), P(IsNonTypeAssertionContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeAt", Tokens(K.CloseParenToken, K.Identifier), K.AtToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterAt", K.AtToken, anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterDecorator", anyToken, Tokens(K.AbstractKeyword, K.Identifier, K.ExportKeyword, K.DefaultKeyword, K.ClassKeyword, K.StaticKeyword, K.PublicKeyword, K.PrivateKeyword, K.ProtectedKeyword, K.GetKeyword, K.SetKeyword, K.OpenBracketToken, K.AsteriskToken), [P(IsEndOfDecoratorContextOnSameLine)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeNonNullAssertionOperator", anyToken, K.ExclamationToken, [P(IsNonJsxSameLineTokenContext), P(IsNonNullAssertionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterNewKeywordOnConstructorSignature", K.NewKeyword, K.OpenParenToken, [P(IsNonJsxSameLineTokenContext), P(IsConstructorSignatureContext)], FormattingAction.DeleteSpace),
            R("SpaceLessThanAndNonJSXTypeAnnotation", K.LessThanToken, K.LessThanToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceAfterConstructor", K.ConstructorKeyword, K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterConstructor == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterConstructor", K.ConstructorKeyword, K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterConstructor != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterComma", K.CommaToken, anyToken, [P(static c => c.Options.InsertSpaceAfterCommaDelimiter == true), P(IsNonJsxSameLineTokenContext), P(IsNonJsxElementOrFragmentContext), P(IsNextTokenNotCloseBracket), P(IsNextTokenNotCloseParen)], FormattingAction.InsertSpace),
            R("NoSpaceAfterComma", K.CommaToken, anyToken, [P(static c => c.Options.InsertSpaceAfterCommaDelimiter != true), P(IsNonJsxSameLineTokenContext), P(IsNonJsxElementOrFragmentContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterAnonymousFunctionKeyword", Tokens(K.FunctionKeyword, K.AsteriskToken), K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterFunctionKeywordForAnonymousFunctions == true), P(IsFunctionDeclContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterAnonymousFunctionKeyword", Tokens(K.FunctionKeyword, K.AsteriskToken), K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterFunctionKeywordForAnonymousFunctions != true), P(IsFunctionDeclContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterKeywordInControl", keywords, K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterKeywordsInControlFlowStatements == true), P(IsControlDeclContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterKeywordInControl", keywords, K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterKeywordsInControlFlowStatements != true), P(IsControlDeclContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterOpenParen", K.OpenParenToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeCloseParen", anyToken, K.CloseParenToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenOpenParens", K.OpenParenToken, K.OpenParenToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenParens", K.OpenParenToken, K.CloseParenToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterOpenParen", K.OpenParenToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeCloseParen", anyToken, K.CloseParenToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterOpenBracket", K.OpenBracketToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeCloseBracket", anyToken, K.CloseBracketToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenBrackets", K.OpenBracketToken, K.CloseBracketToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterOpenBracket", K.OpenBracketToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeCloseBracket", anyToken, K.CloseBracketToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterOpenBrace", K.OpenBraceToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces != false), P(IsBraceWrappedContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeCloseBrace", anyToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces != false), P(IsBraceWrappedContext)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenEmptyBraceBrackets", K.OpenBraceToken, K.CloseBraceToken, [P(IsNonJsxSameLineTokenContext), P(IsObjectContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterOpenBrace", K.OpenBraceToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces == false), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeCloseBrace", anyToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingNonemptyBraces == false), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceBetweenEmptyBraceBrackets", K.OpenBraceToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces == true)], FormattingAction.InsertSpace),
            R("NoSpaceBetweenEmptyBraceBrackets", K.OpenBraceToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingEmptyBraces == false), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterTemplateHeadAndMiddle", Tokens(K.TemplateHead, K.TemplateMiddle), anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces == true), P(IsNonJsxTextContext)], FormattingAction.InsertSpace, true),
            R("SpaceBeforeTemplateMiddleAndTail", anyToken, Tokens(K.TemplateMiddle, K.TemplateTail), [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces == true), P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterTemplateHeadAndMiddle", Tokens(K.TemplateHead, K.TemplateMiddle), anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces != true), P(IsNonJsxTextContext)], FormattingAction.DeleteSpace, true),
            R("NoSpaceBeforeTemplateMiddleAndTail", anyToken, Tokens(K.TemplateMiddle, K.TemplateTail), [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces != true), P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterOpenBraceInJsxExpression", K.OpenBraceToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces == true), P(IsNonJsxSameLineTokenContext), P(IsJsxExpressionContext)], FormattingAction.InsertSpace),
            R("SpaceBeforeCloseBraceInJsxExpression", anyToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces == true), P(IsNonJsxSameLineTokenContext), P(IsJsxExpressionContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterOpenBraceInJsxExpression", K.OpenBraceToken, anyToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces != true), P(IsNonJsxSameLineTokenContext), P(IsJsxExpressionContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeCloseBraceInJsxExpression", anyToken, K.CloseBraceToken, [P(static c => c.Options.InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces != true), P(IsNonJsxSameLineTokenContext), P(IsJsxExpressionContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterSemicolonInFor", K.SemicolonToken, anyToken, [P(static c => c.Options.InsertSpaceAfterSemicolonInForStatements == true), P(IsNonJsxSameLineTokenContext), P(IsForContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterSemicolonInFor", K.SemicolonToken, anyToken, [P(static c => c.Options.InsertSpaceAfterSemicolonInForStatements != true), P(IsNonJsxSameLineTokenContext), P(IsForContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeBinaryOperator", anyToken, binaryOperators, [P(static c => c.Options.InsertSpaceBeforeAndAfterBinaryOperators == true), P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("SpaceAfterBinaryOperator", binaryOperators, anyToken, [P(static c => c.Options.InsertSpaceBeforeAndAfterBinaryOperators == true), P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeBinaryOperator", anyToken, binaryOperators, [P(static c => c.Options.InsertSpaceBeforeAndAfterBinaryOperators != true), P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterBinaryOperator", binaryOperators, anyToken, [P(static c => c.Options.InsertSpaceBeforeAndAfterBinaryOperators != true), P(IsNonJsxSameLineTokenContext), P(IsBinaryOpContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeOpenParenInFuncDecl", anyToken, K.OpenParenToken, [P(static c => c.Options.InsertSpaceBeforeFunctionParenthesis == true), P(IsNonJsxSameLineTokenContext), P(IsFunctionDeclContext)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeOpenParenInFuncDecl", anyToken, K.OpenParenToken, [P(static c => c.Options.InsertSpaceBeforeFunctionParenthesis != true), P(IsNonJsxSameLineTokenContext), P(IsFunctionDeclContext)], FormattingAction.DeleteSpace),
            R("NewLineBeforeOpenBraceInControl", controlOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForControlBlocks == true), P(IsControlDeclContext), P(IsBeforeMultilineBlockContext)], FormattingAction.InsertNewLine, true),
            R("NewLineBeforeOpenBraceInFunction", functionOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForFunctions == true), P(IsFunctionDeclContext), P(IsBeforeMultilineBlockContext)], FormattingAction.InsertNewLine, true),
            R("NewLineBeforeOpenBraceInTypeScriptDeclWithBlock", typeScriptOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForFunctions == true), P(IsTypeScriptDeclWithBlockContext), P(IsBeforeMultilineBlockContext)], FormattingAction.InsertNewLine, true),
            R("SpaceAfterTypeAssertion", K.GreaterThanToken, anyToken, [P(static c => c.Options.InsertSpaceAfterTypeAssertion == true), P(IsNonJsxSameLineTokenContext), P(IsTypeAssertionContext)], FormattingAction.InsertSpace),
            R("NoSpaceAfterTypeAssertion", K.GreaterThanToken, anyToken, [P(static c => c.Options.InsertSpaceAfterTypeAssertion != true), P(IsNonJsxSameLineTokenContext), P(IsTypeAssertionContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeTypeAnnotation", anyToken, Tokens(K.QuestionToken, K.ColonToken), [P(static c => c.Options.InsertSpaceBeforeTypeAnnotation == true), P(IsNonJsxSameLineTokenContext), P(IsTypeAnnotationContext)], FormattingAction.InsertSpace),
            R("NoSpaceBeforeTypeAnnotation", anyToken, Tokens(K.QuestionToken, K.ColonToken), [P(static c => c.Options.InsertSpaceBeforeTypeAnnotation != true), P(IsNonJsxSameLineTokenContext), P(IsTypeAnnotationContext)], FormattingAction.DeleteSpace),
            R("NoOptionalSemicolon", K.SemicolonToken, anyTokenIncludingEOF, [P(static c => c.Options.Semicolons == SemicolonPreference.Remove), P(IsSemicolonDeletionContext)], FormattingAction.DeleteToken),
            R("OptionalSemicolon", anyToken, anyTokenIncludingEOF, [P(static c => c.Options.Semicolons == SemicolonPreference.Insert), P(IsSemicolonInsertionContext)], FormattingAction.InsertTrailingSemicolon),
            R("NoSpaceBeforeSemicolon", anyToken, K.SemicolonToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceBeforeOpenBraceInControl", controlOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForControlBlocks != true || c.TokensOnOneLine), P(IsControlDeclContext), P(IsNotFormatOnEnter), P(IsSameLineTokenOrBeforeBlockContext)], FormattingAction.InsertSpace, true),
            R("SpaceBeforeOpenBraceInFunction", functionOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForFunctions != true || c.TokensOnOneLine), P(IsFunctionDeclContext), P(IsBeforeBlockContext), P(IsNotFormatOnEnter), P(IsSameLineTokenOrBeforeBlockContext)], FormattingAction.InsertSpace, true),
            R("SpaceBeforeOpenBraceInTypeScriptDeclWithBlock", typeScriptOpenBraceLeftTokenRange, K.OpenBraceToken, [P(static c => c.Options.PlaceOpenBraceOnNewLineForFunctions != true || c.TokensOnOneLine), P(IsTypeScriptDeclWithBlockContext), P(IsNotFormatOnEnter), P(IsSameLineTokenOrBeforeBlockContext)], FormattingAction.InsertSpace, true),
            R("NoSpaceBeforeComma", anyToken, K.CommaToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceBeforeOpenBracket", Except(K.AsyncKeyword, K.CaseKeyword), K.OpenBracketToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("NoSpaceAfterCloseBracket", K.CloseBracketToken, anyToken, [P(IsNonJsxSameLineTokenContext), P(IsNotBeforeBlockInFunctionDeclarationContext)], FormattingAction.DeleteSpace),
            R("SpaceAfterSemicolon", K.SemicolonToken, anyToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenForAndAwaitKeyword", K.ForKeyword, K.AwaitKeyword, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
            R("SpaceBetweenDotDotDotAndTypeName", K.DotDotDotToken, typeNames, [P(IsNonJsxSameLineTokenContext)], FormattingAction.DeleteSpace),
            R("SpaceBetweenStatements", Tokens(K.CloseParenToken, K.DoKeyword, K.ElseKeyword, K.CaseKeyword), anyToken, [P(IsNonJsxSameLineTokenContext), P(IsNonJsxElementOrFragmentContext), P(IsNotForContext)], FormattingAction.InsertSpace),
            R("SpaceAfterTryCatchFinally", Tokens(K.TryKeyword, K.CatchKeyword, K.FinallyKeyword), K.OpenBraceToken, [P(IsNonJsxSameLineTokenContext)], FormattingAction.InsertSpace),
        ];
    }
}
