// <auto-generated />
#nullable enable
using System.Text.Json;
using TypeScript.Compiler.Text;
namespace TypeScript.Compiler.Configuration;

public enum ModuleDetectionKind
{
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}

public enum ModuleKind
{
    None = 0,
    CommonJS = 1,
    AMD = 2,
    UMD = 3,
    System = 4,
    ES2015 = 5,
    ES2020 = 6,
    ES2022 = 7,
    ESNext = 99,
    Node16 = 100,
    Node18 = 101,
    Node20 = 102,
    NodeNext = 199,
    Preserve = 200,
}

public enum ModuleResolutionKind
{
    Unknown = 0,
    Classic = 1,
    Node10 = 2,
    Node16 = 3,
    NodeNext = 99,
    Bundler = 100,
}

public enum NewLineKind
{
    None = 0,
    CRLF = 1,
    LF = 2,
}

public enum ScriptTarget
{
    None = 0,
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ES2021 = 8,
    ES2022 = 9,
    ES2023 = 10,
    ES2024 = 11,
    ES2025 = 12,
    ESNext = 99,
    JSON = 100,
}

public enum JsxEmit
{
    None = 0,
    Preserve = 1,
    React = 2,
    ReactNative = 3,
    ReactJSX = 4,
    ReactJSXDev = 5,
}

public sealed partial class CompilerOptions
{
    public bool? AllowJs { get; private set; }
    public bool? AllowArbitraryExtensions { get; private set; }
    public bool? AllowImportingTsExtensions { get; private set; }
    public bool? AllowNonTsExtensions { get; private set; }
    public bool? AllowUmdGlobalAccess { get; private set; }
    public bool? AllowUnreachableCode { get; private set; }
    public bool? AllowUnusedLabels { get; private set; }
    public bool? AssumeChangesOnlyAffectDirectDependencies { get; private set; }
    public bool? CheckJs { get; private set; }
    public Utf8String[]? CustomConditions { get; private set; }
    public bool? Composite { get; private set; }
    public bool? EmitDeclarationOnly { get; private set; }
    public bool? EmitBOM { get; private set; }
    public bool? EmitDecoratorMetadata { get; private set; }
    public bool? Declaration { get; private set; }
    public Utf8String? DeclarationDir { get; private set; }
    public bool? DeclarationMap { get; private set; }
    public bool? DeduplicatePackages { get; private set; }
    public bool? DisableSizeLimit { get; private set; }
    public bool? DisableSourceOfProjectReferenceRedirect { get; private set; }
    public bool? DisableSolutionSearching { get; private set; }
    public bool? DisableReferencedProjectLoad { get; private set; }
    public bool? ErasableSyntaxOnly { get; private set; }
    public bool? ExactOptionalPropertyTypes { get; private set; }
    public bool? ExperimentalDecorators { get; private set; }
    public bool? ForceConsistentCasingInFileNames { get; private set; }
    public bool? IsolatedModules { get; private set; }
    public bool? IsolatedDeclarations { get; private set; }
    public bool? IgnoreConfig { get; private set; }
    public Utf8String? IgnoreDeprecations { get; private set; }
    public bool? ImportHelpers { get; private set; }
    public bool? InlineSourceMap { get; private set; }
    public bool? InlineSources { get; private set; }
    public bool? Init { get; private set; }
    public bool? Incremental { get; private set; }
    public JsxEmit Jsx { get; private set; }
    public Utf8String? JsxFactory { get; private set; }
    public Utf8String? JsxFragmentFactory { get; private set; }
    public Utf8String? JsxImportSource { get; private set; }
    public Utf8String[]? Lib { get; private set; }
    public bool? LibReplacement { get; private set; }
    public Utf8String? Locale { get; private set; }
    public Utf8String? MapRoot { get; private set; }
    public ModuleKind Module { get; private set; }
    public ModuleResolutionKind ModuleResolution { get; private set; }
    public Utf8String[]? ModuleSuffixes { get; private set; }
    public ModuleDetectionKind ModuleDetection { get; private set; }
    public NewLineKind NewLine { get; private set; }
    public bool? NoEmit { get; private set; }
    public bool? NoCheck { get; private set; }
    public bool? NoErrorTruncation { get; private set; }
    public bool? NoFallthroughCasesInSwitch { get; private set; }
    public bool? NoImplicitAny { get; private set; }
    public bool? NoImplicitThis { get; private set; }
    public bool? NoImplicitReturns { get; private set; }
    public bool? NoEmitHelpers { get; private set; }
    public bool? NoLib { get; private set; }
    public bool? NoPropertyAccessFromIndexSignature { get; private set; }
    public bool? NoUncheckedIndexedAccess { get; private set; }
    public bool? NoEmitOnError { get; private set; }
    public bool? NoUnusedLocals { get; private set; }
    public bool? NoUnusedParameters { get; private set; }
    public bool? NoResolve { get; private set; }
    public bool? NoImplicitOverride { get; private set; }
    public bool? NoUncheckedSideEffectImports { get; private set; }
    public Utf8String? OutDir { get; private set; }
    public IReadOnlyList<KeyValuePair<Utf8String, Utf8String[]>>? Paths { get; private set; }
    public bool? PreserveConstEnums { get; private set; }
    public bool? PreserveSymlinks { get; private set; }
    public Utf8String? Project { get; private set; }
    public bool? ResolveJsonModule { get; private set; }
    public bool? ResolvePackageJsonExports { get; private set; }
    public bool? ResolvePackageJsonImports { get; private set; }
    public bool? RemoveComments { get; private set; }
    public bool? RewriteRelativeImportExtensions { get; private set; }
    public Utf8String? ReactNamespace { get; private set; }
    public Utf8String? RootDir { get; private set; }
    public Utf8String[]? RootDirs { get; private set; }
    public bool? SkipLibCheck { get; private set; }
    public bool? StableTypeOrdering { get; private set; }
    public bool? Strict { get; private set; }
    public bool? StrictBindCallApply { get; private set; }
    public bool? StrictBuiltinIteratorReturn { get; private set; }
    public bool? StrictFunctionTypes { get; private set; }
    public bool? StrictNullChecks { get; private set; }
    public bool? StrictPropertyInitialization { get; private set; }
    public bool? StripInternal { get; private set; }
    public bool? SkipDefaultLibCheck { get; private set; }
    public bool? SourceMap { get; private set; }
    public Utf8String? SourceRoot { get; private set; }
    public bool? SuppressOutputPathCheck { get; private set; }
    public ScriptTarget Target { get; private set; }
    public bool? TraceResolution { get; private set; }
    public Utf8String? TsBuildInfoFile { get; private set; }
    public Utf8String[]? TypeRoots { get; private set; }
    public Utf8String[]? Types { get; private set; }
    public bool? UseDefineForClassFields { get; private set; }
    public bool? UseUnknownInCatchVariables { get; private set; }
    public bool? VerbatimModuleSyntax { get; private set; }
    public int? MaxNodeModuleJsDepth { get; private set; }
    public bool? AllowSyntheticDefaultImports { get; private set; }
    public bool? AlwaysStrict { get; private set; }
    public Utf8String? BaseUrl { get; private set; }
    public bool? DownlevelIteration { get; private set; }
    public bool? ESModuleInterop { get; private set; }
    public Utf8String? OutFile { get; private set; }
    public Utf8String? ConfigFilePath { get; private set; }
    public bool? NoDtsResolution { get; private set; }
    public Utf8String? PathsBasePath { get; private set; }
    public bool? Diagnostics { get; private set; }
    public bool? ExtendedDiagnostics { get; private set; }
    public Utf8String? GenerateCpuProfile { get; private set; }
    public Utf8String? GenerateTrace { get; private set; }
    public bool? ListEmittedFiles { get; private set; }
    public bool? ListFiles { get; private set; }
    public bool? ExplainFiles { get; private set; }
    public bool? ListFilesOnly { get; private set; }
    public bool? NoEmitForJsFiles { get; private set; }
    public bool? PreserveWatchOutput { get; private set; }
    public bool? Pretty { get; private set; }
    public bool? Version { get; private set; }
    public bool? Watch { get; private set; }
    public bool? ShowConfig { get; private set; }
    public bool? Build { get; private set; }
    public bool? Help { get; private set; }
    public bool? All { get; private set; }
    public bool? RunExternalCode { get; private set; }
    public Utf8String? PprofDir { get; private set; }
    public bool? SingleThreaded { get; private set; }
    public bool? Quiet { get; private set; }
    public int? Checkers { get; private set; }
    public JsonElement[]? Plugins { get; private set; }

    private void AssignTyped(Utf8String name, JsonElement value, Utf8String? text)
    {
        switch (name)
        {
            case var _ when name == "allowJs"u8: AllowJs = ToBoolean(value); break;
            case var _ when name == "allowArbitraryExtensions"u8: AllowArbitraryExtensions = ToBoolean(value); break;
            case var _ when name == "allowImportingTsExtensions"u8: AllowImportingTsExtensions = ToBoolean(value); break;
            case var _ when name == "allowNonTsExtensions"u8: AllowNonTsExtensions = ToBoolean(value); break;
            case var _ when name == "allowUmdGlobalAccess"u8: AllowUmdGlobalAccess = ToBoolean(value); break;
            case var _ when name == "allowUnreachableCode"u8: AllowUnreachableCode = ToBoolean(value); break;
            case var _ when name == "allowUnusedLabels"u8: AllowUnusedLabels = ToBoolean(value); break;
            case var _ when name == "assumeChangesOnlyAffectDirectDependencies"u8: AssumeChangesOnlyAffectDirectDependencies = ToBoolean(value); break;
            case var _ when name == "checkJs"u8: CheckJs = ToBoolean(value); break;
            case var _ when name == "customConditions"u8: CustomConditions = ToStrings(value); break;
            case var _ when name == "composite"u8: Composite = ToBoolean(value); break;
            case var _ when name == "emitDeclarationOnly"u8: EmitDeclarationOnly = ToBoolean(value); break;
            case var _ when name == "emitBOM"u8: EmitBOM = ToBoolean(value); break;
            case var _ when name == "emitDecoratorMetadata"u8: EmitDecoratorMetadata = ToBoolean(value); break;
            case var _ when name == "declaration"u8: Declaration = ToBoolean(value); break;
            case var _ when name == "declarationDir"u8: DeclarationDir = text; break;
            case var _ when name == "declarationMap"u8: DeclarationMap = ToBoolean(value); break;
            case var _ when name == "deduplicatePackages"u8: DeduplicatePackages = ToBoolean(value); break;
            case var _ when name == "disableSizeLimit"u8: DisableSizeLimit = ToBoolean(value); break;
            case var _ when name == "disableSourceOfProjectReferenceRedirect"u8: DisableSourceOfProjectReferenceRedirect = ToBoolean(value); break;
            case var _ when name == "disableSolutionSearching"u8: DisableSolutionSearching = ToBoolean(value); break;
            case var _ when name == "disableReferencedProjectLoad"u8: DisableReferencedProjectLoad = ToBoolean(value); break;
            case var _ when name == "erasableSyntaxOnly"u8: ErasableSyntaxOnly = ToBoolean(value); break;
            case var _ when name == "exactOptionalPropertyTypes"u8: ExactOptionalPropertyTypes = ToBoolean(value); break;
            case var _ when name == "experimentalDecorators"u8: ExperimentalDecorators = ToBoolean(value); break;
            case var _ when name == "forceConsistentCasingInFileNames"u8: ForceConsistentCasingInFileNames = ToBoolean(value); break;
            case var _ when name == "isolatedModules"u8: IsolatedModules = ToBoolean(value); break;
            case var _ when name == "isolatedDeclarations"u8: IsolatedDeclarations = ToBoolean(value); break;
            case var _ when name == "ignoreConfig"u8: IgnoreConfig = ToBoolean(value); break;
            case var _ when name == "ignoreDeprecations"u8: IgnoreDeprecations = text; break;
            case var _ when name == "importHelpers"u8: ImportHelpers = ToBoolean(value); break;
            case var _ when name == "inlineSourceMap"u8: InlineSourceMap = ToBoolean(value); break;
            case var _ when name == "inlineSources"u8: InlineSources = ToBoolean(value); break;
            case var _ when name == "init"u8: Init = ToBoolean(value); break;
            case var _ when name == "incremental"u8: Incremental = ToBoolean(value); break;
            case var _ when name == "jsx"u8: Jsx = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberJsx) ? (JsxEmit)numberJsx : text switch { { } option when option == "preserve"u8 => (JsxEmit)1, { } option when option == "react-native"u8 => (JsxEmit)3, { } option when option == "react-jsx"u8 => (JsxEmit)4, { } option when option == "react-jsxdev"u8 => (JsxEmit)5, { } option when option == "react"u8 => (JsxEmit)2, _ => default }; break;
            case var _ when name == "jsxFactory"u8: JsxFactory = text; break;
            case var _ when name == "jsxFragmentFactory"u8: JsxFragmentFactory = text; break;
            case var _ when name == "jsxImportSource"u8: JsxImportSource = text; break;
            case var _ when name == "lib"u8: Lib = ToStrings(value); break;
            case var _ when name == "libReplacement"u8: LibReplacement = ToBoolean(value); break;
            case var _ when name == "locale"u8: Locale = text; break;
            case var _ when name == "mapRoot"u8: MapRoot = text; break;
            case var _ when name == "module"u8: Module = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModule) ? (ModuleKind)numberModule : text switch { { } option when option == "commonjs"u8 => (ModuleKind)1, { } option when option == "amd"u8 => (ModuleKind)2, { } option when option == "system"u8 => (ModuleKind)4, { } option when option == "umd"u8 => (ModuleKind)3, { } option when option == "es6"u8 => (ModuleKind)5, { } option when option == "es2015"u8 => (ModuleKind)5, { } option when option == "es2020"u8 => (ModuleKind)6, { } option when option == "es2022"u8 => (ModuleKind)7, { } option when option == "esnext"u8 => (ModuleKind)99, { } option when option == "node16"u8 => (ModuleKind)100, { } option when option == "node18"u8 => (ModuleKind)101, { } option when option == "node20"u8 => (ModuleKind)102, { } option when option == "nodenext"u8 => (ModuleKind)199, { } option when option == "preserve"u8 => (ModuleKind)200, _ => default }; break;
            case var _ when name == "moduleResolution"u8: ModuleResolution = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModuleResolution) ? (ModuleResolutionKind)numberModuleResolution : text switch { { } option when option == "node16"u8 => (ModuleResolutionKind)3, { } option when option == "nodenext"u8 => (ModuleResolutionKind)99, { } option when option == "bundler"u8 => (ModuleResolutionKind)100, { } option when option == "classic"u8 => (ModuleResolutionKind)1, { } option when option == "node"u8 => (ModuleResolutionKind)2, { } option when option == "node10"u8 => (ModuleResolutionKind)2, _ => default }; break;
            case var _ when name == "moduleSuffixes"u8: ModuleSuffixes = ToStrings(value); break;
            case var _ when name == "moduleDetection"u8: ModuleDetection = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModuleDetection) ? (ModuleDetectionKind)numberModuleDetection : text switch { { } option when option == "auto"u8 => (ModuleDetectionKind)1, { } option when option == "legacy"u8 => (ModuleDetectionKind)2, { } option when option == "force"u8 => (ModuleDetectionKind)3, _ => default }; break;
            case var _ when name == "newLine"u8: NewLine = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberNewLine) ? (NewLineKind)numberNewLine : text switch { { } option when option == "crlf"u8 => (NewLineKind)1, { } option when option == "lf"u8 => (NewLineKind)2, _ => default }; break;
            case var _ when name == "noEmit"u8: NoEmit = ToBoolean(value); break;
            case var _ when name == "noCheck"u8: NoCheck = ToBoolean(value); break;
            case var _ when name == "noErrorTruncation"u8: NoErrorTruncation = ToBoolean(value); break;
            case var _ when name == "noFallthroughCasesInSwitch"u8: NoFallthroughCasesInSwitch = ToBoolean(value); break;
            case var _ when name == "noImplicitAny"u8: NoImplicitAny = ToBoolean(value); break;
            case var _ when name == "noImplicitThis"u8: NoImplicitThis = ToBoolean(value); break;
            case var _ when name == "noImplicitReturns"u8: NoImplicitReturns = ToBoolean(value); break;
            case var _ when name == "noEmitHelpers"u8: NoEmitHelpers = ToBoolean(value); break;
            case var _ when name == "noLib"u8: NoLib = ToBoolean(value); break;
            case var _ when name == "noPropertyAccessFromIndexSignature"u8: NoPropertyAccessFromIndexSignature = ToBoolean(value); break;
            case var _ when name == "noUncheckedIndexedAccess"u8: NoUncheckedIndexedAccess = ToBoolean(value); break;
            case var _ when name == "noEmitOnError"u8: NoEmitOnError = ToBoolean(value); break;
            case var _ when name == "noUnusedLocals"u8: NoUnusedLocals = ToBoolean(value); break;
            case var _ when name == "noUnusedParameters"u8: NoUnusedParameters = ToBoolean(value); break;
            case var _ when name == "noResolve"u8: NoResolve = ToBoolean(value); break;
            case var _ when name == "noImplicitOverride"u8: NoImplicitOverride = ToBoolean(value); break;
            case var _ when name == "noUncheckedSideEffectImports"u8: NoUncheckedSideEffectImports = ToBoolean(value); break;
            case var _ when name == "outDir"u8: OutDir = text; break;
            case var _ when name == "paths"u8: Paths = ParsePaths(value); break;
            case var _ when name == "preserveConstEnums"u8: PreserveConstEnums = ToBoolean(value); break;
            case var _ when name == "preserveSymlinks"u8: PreserveSymlinks = ToBoolean(value); break;
            case var _ when name == "project"u8: Project = text; break;
            case var _ when name == "resolveJsonModule"u8: ResolveJsonModule = ToBoolean(value); break;
            case var _ when name == "resolvePackageJsonExports"u8: ResolvePackageJsonExports = ToBoolean(value); break;
            case var _ when name == "resolvePackageJsonImports"u8: ResolvePackageJsonImports = ToBoolean(value); break;
            case var _ when name == "removeComments"u8: RemoveComments = ToBoolean(value); break;
            case var _ when name == "rewriteRelativeImportExtensions"u8: RewriteRelativeImportExtensions = ToBoolean(value); break;
            case var _ when name == "reactNamespace"u8: ReactNamespace = text; break;
            case var _ when name == "rootDir"u8: RootDir = text; break;
            case var _ when name == "rootDirs"u8: RootDirs = ToStrings(value); break;
            case var _ when name == "skipLibCheck"u8: SkipLibCheck = ToBoolean(value); break;
            case var _ when name == "stableTypeOrdering"u8: StableTypeOrdering = ToBoolean(value); break;
            case var _ when name == "strict"u8: Strict = ToBoolean(value); break;
            case var _ when name == "strictBindCallApply"u8: StrictBindCallApply = ToBoolean(value); break;
            case var _ when name == "strictBuiltinIteratorReturn"u8: StrictBuiltinIteratorReturn = ToBoolean(value); break;
            case var _ when name == "strictFunctionTypes"u8: StrictFunctionTypes = ToBoolean(value); break;
            case var _ when name == "strictNullChecks"u8: StrictNullChecks = ToBoolean(value); break;
            case var _ when name == "strictPropertyInitialization"u8: StrictPropertyInitialization = ToBoolean(value); break;
            case var _ when name == "stripInternal"u8: StripInternal = ToBoolean(value); break;
            case var _ when name == "skipDefaultLibCheck"u8: SkipDefaultLibCheck = ToBoolean(value); break;
            case var _ when name == "sourceMap"u8: SourceMap = ToBoolean(value); break;
            case var _ when name == "sourceRoot"u8: SourceRoot = text; break;
            case var _ when name == "suppressOutputPathCheck"u8: SuppressOutputPathCheck = ToBoolean(value); break;
            case var _ when name == "target"u8: Target = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberTarget) ? (ScriptTarget)numberTarget : text switch { { } option when option == "es5"u8 => (ScriptTarget)1, { } option when option == "es6"u8 => (ScriptTarget)2, { } option when option == "es2015"u8 => (ScriptTarget)2, { } option when option == "es2016"u8 => (ScriptTarget)3, { } option when option == "es2017"u8 => (ScriptTarget)4, { } option when option == "es2018"u8 => (ScriptTarget)5, { } option when option == "es2019"u8 => (ScriptTarget)6, { } option when option == "es2020"u8 => (ScriptTarget)7, { } option when option == "es2021"u8 => (ScriptTarget)8, { } option when option == "es2022"u8 => (ScriptTarget)9, { } option when option == "es2023"u8 => (ScriptTarget)10, { } option when option == "es2024"u8 => (ScriptTarget)11, { } option when option == "es2025"u8 => (ScriptTarget)12, { } option when option == "esnext"u8 => (ScriptTarget)99, _ => default }; break;
            case var _ when name == "traceResolution"u8: TraceResolution = ToBoolean(value); break;
            case var _ when name == "tsBuildInfoFile"u8: TsBuildInfoFile = text; break;
            case var _ when name == "typeRoots"u8: TypeRoots = ToStrings(value); break;
            case var _ when name == "types"u8: Types = ToStrings(value); break;
            case var _ when name == "useDefineForClassFields"u8: UseDefineForClassFields = ToBoolean(value); break;
            case var _ when name == "useUnknownInCatchVariables"u8: UseUnknownInCatchVariables = ToBoolean(value); break;
            case var _ when name == "verbatimModuleSyntax"u8: VerbatimModuleSyntax = ToBoolean(value); break;
            case var _ when name == "maxNodeModuleJsDepth"u8: MaxNodeModuleJsDepth = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberMaxNodeModuleJsDepth) ? numberMaxNodeModuleJsDepth : null; break;
            case var _ when name == "allowSyntheticDefaultImports"u8: AllowSyntheticDefaultImports = ToBoolean(value); break;
            case var _ when name == "alwaysStrict"u8: AlwaysStrict = ToBoolean(value); break;
            case var _ when name == "baseUrl"u8: BaseUrl = text; break;
            case var _ when name == "downlevelIteration"u8: DownlevelIteration = ToBoolean(value); break;
            case var _ when name == "esModuleInterop"u8: ESModuleInterop = ToBoolean(value); break;
            case var _ when name == "outFile"u8: OutFile = text; break;
            case var _ when name == "configFilePath"u8: ConfigFilePath = text; break;
            case var _ when name == "noDtsResolution"u8: NoDtsResolution = ToBoolean(value); break;
            case var _ when name == "pathsBasePath"u8: PathsBasePath = text; break;
            case var _ when name == "diagnostics"u8: Diagnostics = ToBoolean(value); break;
            case var _ when name == "extendedDiagnostics"u8: ExtendedDiagnostics = ToBoolean(value); break;
            case var _ when name == "generateCpuProfile"u8: GenerateCpuProfile = text; break;
            case var _ when name == "generateTrace"u8: GenerateTrace = text; break;
            case var _ when name == "listEmittedFiles"u8: ListEmittedFiles = ToBoolean(value); break;
            case var _ when name == "listFiles"u8: ListFiles = ToBoolean(value); break;
            case var _ when name == "explainFiles"u8: ExplainFiles = ToBoolean(value); break;
            case var _ when name == "listFilesOnly"u8: ListFilesOnly = ToBoolean(value); break;
            case var _ when name == "noEmitForJsFiles"u8: NoEmitForJsFiles = ToBoolean(value); break;
            case var _ when name == "preserveWatchOutput"u8: PreserveWatchOutput = ToBoolean(value); break;
            case var _ when name == "pretty"u8: Pretty = ToBoolean(value); break;
            case var _ when name == "version"u8: Version = ToBoolean(value); break;
            case var _ when name == "watch"u8: Watch = ToBoolean(value); break;
            case var _ when name == "showConfig"u8: ShowConfig = ToBoolean(value); break;
            case var _ when name == "build"u8: Build = ToBoolean(value); break;
            case var _ when name == "help"u8: Help = ToBoolean(value); break;
            case var _ when name == "all"u8: All = ToBoolean(value); break;
            case var _ when name == "runExternalCode"u8: RunExternalCode = ToBoolean(value); break;
            case var _ when name == "pprofDir"u8: PprofDir = text; break;
            case var _ when name == "singleThreaded"u8: SingleThreaded = ToBoolean(value); break;
            case var _ when name == "quiet"u8: Quiet = ToBoolean(value); break;
            case var _ when name == "checkers"u8: Checkers = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberCheckers) ? numberCheckers : null; break;
            case var _ when name == "plugins"u8: Plugins = ToObjects(value); break;
        }
    }

    private static bool? ToBoolean(JsonElement value) => value.ValueKind switch
    {
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        _ => null
    };

    private static Utf8String[]? ToStrings(JsonElement value) => value.ValueKind == JsonValueKind.Array
        ? value.EnumerateArray().Where(item => item.ValueKind == JsonValueKind.String).Select(JsonStrings.GetString).ToArray() : null;

    private static JsonElement[]? ToObjects(JsonElement value) => value.ValueKind == JsonValueKind.Array
        ? value.EnumerateArray().Where(item => item.ValueKind == JsonValueKind.Object).ToArray() : null;

    internal static IReadOnlyList<KeyValuePair<Utf8String, Utf8String[]>>? ParsePaths(JsonElement value)
    {
        if (value.ValueKind != JsonValueKind.Object) return null;
        var paths = new List<KeyValuePair<Utf8String, Utf8String[]>>();
        foreach (var property in value.EnumerateObject())
        {
            Utf8String name = JsonStrings.GetName(property);
            int index = paths.FindIndex(entry => entry.Key == name);
            var entry = new KeyValuePair<Utf8String, Utf8String[]>(name, ToStrings(property.Value) ?? []);
            if (index >= 0) paths[index] = entry; else paths.Add(entry);
        }
        return paths;
    }
}
