// <auto-generated />
#nullable enable
using System.Text.Json;
using TypeScript.Compiler.Text;
namespace TypeScript.Compiler.Configuration;

public enum ModuleDetectionKind
{
    None = 0,
    Auto = 1,
    Legacy = 2,
    Force = 3,
}

public enum ModuleKind
{
    None = 0,
    CommonJS = 1,
    AMD = 2,
    UMD = 3,
    System = 4,
    ES2015 = 5,
    ES2020 = 6,
    ES2022 = 7,
    ESNext = 99,
    Node16 = 100,
    Node18 = 101,
    Node20 = 102,
    NodeNext = 199,
    Preserve = 200,
}

public enum ModuleResolutionKind
{
    Unknown = 0,
    Classic = 1,
    Node10 = 2,
    Node16 = 3,
    NodeNext = 99,
    Bundler = 100,
}

public enum NewLineKind
{
    None = 0,
    CRLF = 1,
    LF = 2,
}

public enum ScriptTarget
{
    None = 0,
    ES5 = 1,
    ES2015 = 2,
    ES2016 = 3,
    ES2017 = 4,
    ES2018 = 5,
    ES2019 = 6,
    ES2020 = 7,
    ES2021 = 8,
    ES2022 = 9,
    ES2023 = 10,
    ES2024 = 11,
    ES2025 = 12,
    ESNext = 99,
    JSON = 100,
}

public enum JsxEmit
{
    None = 0,
    Preserve = 1,
    React = 2,
    ReactNative = 3,
    ReactJSX = 4,
    ReactJSXDev = 5,
}

public sealed partial class CompilerOptions
{
    public bool? AllowJs { get; private set; }
    public bool? AllowArbitraryExtensions { get; private set; }
    public bool? AllowImportingTsExtensions { get; private set; }
    public bool? AllowNonTsExtensions { get; private set; }
    public bool? AllowUmdGlobalAccess { get; private set; }
    public bool? AllowUnreachableCode { get; private set; }
    public bool? AllowUnusedLabels { get; private set; }
    public bool? AssumeChangesOnlyAffectDirectDependencies { get; private set; }
    public bool? CheckJs { get; private set; }
    public string[]? CustomConditions { get; private set; }
    public bool? Composite { get; private set; }
    public bool? EmitDeclarationOnly { get; private set; }
    public bool? EmitBOM { get; private set; }
    public bool? EmitDecoratorMetadata { get; private set; }
    public bool? Declaration { get; private set; }
    public string? DeclarationDir { get; private set; }
    public bool? DeclarationMap { get; private set; }
    public bool? DeduplicatePackages { get; private set; }
    public bool? DisableSizeLimit { get; private set; }
    public bool? DisableSourceOfProjectReferenceRedirect { get; private set; }
    public bool? DisableSolutionSearching { get; private set; }
    public bool? DisableReferencedProjectLoad { get; private set; }
    public bool? ErasableSyntaxOnly { get; private set; }
    public bool? ExactOptionalPropertyTypes { get; private set; }
    public bool? ExperimentalDecorators { get; private set; }
    public bool? ForceConsistentCasingInFileNames { get; private set; }
    public bool? IsolatedModules { get; private set; }
    public bool? IsolatedDeclarations { get; private set; }
    public bool? IgnoreConfig { get; private set; }
    public string? IgnoreDeprecations { get; private set; }
    public bool? ImportHelpers { get; private set; }
    public bool? InlineSourceMap { get; private set; }
    public bool? InlineSources { get; private set; }
    public bool? Init { get; private set; }
    public bool? Incremental { get; private set; }
    public JsxEmit Jsx { get; private set; }
    public string? JsxFactory { get; private set; }
    public string? JsxFragmentFactory { get; private set; }
    public string? JsxImportSource { get; private set; }
    public string[]? Lib { get; private set; }
    public bool? LibReplacement { get; private set; }
    public string? Locale { get; private set; }
    public string? MapRoot { get; private set; }
    public ModuleKind Module { get; private set; }
    public ModuleResolutionKind ModuleResolution { get; private set; }
    public string[]? ModuleSuffixes { get; private set; }
    public ModuleDetectionKind ModuleDetection { get; private set; }
    public NewLineKind NewLine { get; private set; }
    public bool? NoEmit { get; private set; }
    public bool? NoCheck { get; private set; }
    public bool? NoErrorTruncation { get; private set; }
    public bool? NoFallthroughCasesInSwitch { get; private set; }
    public bool? NoImplicitAny { get; private set; }
    public bool? NoImplicitThis { get; private set; }
    public bool? NoImplicitReturns { get; private set; }
    public bool? NoEmitHelpers { get; private set; }
    public bool? NoLib { get; private set; }
    public bool? NoPropertyAccessFromIndexSignature { get; private set; }
    public bool? NoUncheckedIndexedAccess { get; private set; }
    public bool? NoEmitOnError { get; private set; }
    public bool? NoUnusedLocals { get; private set; }
    public bool? NoUnusedParameters { get; private set; }
    public bool? NoResolve { get; private set; }
    public bool? NoImplicitOverride { get; private set; }
    public bool? NoUncheckedSideEffectImports { get; private set; }
    public string? OutDir { get; private set; }
    public IReadOnlyList<KeyValuePair<string, string[]>>? Paths { get; private set; }
    public bool? PreserveConstEnums { get; private set; }
    public bool? PreserveSymlinks { get; private set; }
    public string? Project { get; private set; }
    public bool? ResolveJsonModule { get; private set; }
    public bool? ResolvePackageJsonExports { get; private set; }
    public bool? ResolvePackageJsonImports { get; private set; }
    public bool? RemoveComments { get; private set; }
    public bool? RewriteRelativeImportExtensions { get; private set; }
    public string? ReactNamespace { get; private set; }
    public string? RootDir { get; private set; }
    public string[]? RootDirs { get; private set; }
    public bool? SkipLibCheck { get; private set; }
    public bool? StableTypeOrdering { get; private set; }
    public bool? Strict { get; private set; }
    public bool? StrictBindCallApply { get; private set; }
    public bool? StrictBuiltinIteratorReturn { get; private set; }
    public bool? StrictFunctionTypes { get; private set; }
    public bool? StrictNullChecks { get; private set; }
    public bool? StrictPropertyInitialization { get; private set; }
    public bool? StripInternal { get; private set; }
    public bool? SkipDefaultLibCheck { get; private set; }
    public bool? SourceMap { get; private set; }
    public string? SourceRoot { get; private set; }
    public bool? SuppressOutputPathCheck { get; private set; }
    public ScriptTarget Target { get; private set; }
    public bool? TraceResolution { get; private set; }
    public string? TsBuildInfoFile { get; private set; }
    public string[]? TypeRoots { get; private set; }
    public string[]? Types { get; private set; }
    public bool? UseDefineForClassFields { get; private set; }
    public bool? UseUnknownInCatchVariables { get; private set; }
    public bool? VerbatimModuleSyntax { get; private set; }
    public int? MaxNodeModuleJsDepth { get; private set; }
    public bool? AllowSyntheticDefaultImports { get; private set; }
    public bool? AlwaysStrict { get; private set; }
    public string? BaseUrl { get; private set; }
    public bool? DownlevelIteration { get; private set; }
    public bool? ESModuleInterop { get; private set; }
    public string? OutFile { get; private set; }
    public string? ConfigFilePath { get; private set; }
    public bool? NoDtsResolution { get; private set; }
    public string? PathsBasePath { get; private set; }
    public bool? Diagnostics { get; private set; }
    public bool? ExtendedDiagnostics { get; private set; }
    public string? GenerateCpuProfile { get; private set; }
    public string? GenerateTrace { get; private set; }
    public bool? ListEmittedFiles { get; private set; }
    public bool? ListFiles { get; private set; }
    public bool? ExplainFiles { get; private set; }
    public bool? ListFilesOnly { get; private set; }
    public bool? NoEmitForJsFiles { get; private set; }
    public bool? PreserveWatchOutput { get; private set; }
    public bool? Pretty { get; private set; }
    public bool? Version { get; private set; }
    public bool? Watch { get; private set; }
    public bool? ShowConfig { get; private set; }
    public bool? Build { get; private set; }
    public bool? Help { get; private set; }
    public bool? All { get; private set; }
    public bool? RunExternalCode { get; private set; }
    public string? PprofDir { get; private set; }
    public bool? SingleThreaded { get; private set; }
    public bool? Quiet { get; private set; }
    public int? Checkers { get; private set; }
    public JsonElement[]? Plugins { get; private set; }

    private void AssignTyped(string name, JsonElement value, string? text)
    {
        switch (name)
        {
            case "allowJs": AllowJs = ToBoolean(value); break;
            case "allowArbitraryExtensions": AllowArbitraryExtensions = ToBoolean(value); break;
            case "allowImportingTsExtensions": AllowImportingTsExtensions = ToBoolean(value); break;
            case "allowNonTsExtensions": AllowNonTsExtensions = ToBoolean(value); break;
            case "allowUmdGlobalAccess": AllowUmdGlobalAccess = ToBoolean(value); break;
            case "allowUnreachableCode": AllowUnreachableCode = ToBoolean(value); break;
            case "allowUnusedLabels": AllowUnusedLabels = ToBoolean(value); break;
            case "assumeChangesOnlyAffectDirectDependencies": AssumeChangesOnlyAffectDirectDependencies = ToBoolean(value); break;
            case "checkJs": CheckJs = ToBoolean(value); break;
            case "customConditions": CustomConditions = ToStrings(value); break;
            case "composite": Composite = ToBoolean(value); break;
            case "emitDeclarationOnly": EmitDeclarationOnly = ToBoolean(value); break;
            case "emitBOM": EmitBOM = ToBoolean(value); break;
            case "emitDecoratorMetadata": EmitDecoratorMetadata = ToBoolean(value); break;
            case "declaration": Declaration = ToBoolean(value); break;
            case "declarationDir": DeclarationDir = text; break;
            case "declarationMap": DeclarationMap = ToBoolean(value); break;
            case "deduplicatePackages": DeduplicatePackages = ToBoolean(value); break;
            case "disableSizeLimit": DisableSizeLimit = ToBoolean(value); break;
            case "disableSourceOfProjectReferenceRedirect": DisableSourceOfProjectReferenceRedirect = ToBoolean(value); break;
            case "disableSolutionSearching": DisableSolutionSearching = ToBoolean(value); break;
            case "disableReferencedProjectLoad": DisableReferencedProjectLoad = ToBoolean(value); break;
            case "erasableSyntaxOnly": ErasableSyntaxOnly = ToBoolean(value); break;
            case "exactOptionalPropertyTypes": ExactOptionalPropertyTypes = ToBoolean(value); break;
            case "experimentalDecorators": ExperimentalDecorators = ToBoolean(value); break;
            case "forceConsistentCasingInFileNames": ForceConsistentCasingInFileNames = ToBoolean(value); break;
            case "isolatedModules": IsolatedModules = ToBoolean(value); break;
            case "isolatedDeclarations": IsolatedDeclarations = ToBoolean(value); break;
            case "ignoreConfig": IgnoreConfig = ToBoolean(value); break;
            case "ignoreDeprecations": IgnoreDeprecations = text; break;
            case "importHelpers": ImportHelpers = ToBoolean(value); break;
            case "inlineSourceMap": InlineSourceMap = ToBoolean(value); break;
            case "inlineSources": InlineSources = ToBoolean(value); break;
            case "init": Init = ToBoolean(value); break;
            case "incremental": Incremental = ToBoolean(value); break;
            case "jsx": Jsx = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberJsx) ? (JsxEmit)numberJsx : text switch { "preserve" => (JsxEmit)1, "react-native" => (JsxEmit)3, "react-jsx" => (JsxEmit)4, "react-jsxdev" => (JsxEmit)5, "react" => (JsxEmit)2, _ => default }; break;
            case "jsxFactory": JsxFactory = text; break;
            case "jsxFragmentFactory": JsxFragmentFactory = text; break;
            case "jsxImportSource": JsxImportSource = text; break;
            case "lib": Lib = ToStrings(value); break;
            case "libReplacement": LibReplacement = ToBoolean(value); break;
            case "locale": Locale = text; break;
            case "mapRoot": MapRoot = text; break;
            case "module": Module = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModule) ? (ModuleKind)numberModule : text switch { "commonjs" => (ModuleKind)1, "amd" => (ModuleKind)2, "system" => (ModuleKind)4, "umd" => (ModuleKind)3, "es6" => (ModuleKind)5, "es2015" => (ModuleKind)5, "es2020" => (ModuleKind)6, "es2022" => (ModuleKind)7, "esnext" => (ModuleKind)99, "node16" => (ModuleKind)100, "node18" => (ModuleKind)101, "node20" => (ModuleKind)102, "nodenext" => (ModuleKind)199, "preserve" => (ModuleKind)200, _ => default }; break;
            case "moduleResolution": ModuleResolution = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModuleResolution) ? (ModuleResolutionKind)numberModuleResolution : text switch { "node16" => (ModuleResolutionKind)3, "nodenext" => (ModuleResolutionKind)99, "bundler" => (ModuleResolutionKind)100, "classic" => (ModuleResolutionKind)1, "node" => (ModuleResolutionKind)2, "node10" => (ModuleResolutionKind)2, _ => default }; break;
            case "moduleSuffixes": ModuleSuffixes = ToStrings(value); break;
            case "moduleDetection": ModuleDetection = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberModuleDetection) ? (ModuleDetectionKind)numberModuleDetection : text switch { "auto" => (ModuleDetectionKind)1, "legacy" => (ModuleDetectionKind)2, "force" => (ModuleDetectionKind)3, _ => default }; break;
            case "newLine": NewLine = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberNewLine) ? (NewLineKind)numberNewLine : text switch { "crlf" => (NewLineKind)1, "lf" => (NewLineKind)2, _ => default }; break;
            case "noEmit": NoEmit = ToBoolean(value); break;
            case "noCheck": NoCheck = ToBoolean(value); break;
            case "noErrorTruncation": NoErrorTruncation = ToBoolean(value); break;
            case "noFallthroughCasesInSwitch": NoFallthroughCasesInSwitch = ToBoolean(value); break;
            case "noImplicitAny": NoImplicitAny = ToBoolean(value); break;
            case "noImplicitThis": NoImplicitThis = ToBoolean(value); break;
            case "noImplicitReturns": NoImplicitReturns = ToBoolean(value); break;
            case "noEmitHelpers": NoEmitHelpers = ToBoolean(value); break;
            case "noLib": NoLib = ToBoolean(value); break;
            case "noPropertyAccessFromIndexSignature": NoPropertyAccessFromIndexSignature = ToBoolean(value); break;
            case "noUncheckedIndexedAccess": NoUncheckedIndexedAccess = ToBoolean(value); break;
            case "noEmitOnError": NoEmitOnError = ToBoolean(value); break;
            case "noUnusedLocals": NoUnusedLocals = ToBoolean(value); break;
            case "noUnusedParameters": NoUnusedParameters = ToBoolean(value); break;
            case "noResolve": NoResolve = ToBoolean(value); break;
            case "noImplicitOverride": NoImplicitOverride = ToBoolean(value); break;
            case "noUncheckedSideEffectImports": NoUncheckedSideEffectImports = ToBoolean(value); break;
            case "outDir": OutDir = text; break;
            case "paths": Paths = ParsePaths(value); break;
            case "preserveConstEnums": PreserveConstEnums = ToBoolean(value); break;
            case "preserveSymlinks": PreserveSymlinks = ToBoolean(value); break;
            case "project": Project = text; break;
            case "resolveJsonModule": ResolveJsonModule = ToBoolean(value); break;
            case "resolvePackageJsonExports": ResolvePackageJsonExports = ToBoolean(value); break;
            case "resolvePackageJsonImports": ResolvePackageJsonImports = ToBoolean(value); break;
            case "removeComments": RemoveComments = ToBoolean(value); break;
            case "rewriteRelativeImportExtensions": RewriteRelativeImportExtensions = ToBoolean(value); break;
            case "reactNamespace": ReactNamespace = text; break;
            case "rootDir": RootDir = text; break;
            case "rootDirs": RootDirs = ToStrings(value); break;
            case "skipLibCheck": SkipLibCheck = ToBoolean(value); break;
            case "stableTypeOrdering": StableTypeOrdering = ToBoolean(value); break;
            case "strict": Strict = ToBoolean(value); break;
            case "strictBindCallApply": StrictBindCallApply = ToBoolean(value); break;
            case "strictBuiltinIteratorReturn": StrictBuiltinIteratorReturn = ToBoolean(value); break;
            case "strictFunctionTypes": StrictFunctionTypes = ToBoolean(value); break;
            case "strictNullChecks": StrictNullChecks = ToBoolean(value); break;
            case "strictPropertyInitialization": StrictPropertyInitialization = ToBoolean(value); break;
            case "stripInternal": StripInternal = ToBoolean(value); break;
            case "skipDefaultLibCheck": SkipDefaultLibCheck = ToBoolean(value); break;
            case "sourceMap": SourceMap = ToBoolean(value); break;
            case "sourceRoot": SourceRoot = text; break;
            case "suppressOutputPathCheck": SuppressOutputPathCheck = ToBoolean(value); break;
            case "target": Target = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberTarget) ? (ScriptTarget)numberTarget : text switch { "es5" => (ScriptTarget)1, "es6" => (ScriptTarget)2, "es2015" => (ScriptTarget)2, "es2016" => (ScriptTarget)3, "es2017" => (ScriptTarget)4, "es2018" => (ScriptTarget)5, "es2019" => (ScriptTarget)6, "es2020" => (ScriptTarget)7, "es2021" => (ScriptTarget)8, "es2022" => (ScriptTarget)9, "es2023" => (ScriptTarget)10, "es2024" => (ScriptTarget)11, "es2025" => (ScriptTarget)12, "esnext" => (ScriptTarget)99, _ => default }; break;
            case "traceResolution": TraceResolution = ToBoolean(value); break;
            case "tsBuildInfoFile": TsBuildInfoFile = text; break;
            case "typeRoots": TypeRoots = ToStrings(value); break;
            case "types": Types = ToStrings(value); break;
            case "useDefineForClassFields": UseDefineForClassFields = ToBoolean(value); break;
            case "useUnknownInCatchVariables": UseUnknownInCatchVariables = ToBoolean(value); break;
            case "verbatimModuleSyntax": VerbatimModuleSyntax = ToBoolean(value); break;
            case "maxNodeModuleJsDepth": MaxNodeModuleJsDepth = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberMaxNodeModuleJsDepth) ? numberMaxNodeModuleJsDepth : null; break;
            case "allowSyntheticDefaultImports": AllowSyntheticDefaultImports = ToBoolean(value); break;
            case "alwaysStrict": AlwaysStrict = ToBoolean(value); break;
            case "baseUrl": BaseUrl = text; break;
            case "downlevelIteration": DownlevelIteration = ToBoolean(value); break;
            case "esModuleInterop": ESModuleInterop = ToBoolean(value); break;
            case "outFile": OutFile = text; break;
            case "configFilePath": ConfigFilePath = text; break;
            case "noDtsResolution": NoDtsResolution = ToBoolean(value); break;
            case "pathsBasePath": PathsBasePath = text; break;
            case "diagnostics": Diagnostics = ToBoolean(value); break;
            case "extendedDiagnostics": ExtendedDiagnostics = ToBoolean(value); break;
            case "generateCpuProfile": GenerateCpuProfile = text; break;
            case "generateTrace": GenerateTrace = text; break;
            case "listEmittedFiles": ListEmittedFiles = ToBoolean(value); break;
            case "listFiles": ListFiles = ToBoolean(value); break;
            case "explainFiles": ExplainFiles = ToBoolean(value); break;
            case "listFilesOnly": ListFilesOnly = ToBoolean(value); break;
            case "noEmitForJsFiles": NoEmitForJsFiles = ToBoolean(value); break;
            case "preserveWatchOutput": PreserveWatchOutput = ToBoolean(value); break;
            case "pretty": Pretty = ToBoolean(value); break;
            case "version": Version = ToBoolean(value); break;
            case "watch": Watch = ToBoolean(value); break;
            case "showConfig": ShowConfig = ToBoolean(value); break;
            case "build": Build = ToBoolean(value); break;
            case "help": Help = ToBoolean(value); break;
            case "all": All = ToBoolean(value); break;
            case "runExternalCode": RunExternalCode = ToBoolean(value); break;
            case "pprofDir": PprofDir = text; break;
            case "singleThreaded": SingleThreaded = ToBoolean(value); break;
            case "quiet": Quiet = ToBoolean(value); break;
            case "checkers": Checkers = value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out int numberCheckers) ? numberCheckers : null; break;
            case "plugins": Plugins = ToObjects(value); break;
        }
    }

    private static bool? ToBoolean(JsonElement value) => value.ValueKind switch
    {
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        _ => null
    };

    private static string[]? ToStrings(JsonElement value) => value.ValueKind == JsonValueKind.Array
        ? value.EnumerateArray().Where(item => item.ValueKind == JsonValueKind.String).Select(JsonStrings.GetString).ToArray() : null;

    private static JsonElement[]? ToObjects(JsonElement value) => value.ValueKind == JsonValueKind.Array
        ? value.EnumerateArray().Where(item => item.ValueKind == JsonValueKind.Object).ToArray() : null;

    internal static IReadOnlyList<KeyValuePair<string, string[]>>? ParsePaths(JsonElement value)
    {
        if (value.ValueKind != JsonValueKind.Object) return null;
        var paths = new List<KeyValuePair<string, string[]>>();
        foreach (var property in value.EnumerateObject())
        {
            string name = JsonStrings.GetName(property);
            int index = paths.FindIndex(entry => entry.Key == name);
            var entry = new KeyValuePair<string, string[]>(name, ToStrings(property.Value) ?? []);
            if (index >= 0) paths[index] = entry; else paths.Add(entry);
        }
        return paths;
    }
}
