// Code generated by csharp/tools/generate-binding.mjs; DO NOT EDIT.
// ast.json SHA256 9ab3dfc6a2ff155ec1e315c6fee3deba8fe77c74256761ed38f475296a569574; development probe only.
package ast

import (
	"encoding/base64"
	"encoding/json"

	"github.com/microsoft/TypeScript/tsc/internal/core"
)

type CSharpSyntaxNode struct {
	Type             string
	Kind             Kind
	Flags            NodeFlags
	Pos, End, Parent int
	Fields           map[string]json.RawMessage
}
type CSharpSyntaxTree struct {
	Nodes                 []CSharpSyntaxNode
	External, ParseErrors int
}
type csharpSyntaxList struct {
	Pos, End int
	Nodes    []int
}

func csharpDecode[T any](raw json.RawMessage) (value T) {
	if err := json.Unmarshal(raw, &value); err != nil {
		panic(err)
	}
	return
}

func csharpString(raw json.RawMessage) string {
	bytes, err := base64.StdEncoding.DecodeString(csharpDecode[string](raw))
	if err != nil {
		panic(err)
	}
	return string(bytes)
}

func CSharpLoadSyntax(root *SourceFile, tree CSharpSyntaxTree) []*Node {
	nodes := make([]*Node, len(tree.Nodes)+1)
	for i, row := range tree.Nodes {
		switch row.Type {
		case "SourceFile":
			nodes[i+1] = root.AsNode()
		case "Token":
			nodes[i+1] = newNode(row.Kind, &Token{}, NodeFactoryHooks{})
		case "Identifier":
			nodes[i+1] = newNode(row.Kind, &Identifier{}, NodeFactoryHooks{})
		case "PrivateIdentifier":
			nodes[i+1] = newNode(row.Kind, &PrivateIdentifier{}, NodeFactoryHooks{})
		case "QualifiedName":
			nodes[i+1] = newNode(row.Kind, &QualifiedName{}, NodeFactoryHooks{})
		case "ComputedPropertyName":
			nodes[i+1] = newNode(row.Kind, &ComputedPropertyName{}, NodeFactoryHooks{})
		case "Decorator":
			nodes[i+1] = newNode(row.Kind, &Decorator{}, NodeFactoryHooks{})
		case "EmptyStatement":
			nodes[i+1] = newNode(row.Kind, &EmptyStatement{}, NodeFactoryHooks{})
		case "IfStatement":
			nodes[i+1] = newNode(row.Kind, &IfStatement{}, NodeFactoryHooks{})
		case "DoStatement":
			nodes[i+1] = newNode(row.Kind, &DoStatement{}, NodeFactoryHooks{})
		case "WhileStatement":
			nodes[i+1] = newNode(row.Kind, &WhileStatement{}, NodeFactoryHooks{})
		case "ForStatement":
			nodes[i+1] = newNode(row.Kind, &ForStatement{}, NodeFactoryHooks{})
		case "ForInOrOfStatement":
			nodes[i+1] = newNode(row.Kind, &ForInOrOfStatement{}, NodeFactoryHooks{})
		case "BreakStatement":
			nodes[i+1] = newNode(row.Kind, &BreakStatement{}, NodeFactoryHooks{})
		case "ContinueStatement":
			nodes[i+1] = newNode(row.Kind, &ContinueStatement{}, NodeFactoryHooks{})
		case "ReturnStatement":
			nodes[i+1] = newNode(row.Kind, &ReturnStatement{}, NodeFactoryHooks{})
		case "WithStatement":
			nodes[i+1] = newNode(row.Kind, &WithStatement{}, NodeFactoryHooks{})
		case "SwitchStatement":
			nodes[i+1] = newNode(row.Kind, &SwitchStatement{}, NodeFactoryHooks{})
		case "CaseBlock":
			nodes[i+1] = newNode(row.Kind, &CaseBlock{}, NodeFactoryHooks{})
		case "CaseOrDefaultClause":
			nodes[i+1] = newNode(row.Kind, &CaseOrDefaultClause{}, NodeFactoryHooks{})
		case "ThrowStatement":
			nodes[i+1] = newNode(row.Kind, &ThrowStatement{}, NodeFactoryHooks{})
		case "TryStatement":
			nodes[i+1] = newNode(row.Kind, &TryStatement{}, NodeFactoryHooks{})
		case "CatchClause":
			nodes[i+1] = newNode(row.Kind, &CatchClause{}, NodeFactoryHooks{})
		case "DebuggerStatement":
			nodes[i+1] = newNode(row.Kind, &DebuggerStatement{}, NodeFactoryHooks{})
		case "LabeledStatement":
			nodes[i+1] = newNode(row.Kind, &LabeledStatement{}, NodeFactoryHooks{})
		case "ExpressionStatement":
			nodes[i+1] = newNode(row.Kind, &ExpressionStatement{}, NodeFactoryHooks{})
		case "Block":
			nodes[i+1] = newNode(row.Kind, &Block{}, NodeFactoryHooks{})
		case "VariableStatement":
			nodes[i+1] = newNode(row.Kind, &VariableStatement{}, NodeFactoryHooks{})
		case "VariableDeclaration":
			nodes[i+1] = newNode(row.Kind, &VariableDeclaration{}, NodeFactoryHooks{})
		case "VariableDeclarationList":
			nodes[i+1] = newNode(row.Kind, &VariableDeclarationList{}, NodeFactoryHooks{})
		case "BindingPattern":
			nodes[i+1] = newNode(row.Kind, &BindingPattern{}, NodeFactoryHooks{})
		case "ParameterDeclaration":
			nodes[i+1] = newNode(row.Kind, &ParameterDeclaration{}, NodeFactoryHooks{})
		case "BindingElement":
			nodes[i+1] = newNode(row.Kind, &BindingElement{}, NodeFactoryHooks{})
		case "MissingDeclaration":
			nodes[i+1] = newNode(row.Kind, &MissingDeclaration{}, NodeFactoryHooks{})
		case "FunctionDeclaration":
			nodes[i+1] = newNode(row.Kind, &FunctionDeclaration{}, NodeFactoryHooks{})
		case "ClassDeclaration":
			nodes[i+1] = newNode(row.Kind, &ClassDeclaration{}, NodeFactoryHooks{})
		case "ClassExpression":
			nodes[i+1] = newNode(row.Kind, &ClassExpression{}, NodeFactoryHooks{})
		case "HeritageClause":
			nodes[i+1] = newNode(row.Kind, &HeritageClause{}, NodeFactoryHooks{})
		case "InterfaceDeclaration":
			nodes[i+1] = newNode(row.Kind, &InterfaceDeclaration{}, NodeFactoryHooks{})
		case "TypeAliasDeclaration":
			nodes[i+1] = newNode(row.Kind, &TypeAliasDeclaration{}, NodeFactoryHooks{})
		case "EnumMember":
			nodes[i+1] = newNode(row.Kind, &EnumMember{}, NodeFactoryHooks{})
		case "EnumDeclaration":
			nodes[i+1] = newNode(row.Kind, &EnumDeclaration{}, NodeFactoryHooks{})
		case "ModuleBlock":
			nodes[i+1] = newNode(row.Kind, &ModuleBlock{}, NodeFactoryHooks{})
		case "NotEmittedStatement":
			nodes[i+1] = newNode(row.Kind, &NotEmittedStatement{}, NodeFactoryHooks{})
		case "NotEmittedTypeElement":
			nodes[i+1] = newNode(row.Kind, &NotEmittedTypeElement{}, NodeFactoryHooks{})
		case "ImportDeclaration":
			nodes[i+1] = newNode(row.Kind, &ImportDeclaration{}, NodeFactoryHooks{})
		case "ExternalModuleReference":
			nodes[i+1] = newNode(row.Kind, &ExternalModuleReference{}, NodeFactoryHooks{})
		case "NamespaceImport":
			nodes[i+1] = newNode(row.Kind, &NamespaceImport{}, NodeFactoryHooks{})
		case "NamedImports":
			nodes[i+1] = newNode(row.Kind, &NamedImports{}, NodeFactoryHooks{})
		case "ExportAssignment":
			nodes[i+1] = newNode(row.Kind, &ExportAssignment{}, NodeFactoryHooks{})
		case "NamespaceExportDeclaration":
			nodes[i+1] = newNode(row.Kind, &NamespaceExportDeclaration{}, NodeFactoryHooks{})
		case "NamespaceExport":
			nodes[i+1] = newNode(row.Kind, &NamespaceExport{}, NodeFactoryHooks{})
		case "NamedExports":
			nodes[i+1] = newNode(row.Kind, &NamedExports{}, NodeFactoryHooks{})
		case "ExportSpecifier":
			nodes[i+1] = newNode(row.Kind, &ExportSpecifier{}, NodeFactoryHooks{})
		case "CallSignatureDeclaration":
			nodes[i+1] = newNode(row.Kind, &CallSignatureDeclaration{}, NodeFactoryHooks{})
		case "ConstructSignatureDeclaration":
			nodes[i+1] = newNode(row.Kind, &ConstructSignatureDeclaration{}, NodeFactoryHooks{})
		case "ConstructorDeclaration":
			nodes[i+1] = newNode(row.Kind, &ConstructorDeclaration{}, NodeFactoryHooks{})
		case "GetAccessorDeclaration":
			nodes[i+1] = newNode(row.Kind, &GetAccessorDeclaration{}, NodeFactoryHooks{})
		case "SetAccessorDeclaration":
			nodes[i+1] = newNode(row.Kind, &SetAccessorDeclaration{}, NodeFactoryHooks{})
		case "IndexSignatureDeclaration":
			nodes[i+1] = newNode(row.Kind, &IndexSignatureDeclaration{}, NodeFactoryHooks{})
		case "MethodSignatureDeclaration":
			nodes[i+1] = newNode(row.Kind, &MethodSignatureDeclaration{}, NodeFactoryHooks{})
		case "MethodDeclaration":
			nodes[i+1] = newNode(row.Kind, &MethodDeclaration{}, NodeFactoryHooks{})
		case "PropertySignatureDeclaration":
			nodes[i+1] = newNode(row.Kind, &PropertySignatureDeclaration{}, NodeFactoryHooks{})
		case "PropertyDeclaration":
			nodes[i+1] = newNode(row.Kind, &PropertyDeclaration{}, NodeFactoryHooks{})
		case "SemicolonClassElement":
			nodes[i+1] = newNode(row.Kind, &SemicolonClassElement{}, NodeFactoryHooks{})
		case "ClassStaticBlockDeclaration":
			nodes[i+1] = newNode(row.Kind, &ClassStaticBlockDeclaration{}, NodeFactoryHooks{})
		case "OmittedExpression":
			nodes[i+1] = newNode(row.Kind, &OmittedExpression{}, NodeFactoryHooks{})
		case "KeywordExpression":
			nodes[i+1] = newNode(row.Kind, &KeywordExpression{}, NodeFactoryHooks{})
		case "StringLiteral":
			nodes[i+1] = newNode(row.Kind, &StringLiteral{}, NodeFactoryHooks{})
		case "NumericLiteral":
			nodes[i+1] = newNode(row.Kind, &NumericLiteral{}, NodeFactoryHooks{})
		case "BigIntLiteral":
			nodes[i+1] = newNode(row.Kind, &BigIntLiteral{}, NodeFactoryHooks{})
		case "RegularExpressionLiteral":
			nodes[i+1] = newNode(row.Kind, &RegularExpressionLiteral{}, NodeFactoryHooks{})
		case "NoSubstitutionTemplateLiteral":
			nodes[i+1] = newNode(row.Kind, &NoSubstitutionTemplateLiteral{}, NodeFactoryHooks{})
		case "BinaryExpression":
			nodes[i+1] = newNode(row.Kind, &BinaryExpression{}, NodeFactoryHooks{})
		case "PrefixUnaryExpression":
			nodes[i+1] = newNode(row.Kind, &PrefixUnaryExpression{}, NodeFactoryHooks{})
		case "PostfixUnaryExpression":
			nodes[i+1] = newNode(row.Kind, &PostfixUnaryExpression{}, NodeFactoryHooks{})
		case "YieldExpression":
			nodes[i+1] = newNode(row.Kind, &YieldExpression{}, NodeFactoryHooks{})
		case "ArrowFunction":
			nodes[i+1] = newNode(row.Kind, &ArrowFunction{}, NodeFactoryHooks{})
		case "FunctionExpression":
			nodes[i+1] = newNode(row.Kind, &FunctionExpression{}, NodeFactoryHooks{})
		case "AsExpression":
			nodes[i+1] = newNode(row.Kind, &AsExpression{}, NodeFactoryHooks{})
		case "SatisfiesExpression":
			nodes[i+1] = newNode(row.Kind, &SatisfiesExpression{}, NodeFactoryHooks{})
		case "ConditionalExpression":
			nodes[i+1] = newNode(row.Kind, &ConditionalExpression{}, NodeFactoryHooks{})
		case "PropertyAccessExpression":
			nodes[i+1] = newNode(row.Kind, &PropertyAccessExpression{}, NodeFactoryHooks{})
		case "ElementAccessExpression":
			nodes[i+1] = newNode(row.Kind, &ElementAccessExpression{}, NodeFactoryHooks{})
		case "CallExpression":
			nodes[i+1] = newNode(row.Kind, &CallExpression{}, NodeFactoryHooks{})
		case "NewExpression":
			nodes[i+1] = newNode(row.Kind, &NewExpression{}, NodeFactoryHooks{})
		case "MetaProperty":
			nodes[i+1] = newNode(row.Kind, &MetaProperty{}, NodeFactoryHooks{})
		case "NonNullExpression":
			nodes[i+1] = newNode(row.Kind, &NonNullExpression{}, NodeFactoryHooks{})
		case "SpreadElement":
			nodes[i+1] = newNode(row.Kind, &SpreadElement{}, NodeFactoryHooks{})
		case "TemplateExpression":
			nodes[i+1] = newNode(row.Kind, &TemplateExpression{}, NodeFactoryHooks{})
		case "TemplateSpan":
			nodes[i+1] = newNode(row.Kind, &TemplateSpan{}, NodeFactoryHooks{})
		case "TaggedTemplateExpression":
			nodes[i+1] = newNode(row.Kind, &TaggedTemplateExpression{}, NodeFactoryHooks{})
		case "ParenthesizedExpression":
			nodes[i+1] = newNode(row.Kind, &ParenthesizedExpression{}, NodeFactoryHooks{})
		case "ArrayLiteralExpression":
			nodes[i+1] = newNode(row.Kind, &ArrayLiteralExpression{}, NodeFactoryHooks{})
		case "ObjectLiteralExpression":
			nodes[i+1] = newNode(row.Kind, &ObjectLiteralExpression{}, NodeFactoryHooks{})
		case "SpreadAssignment":
			nodes[i+1] = newNode(row.Kind, &SpreadAssignment{}, NodeFactoryHooks{})
		case "PropertyAssignment":
			nodes[i+1] = newNode(row.Kind, &PropertyAssignment{}, NodeFactoryHooks{})
		case "ShorthandPropertyAssignment":
			nodes[i+1] = newNode(row.Kind, &ShorthandPropertyAssignment{}, NodeFactoryHooks{})
		case "DeleteExpression":
			nodes[i+1] = newNode(row.Kind, &DeleteExpression{}, NodeFactoryHooks{})
		case "TypeOfExpression":
			nodes[i+1] = newNode(row.Kind, &TypeOfExpression{}, NodeFactoryHooks{})
		case "VoidExpression":
			nodes[i+1] = newNode(row.Kind, &VoidExpression{}, NodeFactoryHooks{})
		case "AwaitExpression":
			nodes[i+1] = newNode(row.Kind, &AwaitExpression{}, NodeFactoryHooks{})
		case "TypeAssertion":
			nodes[i+1] = newNode(row.Kind, &TypeAssertion{}, NodeFactoryHooks{})
		case "KeywordTypeNode":
			nodes[i+1] = newNode(row.Kind, &KeywordTypeNode{}, NodeFactoryHooks{})
		case "UnionTypeNode":
			nodes[i+1] = newNode(row.Kind, &UnionTypeNode{}, NodeFactoryHooks{})
		case "IntersectionTypeNode":
			nodes[i+1] = newNode(row.Kind, &IntersectionTypeNode{}, NodeFactoryHooks{})
		case "ConditionalTypeNode":
			nodes[i+1] = newNode(row.Kind, &ConditionalTypeNode{}, NodeFactoryHooks{})
		case "TypeOperatorNode":
			nodes[i+1] = newNode(row.Kind, &TypeOperatorNode{}, NodeFactoryHooks{})
		case "InferTypeNode":
			nodes[i+1] = newNode(row.Kind, &InferTypeNode{}, NodeFactoryHooks{})
		case "ArrayTypeNode":
			nodes[i+1] = newNode(row.Kind, &ArrayTypeNode{}, NodeFactoryHooks{})
		case "IndexedAccessTypeNode":
			nodes[i+1] = newNode(row.Kind, &IndexedAccessTypeNode{}, NodeFactoryHooks{})
		case "TypeReferenceNode":
			nodes[i+1] = newNode(row.Kind, &TypeReferenceNode{}, NodeFactoryHooks{})
		case "ExpressionWithTypeArguments":
			nodes[i+1] = newNode(row.Kind, &ExpressionWithTypeArguments{}, NodeFactoryHooks{})
		case "LiteralTypeNode":
			nodes[i+1] = newNode(row.Kind, &LiteralTypeNode{}, NodeFactoryHooks{})
		case "ThisTypeNode":
			nodes[i+1] = newNode(row.Kind, &ThisTypeNode{}, NodeFactoryHooks{})
		case "TypePredicateNode":
			nodes[i+1] = newNode(row.Kind, &TypePredicateNode{}, NodeFactoryHooks{})
		case "ImportAttribute":
			nodes[i+1] = newNode(row.Kind, &ImportAttribute{}, NodeFactoryHooks{})
		case "ImportAttributes":
			nodes[i+1] = newNode(row.Kind, &ImportAttributes{}, NodeFactoryHooks{})
		case "TypeQueryNode":
			nodes[i+1] = newNode(row.Kind, &TypeQueryNode{}, NodeFactoryHooks{})
		case "MappedTypeNode":
			nodes[i+1] = newNode(row.Kind, &MappedTypeNode{}, NodeFactoryHooks{})
		case "TypeLiteralNode":
			nodes[i+1] = newNode(row.Kind, &TypeLiteralNode{}, NodeFactoryHooks{})
		case "TupleTypeNode":
			nodes[i+1] = newNode(row.Kind, &TupleTypeNode{}, NodeFactoryHooks{})
		case "NamedTupleMember":
			nodes[i+1] = newNode(row.Kind, &NamedTupleMember{}, NodeFactoryHooks{})
		case "OptionalTypeNode":
			nodes[i+1] = newNode(row.Kind, &OptionalTypeNode{}, NodeFactoryHooks{})
		case "RestTypeNode":
			nodes[i+1] = newNode(row.Kind, &RestTypeNode{}, NodeFactoryHooks{})
		case "ParenthesizedTypeNode":
			nodes[i+1] = newNode(row.Kind, &ParenthesizedTypeNode{}, NodeFactoryHooks{})
		case "FunctionTypeNode":
			nodes[i+1] = newNode(row.Kind, &FunctionTypeNode{}, NodeFactoryHooks{})
		case "ConstructorTypeNode":
			nodes[i+1] = newNode(row.Kind, &ConstructorTypeNode{}, NodeFactoryHooks{})
		case "TemplateHead":
			nodes[i+1] = newNode(row.Kind, &TemplateHead{}, NodeFactoryHooks{})
		case "TemplateMiddle":
			nodes[i+1] = newNode(row.Kind, &TemplateMiddle{}, NodeFactoryHooks{})
		case "TemplateTail":
			nodes[i+1] = newNode(row.Kind, &TemplateTail{}, NodeFactoryHooks{})
		case "TemplateLiteralTypeNode":
			nodes[i+1] = newNode(row.Kind, &TemplateLiteralTypeNode{}, NodeFactoryHooks{})
		case "TemplateLiteralTypeSpan":
			nodes[i+1] = newNode(row.Kind, &TemplateLiteralTypeSpan{}, NodeFactoryHooks{})
		case "SyntheticExpression":
			nodes[i+1] = newNode(row.Kind, &SyntheticExpression{}, NodeFactoryHooks{})
		case "PartiallyEmittedExpression":
			nodes[i+1] = newNode(row.Kind, &PartiallyEmittedExpression{}, NodeFactoryHooks{})
		case "JsxElement":
			nodes[i+1] = newNode(row.Kind, &JsxElement{}, NodeFactoryHooks{})
		case "JsxAttributes":
			nodes[i+1] = newNode(row.Kind, &JsxAttributes{}, NodeFactoryHooks{})
		case "JsxNamespacedName":
			nodes[i+1] = newNode(row.Kind, &JsxNamespacedName{}, NodeFactoryHooks{})
		case "JsxOpeningElement":
			nodes[i+1] = newNode(row.Kind, &JsxOpeningElement{}, NodeFactoryHooks{})
		case "JsxSelfClosingElement":
			nodes[i+1] = newNode(row.Kind, &JsxSelfClosingElement{}, NodeFactoryHooks{})
		case "JsxFragment":
			nodes[i+1] = newNode(row.Kind, &JsxFragment{}, NodeFactoryHooks{})
		case "JsxOpeningFragment":
			nodes[i+1] = newNode(row.Kind, &JsxOpeningFragment{}, NodeFactoryHooks{})
		case "JsxClosingFragment":
			nodes[i+1] = newNode(row.Kind, &JsxClosingFragment{}, NodeFactoryHooks{})
		case "JsxAttribute":
			nodes[i+1] = newNode(row.Kind, &JsxAttribute{}, NodeFactoryHooks{})
		case "JsxSpreadAttribute":
			nodes[i+1] = newNode(row.Kind, &JsxSpreadAttribute{}, NodeFactoryHooks{})
		case "JsxClosingElement":
			nodes[i+1] = newNode(row.Kind, &JsxClosingElement{}, NodeFactoryHooks{})
		case "JsxExpression":
			nodes[i+1] = newNode(row.Kind, &JsxExpression{}, NodeFactoryHooks{})
		case "JsxText":
			nodes[i+1] = newNode(row.Kind, &JsxText{}, NodeFactoryHooks{})
		case "SyntaxList":
			nodes[i+1] = newNode(row.Kind, &SyntaxList{}, NodeFactoryHooks{})
		case "JSDoc":
			nodes[i+1] = newNode(row.Kind, &JSDoc{}, NodeFactoryHooks{})
		case "JSDocTypeExpression":
			nodes[i+1] = newNode(row.Kind, &JSDocTypeExpression{}, NodeFactoryHooks{})
		case "JSDocNonNullableType":
			nodes[i+1] = newNode(row.Kind, &JSDocNonNullableType{}, NodeFactoryHooks{})
		case "JSDocNullableType":
			nodes[i+1] = newNode(row.Kind, &JSDocNullableType{}, NodeFactoryHooks{})
		case "JSDocAllType":
			nodes[i+1] = newNode(row.Kind, &JSDocAllType{}, NodeFactoryHooks{})
		case "JSDocVariadicType":
			nodes[i+1] = newNode(row.Kind, &JSDocVariadicType{}, NodeFactoryHooks{})
		case "JSDocOptionalType":
			nodes[i+1] = newNode(row.Kind, &JSDocOptionalType{}, NodeFactoryHooks{})
		case "JSDocTypeTag":
			nodes[i+1] = newNode(row.Kind, &JSDocTypeTag{}, NodeFactoryHooks{})
		case "JSDocUnknownTag":
			nodes[i+1] = newNode(row.Kind, &JSDocUnknownTag{}, NodeFactoryHooks{})
		case "JSDocTemplateTag":
			nodes[i+1] = newNode(row.Kind, &JSDocTemplateTag{}, NodeFactoryHooks{})
		case "JSDocReturnTag":
			nodes[i+1] = newNode(row.Kind, &JSDocReturnTag{}, NodeFactoryHooks{})
		case "JSDocPublicTag":
			nodes[i+1] = newNode(row.Kind, &JSDocPublicTag{}, NodeFactoryHooks{})
		case "JSDocPrivateTag":
			nodes[i+1] = newNode(row.Kind, &JSDocPrivateTag{}, NodeFactoryHooks{})
		case "JSDocProtectedTag":
			nodes[i+1] = newNode(row.Kind, &JSDocProtectedTag{}, NodeFactoryHooks{})
		case "JSDocReadonlyTag":
			nodes[i+1] = newNode(row.Kind, &JSDocReadonlyTag{}, NodeFactoryHooks{})
		case "JSDocOverrideTag":
			nodes[i+1] = newNode(row.Kind, &JSDocOverrideTag{}, NodeFactoryHooks{})
		case "JSDocDeprecatedTag":
			nodes[i+1] = newNode(row.Kind, &JSDocDeprecatedTag{}, NodeFactoryHooks{})
		case "JSDocSeeTag":
			nodes[i+1] = newNode(row.Kind, &JSDocSeeTag{}, NodeFactoryHooks{})
		case "JSDocImplementsTag":
			nodes[i+1] = newNode(row.Kind, &JSDocImplementsTag{}, NodeFactoryHooks{})
		case "JSDocAugmentsTag":
			nodes[i+1] = newNode(row.Kind, &JSDocAugmentsTag{}, NodeFactoryHooks{})
		case "JSDocSatisfiesTag":
			nodes[i+1] = newNode(row.Kind, &JSDocSatisfiesTag{}, NodeFactoryHooks{})
		case "JSDocThrowsTag":
			nodes[i+1] = newNode(row.Kind, &JSDocThrowsTag{}, NodeFactoryHooks{})
		case "JSDocThisTag":
			nodes[i+1] = newNode(row.Kind, &JSDocThisTag{}, NodeFactoryHooks{})
		case "JSDocImportTag":
			nodes[i+1] = newNode(row.Kind, &JSDocImportTag{}, NodeFactoryHooks{})
		case "JSDocCallbackTag":
			nodes[i+1] = newNode(row.Kind, &JSDocCallbackTag{}, NodeFactoryHooks{})
		case "JSDocOverloadTag":
			nodes[i+1] = newNode(row.Kind, &JSDocOverloadTag{}, NodeFactoryHooks{})
		case "JSDocTypedefTag":
			nodes[i+1] = newNode(row.Kind, &JSDocTypedefTag{}, NodeFactoryHooks{})
		case "JSDocSignature":
			nodes[i+1] = newNode(row.Kind, &JSDocSignature{}, NodeFactoryHooks{})
		case "JSDocNameReference":
			nodes[i+1] = newNode(row.Kind, &JSDocNameReference{}, NodeFactoryHooks{})
		case "ModuleDeclaration":
			nodes[i+1] = newNode(row.Kind, &ModuleDeclaration{}, NodeFactoryHooks{})
		case "ImportEqualsDeclaration":
			nodes[i+1] = newNode(row.Kind, &ImportEqualsDeclaration{}, NodeFactoryHooks{})
		case "ExportDeclaration":
			nodes[i+1] = newNode(row.Kind, &ExportDeclaration{}, NodeFactoryHooks{})
		case "ImportTypeNode":
			nodes[i+1] = newNode(row.Kind, &ImportTypeNode{}, NodeFactoryHooks{})
		case "ImportClause":
			nodes[i+1] = newNode(row.Kind, &ImportClause{}, NodeFactoryHooks{})
		case "ImportSpecifier":
			nodes[i+1] = newNode(row.Kind, &ImportSpecifier{}, NodeFactoryHooks{})
		case "JSDocText":
			nodes[i+1] = newNode(row.Kind, &JSDocText{}, NodeFactoryHooks{})
		case "JSDocLink":
			nodes[i+1] = newNode(row.Kind, &JSDocLink{}, NodeFactoryHooks{})
		case "JSDocLinkPlain":
			nodes[i+1] = newNode(row.Kind, &JSDocLinkPlain{}, NodeFactoryHooks{})
		case "JSDocLinkCode":
			nodes[i+1] = newNode(row.Kind, &JSDocLinkCode{}, NodeFactoryHooks{})
		case "TypeParameterDeclaration":
			nodes[i+1] = newNode(row.Kind, &TypeParameterDeclaration{}, NodeFactoryHooks{})
		case "SyntheticReferenceExpression":
			nodes[i+1] = newNode(row.Kind, &SyntheticReferenceExpression{}, NodeFactoryHooks{})
		case "JSDocTypeLiteral":
			nodes[i+1] = newNode(row.Kind, &JSDocTypeLiteral{}, NodeFactoryHooks{})
		case "JSDocParameterOrPropertyTag":
			nodes[i+1] = newNode(row.Kind, &JSDocParameterOrPropertyTag{}, NodeFactoryHooks{})
		default:
			panic("Unknown syntax type " + row.Type)
		}
	}
	node := func(raw json.RawMessage) *Node { return nodes[csharpDecode[int](raw)] }
	list := func(raw json.RawMessage) *NodeList {
		if string(raw) == "null" {
			return nil
		}
		value := csharpDecode[csharpSyntaxList](raw)
		items := make([]*Node, len(value.Nodes))
		for i, id := range value.Nodes {
			items[i] = nodes[id]
		}
		return &NodeList{Loc: core.NewTextRange(value.Pos, value.End), Nodes: items}
	}
	modifiers := func(raw json.RawMessage) *ModifierList {
		l := list(raw)
		if l == nil {
			return nil
		}
		return &ModifierList{NodeList: *l, ModifierFlags: ModifiersToFlags(l.Nodes)}
	}
	for i, row := range tree.Nodes {
		current := nodes[i+1]
		current.Flags = row.Flags
		current.Loc = core.NewTextRange(row.Pos, row.End)
		current.Parent = nodes[row.Parent]
		switch row.Type {
		case "Identifier":
			n := current.AsIdentifier()
			n.Text = csharpString(row.Fields["Text"])
		case "PrivateIdentifier":
			n := current.AsPrivateIdentifier()
			n.Text = csharpString(row.Fields["Text"])
		case "QualifiedName":
			n := current.AsQualifiedName()
			n.Left = node(row.Fields["Left"])
			n.Right = node(row.Fields["Right"])
		case "ComputedPropertyName":
			n := current.AsComputedPropertyName()
			n.Expression = node(row.Fields["Expression"])
		case "Decorator":
			n := current.AsDecorator()
			n.Expression = node(row.Fields["Expression"])
		case "IfStatement":
			n := current.AsIfStatement()
			n.Expression = node(row.Fields["Expression"])
			n.ThenStatement = node(row.Fields["ThenStatement"])
			n.ElseStatement = node(row.Fields["ElseStatement"])
		case "DoStatement":
			n := current.AsDoStatement()
			n.Statement = node(row.Fields["Statement"])
			n.Expression = node(row.Fields["Expression"])
		case "WhileStatement":
			n := current.AsWhileStatement()
			n.Expression = node(row.Fields["Expression"])
			n.Statement = node(row.Fields["Statement"])
		case "ForStatement":
			n := current.AsForStatement()
			n.Initializer = node(row.Fields["Initializer"])
			n.Condition = node(row.Fields["Condition"])
			n.Incrementor = node(row.Fields["Incrementor"])
			n.Statement = node(row.Fields["Statement"])
		case "ForInOrOfStatement":
			n := current.AsForInOrOfStatement()
			n.AwaitModifier = node(row.Fields["AwaitModifier"])
			n.Initializer = node(row.Fields["Initializer"])
			n.Expression = node(row.Fields["Expression"])
			n.Statement = node(row.Fields["Statement"])
		case "BreakStatement":
			n := current.AsBreakStatement()
			n.Label = node(row.Fields["Label"])
		case "ContinueStatement":
			n := current.AsContinueStatement()
			n.Label = node(row.Fields["Label"])
		case "ReturnStatement":
			n := current.AsReturnStatement()
			n.Expression = node(row.Fields["Expression"])
		case "WithStatement":
			n := current.AsWithStatement()
			n.Expression = node(row.Fields["Expression"])
			n.Statement = node(row.Fields["Statement"])
		case "SwitchStatement":
			n := current.AsSwitchStatement()
			n.Expression = node(row.Fields["Expression"])
			n.CaseBlock = node(row.Fields["CaseBlock"])
		case "CaseBlock":
			n := current.AsCaseBlock()
			n.Clauses = list(row.Fields["Clauses"])
		case "CaseOrDefaultClause":
			n := current.AsCaseOrDefaultClause()
			n.Expression = node(row.Fields["Expression"])
			n.Statements = list(row.Fields["Statements"])
		case "ThrowStatement":
			n := current.AsThrowStatement()
			n.Expression = node(row.Fields["Expression"])
		case "TryStatement":
			n := current.AsTryStatement()
			n.TryBlock = node(row.Fields["TryBlock"])
			n.CatchClause = node(row.Fields["CatchClause"])
			n.FinallyBlock = node(row.Fields["FinallyBlock"])
		case "CatchClause":
			n := current.AsCatchClause()
			n.VariableDeclaration = node(row.Fields["VariableDeclaration"])
			n.Block = node(row.Fields["Block"])
		case "LabeledStatement":
			n := current.AsLabeledStatement()
			n.Label = node(row.Fields["Label"])
			n.Statement = node(row.Fields["Statement"])
		case "ExpressionStatement":
			n := current.AsExpressionStatement()
			n.Expression = node(row.Fields["Expression"])
		case "Block":
			n := current.AsBlock()
			n.Statements = list(row.Fields["Statements"])
			n.MultiLine = csharpDecode[bool](row.Fields["MultiLine"])
		case "VariableStatement":
			n := current.AsVariableStatement()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.DeclarationList = node(row.Fields["DeclarationList"])
		case "VariableDeclaration":
			n := current.AsVariableDeclaration()
			n.name = node(row.Fields["Name"])
			n.ExclamationToken = node(row.Fields["ExclamationToken"])
			n.Type = node(row.Fields["Type"])
			n.Initializer = node(row.Fields["Initializer"])
		case "VariableDeclarationList":
			n := current.AsVariableDeclarationList()
			n.Declarations = list(row.Fields["Declarations"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "BindingPattern":
			n := current.AsBindingPattern()
			n.Elements = list(row.Fields["Elements"])
		case "ParameterDeclaration":
			n := current.AsParameterDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.DotDotDotToken = node(row.Fields["DotDotDotToken"])
			n.name = node(row.Fields["Name"])
			n.QuestionToken = node(row.Fields["QuestionToken"])
			n.Type = node(row.Fields["Type"])
			n.Initializer = node(row.Fields["Initializer"])
		case "BindingElement":
			n := current.AsBindingElement()
			n.DotDotDotToken = node(row.Fields["DotDotDotToken"])
			n.PropertyName = node(row.Fields["PropertyName"])
			n.name = node(row.Fields["Name"])
			n.Initializer = node(row.Fields["Initializer"])
		case "MissingDeclaration":
			n := current.AsMissingDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
		case "FunctionDeclaration":
			n := current.AsFunctionDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.AsteriskToken = node(row.Fields["AsteriskToken"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "ClassDeclaration":
			n := current.AsClassDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.HeritageClauses = list(row.Fields["HeritageClauses"])
			n.Members = list(row.Fields["Members"])
		case "ClassExpression":
			n := current.AsClassExpression()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.HeritageClauses = list(row.Fields["HeritageClauses"])
			n.Members = list(row.Fields["Members"])
		case "HeritageClause":
			n := current.AsHeritageClause()
			n.Token = csharpDecode[Kind](row.Fields["Token"])
			n.Types = list(row.Fields["Types"])
		case "InterfaceDeclaration":
			n := current.AsInterfaceDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.HeritageClauses = list(row.Fields["HeritageClauses"])
			n.Members = list(row.Fields["Members"])
		case "TypeAliasDeclaration":
			n := current.AsTypeAliasDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Type = node(row.Fields["Type"])
		case "EnumMember":
			n := current.AsEnumMember()
			n.name = node(row.Fields["Name"])
			n.Initializer = node(row.Fields["Initializer"])
		case "EnumDeclaration":
			n := current.AsEnumDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.Members = list(row.Fields["Members"])
		case "ModuleBlock":
			n := current.AsModuleBlock()
			n.Statements = list(row.Fields["Statements"])
		case "ImportDeclaration":
			n := current.AsImportDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.ImportClause = node(row.Fields["ImportClause"])
			n.ModuleSpecifier = node(row.Fields["ModuleSpecifier"])
			n.Attributes = node(row.Fields["Attributes"])
		case "ExternalModuleReference":
			n := current.AsExternalModuleReference()
			n.Expression = node(row.Fields["Expression"])
		case "NamespaceImport":
			n := current.AsNamespaceImport()
			n.name = node(row.Fields["Name"])
		case "NamedImports":
			n := current.AsNamedImports()
			n.Elements = list(row.Fields["Elements"])
		case "ExportAssignment":
			n := current.AsExportAssignment()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.IsExportEquals = csharpDecode[bool](row.Fields["IsExportEquals"])
			n.Type = node(row.Fields["Type"])
			n.Expression = node(row.Fields["Expression"])
		case "NamespaceExportDeclaration":
			n := current.AsNamespaceExportDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
		case "NamespaceExport":
			n := current.AsNamespaceExport()
			n.name = node(row.Fields["Name"])
		case "NamedExports":
			n := current.AsNamedExports()
			n.Elements = list(row.Fields["Elements"])
		case "ExportSpecifier":
			n := current.AsExportSpecifier()
			n.IsTypeOnly = csharpDecode[bool](row.Fields["IsTypeOnly"])
			n.PropertyName = node(row.Fields["PropertyName"])
			n.name = node(row.Fields["Name"])
		case "CallSignatureDeclaration":
			n := current.AsCallSignatureDeclaration()
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "ConstructSignatureDeclaration":
			n := current.AsConstructSignatureDeclaration()
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "ConstructorDeclaration":
			n := current.AsConstructorDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "GetAccessorDeclaration":
			n := current.AsGetAccessorDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "SetAccessorDeclaration":
			n := current.AsSetAccessorDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "IndexSignatureDeclaration":
			n := current.AsIndexSignatureDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "MethodSignatureDeclaration":
			n := current.AsMethodSignatureDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "MethodDeclaration":
			n := current.AsMethodDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.AsteriskToken = node(row.Fields["AsteriskToken"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "PropertySignatureDeclaration":
			n := current.AsPropertySignatureDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.Type = node(row.Fields["Type"])
			n.Initializer = node(row.Fields["Initializer"])
		case "PropertyDeclaration":
			n := current.AsPropertyDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.Type = node(row.Fields["Type"])
			n.Initializer = node(row.Fields["Initializer"])
		case "ClassStaticBlockDeclaration":
			n := current.AsClassStaticBlockDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.Body = node(row.Fields["Body"])
		case "StringLiteral":
			n := current.AsStringLiteral()
			n.Text = csharpString(row.Fields["Text"])
			n.TokenFlags = csharpDecode[TokenFlags](row.Fields["TokenFlags"])
		case "NumericLiteral":
			n := current.AsNumericLiteral()
			n.Text = csharpString(row.Fields["Text"])
			n.TokenFlags = csharpDecode[TokenFlags](row.Fields["TokenFlags"])
		case "BigIntLiteral":
			n := current.AsBigIntLiteral()
			n.Text = csharpString(row.Fields["Text"])
			n.TokenFlags = csharpDecode[TokenFlags](row.Fields["TokenFlags"])
		case "RegularExpressionLiteral":
			n := current.AsRegularExpressionLiteral()
			n.Text = csharpString(row.Fields["Text"])
			n.TokenFlags = csharpDecode[TokenFlags](row.Fields["TokenFlags"])
		case "NoSubstitutionTemplateLiteral":
			n := current.AsNoSubstitutionTemplateLiteral()
			n.Text = csharpString(row.Fields["Text"])
			n.TemplateFlags = csharpDecode[TokenFlags](row.Fields["TemplateFlags"])
		case "BinaryExpression":
			n := current.AsBinaryExpression()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.Left = node(row.Fields["Left"])
			n.Type = node(row.Fields["Type"])
			n.OperatorToken = node(row.Fields["OperatorToken"])
			n.Right = node(row.Fields["Right"])
		case "PrefixUnaryExpression":
			n := current.AsPrefixUnaryExpression()
			n.Operator = csharpDecode[Kind](row.Fields["Operator"])
			n.Operand = node(row.Fields["Operand"])
		case "PostfixUnaryExpression":
			n := current.AsPostfixUnaryExpression()
			n.Operand = node(row.Fields["Operand"])
			n.Operator = csharpDecode[Kind](row.Fields["Operator"])
		case "YieldExpression":
			n := current.AsYieldExpression()
			n.AsteriskToken = node(row.Fields["AsteriskToken"])
			n.Expression = node(row.Fields["Expression"])
		case "ArrowFunction":
			n := current.AsArrowFunction()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.EqualsGreaterThanToken = node(row.Fields["EqualsGreaterThanToken"])
			n.Body = node(row.Fields["Body"])
		case "FunctionExpression":
			n := current.AsFunctionExpression()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.AsteriskToken = node(row.Fields["AsteriskToken"])
			n.name = node(row.Fields["Name"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
			n.FullSignature = node(row.Fields["FullSignature"])
			n.Body = node(row.Fields["Body"])
		case "AsExpression":
			n := current.AsAsExpression()
			n.Expression = node(row.Fields["Expression"])
			n.Type = node(row.Fields["Type"])
		case "SatisfiesExpression":
			n := current.AsSatisfiesExpression()
			n.Expression = node(row.Fields["Expression"])
			n.Type = node(row.Fields["Type"])
		case "ConditionalExpression":
			n := current.AsConditionalExpression()
			n.Condition = node(row.Fields["Condition"])
			n.QuestionToken = node(row.Fields["QuestionToken"])
			n.WhenTrue = node(row.Fields["WhenTrue"])
			n.ColonToken = node(row.Fields["ColonToken"])
			n.WhenFalse = node(row.Fields["WhenFalse"])
		case "PropertyAccessExpression":
			n := current.AsPropertyAccessExpression()
			n.Expression = node(row.Fields["Expression"])
			n.QuestionDotToken = node(row.Fields["QuestionDotToken"])
			n.name = node(row.Fields["Name"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "ElementAccessExpression":
			n := current.AsElementAccessExpression()
			n.Expression = node(row.Fields["Expression"])
			n.QuestionDotToken = node(row.Fields["QuestionDotToken"])
			n.ArgumentExpression = node(row.Fields["ArgumentExpression"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "CallExpression":
			n := current.AsCallExpression()
			n.Expression = node(row.Fields["Expression"])
			n.QuestionDotToken = node(row.Fields["QuestionDotToken"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
			n.Arguments = list(row.Fields["Arguments"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "NewExpression":
			n := current.AsNewExpression()
			n.Expression = node(row.Fields["Expression"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
			n.Arguments = list(row.Fields["Arguments"])
		case "MetaProperty":
			n := current.AsMetaProperty()
			n.KeywordToken = csharpDecode[Kind](row.Fields["KeywordToken"])
			n.name = node(row.Fields["Name"])
		case "NonNullExpression":
			n := current.AsNonNullExpression()
			n.Expression = node(row.Fields["Expression"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "SpreadElement":
			n := current.AsSpreadElement()
			n.Expression = node(row.Fields["Expression"])
		case "TemplateExpression":
			n := current.AsTemplateExpression()
			n.Head = node(row.Fields["Head"])
			n.TemplateSpans = list(row.Fields["TemplateSpans"])
		case "TemplateSpan":
			n := current.AsTemplateSpan()
			n.Expression = node(row.Fields["Expression"])
			n.Literal = node(row.Fields["Literal"])
		case "TaggedTemplateExpression":
			n := current.AsTaggedTemplateExpression()
			n.Tag = node(row.Fields["Tag"])
			n.QuestionDotToken = node(row.Fields["QuestionDotToken"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
			n.Template = node(row.Fields["Template"])
			n.Flags = csharpDecode[NodeFlags](row.Fields["Flags"])
		case "ParenthesizedExpression":
			n := current.AsParenthesizedExpression()
			n.Expression = node(row.Fields["Expression"])
		case "ArrayLiteralExpression":
			n := current.AsArrayLiteralExpression()
			n.Elements = list(row.Fields["Elements"])
			n.MultiLine = csharpDecode[bool](row.Fields["MultiLine"])
		case "ObjectLiteralExpression":
			n := current.AsObjectLiteralExpression()
			n.Properties = list(row.Fields["Properties"])
			n.MultiLine = csharpDecode[bool](row.Fields["MultiLine"])
		case "SpreadAssignment":
			n := current.AsSpreadAssignment()
			n.Expression = node(row.Fields["Expression"])
		case "PropertyAssignment":
			n := current.AsPropertyAssignment()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.Type = node(row.Fields["Type"])
			n.Initializer = node(row.Fields["Initializer"])
		case "ShorthandPropertyAssignment":
			n := current.AsShorthandPropertyAssignment()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.PostfixToken = node(row.Fields["PostfixToken"])
			n.Type = node(row.Fields["Type"])
			n.EqualsToken = node(row.Fields["EqualsToken"])
			n.ObjectAssignmentInitializer = node(row.Fields["ObjectAssignmentInitializer"])
		case "DeleteExpression":
			n := current.AsDeleteExpression()
			n.Expression = node(row.Fields["Expression"])
		case "TypeOfExpression":
			n := current.AsTypeOfExpression()
			n.Expression = node(row.Fields["Expression"])
		case "VoidExpression":
			n := current.AsVoidExpression()
			n.Expression = node(row.Fields["Expression"])
		case "AwaitExpression":
			n := current.AsAwaitExpression()
			n.Expression = node(row.Fields["Expression"])
		case "TypeAssertion":
			n := current.AsTypeAssertion()
			n.Type = node(row.Fields["Type"])
			n.Expression = node(row.Fields["Expression"])
		case "UnionTypeNode":
			n := current.AsUnionTypeNode()
			n.Types = list(row.Fields["Types"])
		case "IntersectionTypeNode":
			n := current.AsIntersectionTypeNode()
			n.Types = list(row.Fields["Types"])
		case "ConditionalTypeNode":
			n := current.AsConditionalTypeNode()
			n.CheckType = node(row.Fields["CheckType"])
			n.ExtendsType = node(row.Fields["ExtendsType"])
			n.TrueType = node(row.Fields["TrueType"])
			n.FalseType = node(row.Fields["FalseType"])
		case "TypeOperatorNode":
			n := current.AsTypeOperatorNode()
			n.Operator = csharpDecode[Kind](row.Fields["Operator"])
			n.Type = node(row.Fields["Type"])
		case "InferTypeNode":
			n := current.AsInferTypeNode()
			n.TypeParameter = node(row.Fields["TypeParameter"])
		case "ArrayTypeNode":
			n := current.AsArrayTypeNode()
			n.ElementType = node(row.Fields["ElementType"])
		case "IndexedAccessTypeNode":
			n := current.AsIndexedAccessTypeNode()
			n.ObjectType = node(row.Fields["ObjectType"])
			n.IndexType = node(row.Fields["IndexType"])
		case "TypeReferenceNode":
			n := current.AsTypeReferenceNode()
			n.TypeName = node(row.Fields["TypeName"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
		case "ExpressionWithTypeArguments":
			n := current.AsExpressionWithTypeArguments()
			n.Expression = node(row.Fields["Expression"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
		case "LiteralTypeNode":
			n := current.AsLiteralTypeNode()
			n.Literal = node(row.Fields["Literal"])
		case "TypePredicateNode":
			n := current.AsTypePredicateNode()
			n.AssertsModifier = node(row.Fields["AssertsModifier"])
			n.ParameterName = node(row.Fields["ParameterName"])
			n.Type = node(row.Fields["Type"])
		case "ImportAttribute":
			n := current.AsImportAttribute()
			n.name = node(row.Fields["Name"])
			n.Value = node(row.Fields["Value"])
		case "ImportAttributes":
			n := current.AsImportAttributes()
			n.Token = csharpDecode[Kind](row.Fields["Token"])
			n.Attributes = list(row.Fields["Attributes"])
			n.MultiLine = csharpDecode[bool](row.Fields["MultiLine"])
		case "TypeQueryNode":
			n := current.AsTypeQueryNode()
			n.ExprName = node(row.Fields["ExprName"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
		case "MappedTypeNode":
			n := current.AsMappedTypeNode()
			n.ReadonlyToken = node(row.Fields["ReadonlyToken"])
			n.TypeParameter = node(row.Fields["TypeParameter"])
			n.NameType = node(row.Fields["NameType"])
			n.QuestionToken = node(row.Fields["QuestionToken"])
			n.Type = node(row.Fields["Type"])
			n.Members = list(row.Fields["Members"])
		case "TypeLiteralNode":
			n := current.AsTypeLiteralNode()
			n.Members = list(row.Fields["Members"])
		case "TupleTypeNode":
			n := current.AsTupleTypeNode()
			n.Elements = list(row.Fields["Elements"])
		case "NamedTupleMember":
			n := current.AsNamedTupleMember()
			n.DotDotDotToken = node(row.Fields["DotDotDotToken"])
			n.name = node(row.Fields["Name"])
			n.QuestionToken = node(row.Fields["QuestionToken"])
			n.Type = node(row.Fields["Type"])
		case "OptionalTypeNode":
			n := current.AsOptionalTypeNode()
			n.Type = node(row.Fields["Type"])
		case "RestTypeNode":
			n := current.AsRestTypeNode()
			n.Type = node(row.Fields["Type"])
		case "ParenthesizedTypeNode":
			n := current.AsParenthesizedTypeNode()
			n.Type = node(row.Fields["Type"])
		case "FunctionTypeNode":
			n := current.AsFunctionTypeNode()
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "ConstructorTypeNode":
			n := current.AsConstructorTypeNode()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "TemplateHead":
			n := current.AsTemplateHead()
			n.Text = csharpString(row.Fields["Text"])
			n.RawText = csharpString(row.Fields["RawText"])
			n.TemplateFlags = csharpDecode[TokenFlags](row.Fields["TemplateFlags"])
		case "TemplateMiddle":
			n := current.AsTemplateMiddle()
			n.Text = csharpString(row.Fields["Text"])
			n.RawText = csharpString(row.Fields["RawText"])
			n.TemplateFlags = csharpDecode[TokenFlags](row.Fields["TemplateFlags"])
		case "TemplateTail":
			n := current.AsTemplateTail()
			n.Text = csharpString(row.Fields["Text"])
			n.RawText = csharpString(row.Fields["RawText"])
			n.TemplateFlags = csharpDecode[TokenFlags](row.Fields["TemplateFlags"])
		case "TemplateLiteralTypeNode":
			n := current.AsTemplateLiteralTypeNode()
			n.Head = node(row.Fields["Head"])
			n.TemplateSpans = list(row.Fields["TemplateSpans"])
		case "TemplateLiteralTypeSpan":
			n := current.AsTemplateLiteralTypeSpan()
			n.Type = node(row.Fields["Type"])
			n.Literal = node(row.Fields["Literal"])
		case "SyntheticExpression":
			n := current.AsSyntheticExpression()
			n.Type = nil
			n.IsSpread = csharpDecode[bool](row.Fields["IsSpread"])
			n.TupleNameSource = node(row.Fields["TupleNameSource"])
		case "PartiallyEmittedExpression":
			n := current.AsPartiallyEmittedExpression()
			n.Expression = node(row.Fields["Expression"])
		case "JsxElement":
			n := current.AsJsxElement()
			n.OpeningElement = node(row.Fields["OpeningElement"])
			n.Children = list(row.Fields["Children"])
			n.ClosingElement = node(row.Fields["ClosingElement"])
		case "JsxAttributes":
			n := current.AsJsxAttributes()
			n.Properties = list(row.Fields["Properties"])
		case "JsxNamespacedName":
			n := current.AsJsxNamespacedName()
			n.Namespace = node(row.Fields["Namespace"])
			n.name = node(row.Fields["Name"])
		case "JsxOpeningElement":
			n := current.AsJsxOpeningElement()
			n.TagName = node(row.Fields["TagName"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
			n.Attributes = node(row.Fields["Attributes"])
		case "JsxSelfClosingElement":
			n := current.AsJsxSelfClosingElement()
			n.TagName = node(row.Fields["TagName"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
			n.Attributes = node(row.Fields["Attributes"])
		case "JsxFragment":
			n := current.AsJsxFragment()
			n.OpeningFragment = node(row.Fields["OpeningFragment"])
			n.Children = list(row.Fields["Children"])
			n.ClosingFragment = node(row.Fields["ClosingFragment"])
		case "JsxAttribute":
			n := current.AsJsxAttribute()
			n.name = node(row.Fields["Name"])
			n.Initializer = node(row.Fields["Initializer"])
		case "JsxSpreadAttribute":
			n := current.AsJsxSpreadAttribute()
			n.Expression = node(row.Fields["Expression"])
		case "JsxClosingElement":
			n := current.AsJsxClosingElement()
			n.TagName = node(row.Fields["TagName"])
		case "JsxExpression":
			n := current.AsJsxExpression()
			n.DotDotDotToken = node(row.Fields["DotDotDotToken"])
			n.Expression = node(row.Fields["Expression"])
		case "JsxText":
			n := current.AsJsxText()
			n.Text = csharpString(row.Fields["Text"])
			n.ContainsOnlyTriviaWhiteSpaces = csharpDecode[bool](row.Fields["ContainsOnlyTriviaWhiteSpaces"])
		case "SyntaxList":
			n := current.AsSyntaxList()
			for _, id := range csharpDecode[[]int](row.Fields["Children"]) {
				n.Children = append(n.Children, nodes[id])
			}
		case "JSDoc":
			n := current.AsJSDoc()
			n.Comment = list(row.Fields["Comment"])
			n.Tags = list(row.Fields["Tags"])
		case "JSDocTypeExpression":
			n := current.AsJSDocTypeExpression()
			n.Type = node(row.Fields["Type"])
		case "JSDocNonNullableType":
			n := current.AsJSDocNonNullableType()
			n.Type = node(row.Fields["Type"])
		case "JSDocNullableType":
			n := current.AsJSDocNullableType()
			n.Type = node(row.Fields["Type"])
		case "JSDocVariadicType":
			n := current.AsJSDocVariadicType()
			n.Type = node(row.Fields["Type"])
		case "JSDocOptionalType":
			n := current.AsJSDocOptionalType()
			n.Type = node(row.Fields["Type"])
		case "JSDocTypeTag":
			n := current.AsJSDocTypeTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocUnknownTag":
			n := current.AsJSDocUnknownTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocTemplateTag":
			n := current.AsJSDocTemplateTag()
			n.TagName = node(row.Fields["TagName"])
			n.Constraint = node(row.Fields["Constraint"])
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocReturnTag":
			n := current.AsJSDocReturnTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocPublicTag":
			n := current.AsJSDocPublicTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocPrivateTag":
			n := current.AsJSDocPrivateTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocProtectedTag":
			n := current.AsJSDocProtectedTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocReadonlyTag":
			n := current.AsJSDocReadonlyTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocOverrideTag":
			n := current.AsJSDocOverrideTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocDeprecatedTag":
			n := current.AsJSDocDeprecatedTag()
			n.TagName = node(row.Fields["TagName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocSeeTag":
			n := current.AsJSDocSeeTag()
			n.TagName = node(row.Fields["TagName"])
			n.NameExpression = node(row.Fields["NameExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocImplementsTag":
			n := current.AsJSDocImplementsTag()
			n.TagName = node(row.Fields["TagName"])
			n.ClassName = node(row.Fields["ClassName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocAugmentsTag":
			n := current.AsJSDocAugmentsTag()
			n.TagName = node(row.Fields["TagName"])
			n.ClassName = node(row.Fields["ClassName"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocSatisfiesTag":
			n := current.AsJSDocSatisfiesTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocThrowsTag":
			n := current.AsJSDocThrowsTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocThisTag":
			n := current.AsJSDocThisTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocImportTag":
			n := current.AsJSDocImportTag()
			n.TagName = node(row.Fields["TagName"])
			n.ImportClause = node(row.Fields["ImportClause"])
			n.ModuleSpecifier = node(row.Fields["ModuleSpecifier"])
			n.Attributes = node(row.Fields["Attributes"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocCallbackTag":
			n := current.AsJSDocCallbackTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.name = node(row.Fields["Name"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocOverloadTag":
			n := current.AsJSDocOverloadTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocTypedefTag":
			n := current.AsJSDocTypedefTag()
			n.TagName = node(row.Fields["TagName"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.name = node(row.Fields["Name"])
			n.Comment = list(row.Fields["Comment"])
		case "JSDocSignature":
			n := current.AsJSDocSignature()
			n.TypeParameters = list(row.Fields["TypeParameters"])
			n.Parameters = list(row.Fields["Parameters"])
			n.Type = node(row.Fields["Type"])
		case "JSDocNameReference":
			n := current.AsJSDocNameReference()
			n.name = node(row.Fields["Name"])
		case "SourceFile":
			n := current.AsSourceFile()
			n.Statements = list(row.Fields["Statements"])
			n.EndOfFileToken = node(row.Fields["EndOfFileToken"])
		case "ModuleDeclaration":
			n := current.AsModuleDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.Keyword = csharpDecode[Kind](row.Fields["Keyword"])
			n.name = node(row.Fields["Name"])
			n.Attributes = node(row.Fields["Attributes"])
			n.Body = node(row.Fields["Body"])
		case "ImportEqualsDeclaration":
			n := current.AsImportEqualsDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.IsTypeOnly = csharpDecode[bool](row.Fields["IsTypeOnly"])
			n.name = node(row.Fields["Name"])
			n.ModuleReference = node(row.Fields["ModuleReference"])
		case "ExportDeclaration":
			n := current.AsExportDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.IsTypeOnly = csharpDecode[bool](row.Fields["IsTypeOnly"])
			n.ExportClause = node(row.Fields["ExportClause"])
			n.ModuleSpecifier = node(row.Fields["ModuleSpecifier"])
			n.Attributes = node(row.Fields["Attributes"])
		case "ImportTypeNode":
			n := current.AsImportTypeNode()
			n.IsTypeOf = csharpDecode[bool](row.Fields["IsTypeOf"])
			n.Argument = node(row.Fields["Argument"])
			n.Attributes = node(row.Fields["Attributes"])
			n.Qualifier = node(row.Fields["Qualifier"])
			n.TypeArguments = list(row.Fields["TypeArguments"])
		case "ImportClause":
			n := current.AsImportClause()
			n.PhaseModifier = csharpDecode[Kind](row.Fields["PhaseModifier"])
			n.name = node(row.Fields["Name"])
			n.NamedBindings = node(row.Fields["NamedBindings"])
		case "ImportSpecifier":
			n := current.AsImportSpecifier()
			n.IsTypeOnly = csharpDecode[bool](row.Fields["IsTypeOnly"])
			n.PropertyName = node(row.Fields["PropertyName"])
			n.name = node(row.Fields["Name"])
		case "JSDocText":
			n := current.AsJSDocText()
			for _, raw := range csharpDecode[[]json.RawMessage](row.Fields["Text"]) {
				n.text = append(n.text, csharpString(raw))
			}
		case "JSDocLink":
			n := current.AsJSDocLink()
			n.name = node(row.Fields["Name"])
			for _, raw := range csharpDecode[[]json.RawMessage](row.Fields["Text"]) {
				n.text = append(n.text, csharpString(raw))
			}
		case "JSDocLinkPlain":
			n := current.AsJSDocLinkPlain()
			n.name = node(row.Fields["Name"])
			for _, raw := range csharpDecode[[]json.RawMessage](row.Fields["Text"]) {
				n.text = append(n.text, csharpString(raw))
			}
		case "JSDocLinkCode":
			n := current.AsJSDocLinkCode()
			n.name = node(row.Fields["Name"])
			for _, raw := range csharpDecode[[]json.RawMessage](row.Fields["Text"]) {
				n.text = append(n.text, csharpString(raw))
			}
		case "TypeParameterDeclaration":
			n := current.AsTypeParameterDeclaration()
			n.modifiers = modifiers(row.Fields["Modifiers"])
			n.name = node(row.Fields["Name"])
			n.Constraint = node(row.Fields["Constraint"])
			n.Expression = node(row.Fields["Expression"])
			n.DefaultType = node(row.Fields["DefaultType"])
		case "SyntheticReferenceExpression":
			n := current.AsSyntheticReferenceExpression()
			n.Expression = node(row.Fields["Expression"])
			n.ThisArg = node(row.Fields["ThisArg"])
		case "JSDocTypeLiteral":
			n := current.AsJSDocTypeLiteral()
			for _, id := range csharpDecode[[]int](row.Fields["JSDocPropertyTags"]) {
				n.JSDocPropertyTags = append(n.JSDocPropertyTags, nodes[id])
			}
			n.IsArrayType = csharpDecode[bool](row.Fields["IsArrayType"])
		case "JSDocParameterOrPropertyTag":
			n := current.AsJSDocParameterOrPropertyTag()
			n.TagName = node(row.Fields["TagName"])
			n.name = node(row.Fields["Name"])
			n.IsBracketed = csharpDecode[bool](row.Fields["IsBracketed"])
			n.TypeExpression = node(row.Fields["TypeExpression"])
			n.IsNameFirst = csharpDecode[bool](row.Fields["IsNameFirst"])
			n.Comment = list(row.Fields["Comment"])
		}
	}
	root.ExternalModuleIndicator = nodes[tree.External]
	return nodes
}
