<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NuGetLockFilePath Condition="'$(PublishAot)' == 'true'">packages.aot.lock.json</NuGetLockFilePath>
    <OutputType>Exe</OutputType>
    <IlcGenerateMapFile>true</IlcGenerateMapFile>
    <EventSourceSupport>true</EventSourceSupport>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TypeScript.Compiler/TypeScript.Compiler.csproj" />
  </ItemGroup>
</Project>
