// Code generated by csharp/tools/generate-ast.mjs; DO NOT EDIT.
// ast.json SHA256 9ab3dfc6a2ff155ec1e315c6fee3deba8fe77c74256761ed38f475296a569574
// Development oracle instrumentation only; not part of the shipped compiler.
package ast

import "encoding/base64"

func CSharpScalarProperties(node *Node) map[string]any {
	result := map[string]any{}
	switch node.Kind {
	case KindIdentifier:
		n := node.AsIdentifier()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindPrivateIdentifier:
		n := node.AsPrivateIdentifier()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindBlock:
		n := node.AsBlock()
		result["MultiLine"] = n.MultiLine
	case KindHeritageClause:
		n := node.AsHeritageClause()
		result["Token"] = int(n.Token)
	case KindExportAssignment:
		n := node.AsExportAssignment()
		result["IsExportEquals"] = n.IsExportEquals
	case KindExportSpecifier:
		n := node.AsExportSpecifier()
		result["IsTypeOnly"] = n.IsTypeOnly
	case KindStringLiteral:
		n := node.AsStringLiteral()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
		result["TokenFlags"] = uint32(n.TokenFlags)
	case KindNumericLiteral:
		n := node.AsNumericLiteral()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
		result["TokenFlags"] = uint32(n.TokenFlags)
	case KindBigIntLiteral:
		n := node.AsBigIntLiteral()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
		result["TokenFlags"] = uint32(n.TokenFlags)
	case KindRegularExpressionLiteral:
		n := node.AsRegularExpressionLiteral()
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
		result["TokenFlags"] = uint32(n.TokenFlags)
	case KindNoSubstitutionTemplateLiteral:
		n := node.AsNoSubstitutionTemplateLiteral()
		result["TemplateFlags"] = uint32(n.TemplateFlags)
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindPrefixUnaryExpression:
		n := node.AsPrefixUnaryExpression()
		result["Operator"] = int(n.Operator)
	case KindPostfixUnaryExpression:
		n := node.AsPostfixUnaryExpression()
		result["Operator"] = int(n.Operator)
	case KindMetaProperty:
		n := node.AsMetaProperty()
		result["KeywordToken"] = int(n.KeywordToken)
	case KindArrayLiteralExpression:
		n := node.AsArrayLiteralExpression()
		result["MultiLine"] = n.MultiLine
	case KindObjectLiteralExpression:
		n := node.AsObjectLiteralExpression()
		result["MultiLine"] = n.MultiLine
	case KindTypeOperator:
		n := node.AsTypeOperatorNode()
		result["Operator"] = int(n.Operator)
	case KindImportAttributes:
		n := node.AsImportAttributes()
		result["MultiLine"] = n.MultiLine
		result["Token"] = int(n.Token)
	case KindTemplateHead:
		n := node.AsTemplateHead()
		result["RawText"] = base64.StdEncoding.EncodeToString([]byte(n.RawText))
		result["TemplateFlags"] = uint32(n.TemplateFlags)
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindTemplateMiddle:
		n := node.AsTemplateMiddle()
		result["RawText"] = base64.StdEncoding.EncodeToString([]byte(n.RawText))
		result["TemplateFlags"] = uint32(n.TemplateFlags)
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindTemplateTail:
		n := node.AsTemplateTail()
		result["RawText"] = base64.StdEncoding.EncodeToString([]byte(n.RawText))
		result["TemplateFlags"] = uint32(n.TemplateFlags)
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindSyntheticExpression:
		n := node.AsSyntheticExpression()
		result["IsSpread"] = n.IsSpread
		if n.Type != nil {
			panic("Cannot serialize semantic state SyntheticExpression.Type as parser syntax")
		}
		result["Type"] = nil
	case KindJsxText:
		n := node.AsJsxText()
		result["ContainsOnlyTriviaWhiteSpaces"] = n.ContainsOnlyTriviaWhiteSpaces
		result["Text"] = base64.StdEncoding.EncodeToString([]byte(n.Text))
	case KindModuleDeclaration:
		n := node.AsModuleDeclaration()
		result["Keyword"] = int(n.Keyword)
	case KindImportEqualsDeclaration:
		n := node.AsImportEqualsDeclaration()
		result["IsTypeOnly"] = n.IsTypeOnly
	case KindExportDeclaration:
		n := node.AsExportDeclaration()
		result["IsTypeOnly"] = n.IsTypeOnly
	case KindImportType:
		n := node.AsImportTypeNode()
		result["IsTypeOf"] = n.IsTypeOf
	case KindImportClause:
		n := node.AsImportClause()
		result["PhaseModifier"] = int(n.PhaseModifier)
	case KindImportSpecifier:
		n := node.AsImportSpecifier()
		result["IsTypeOnly"] = n.IsTypeOnly
	case KindJSDocText:
		n := node.AsJSDocText()
		text := make([]string, len(n.text))
		for i, value := range n.text {
			text[i] = base64.StdEncoding.EncodeToString([]byte(value))
		}
		result["Text"] = text
	case KindJSDocLink:
		n := node.AsJSDocLink()
		text := make([]string, len(n.text))
		for i, value := range n.text {
			text[i] = base64.StdEncoding.EncodeToString([]byte(value))
		}
		result["Text"] = text
	case KindJSDocLinkPlain:
		n := node.AsJSDocLinkPlain()
		text := make([]string, len(n.text))
		for i, value := range n.text {
			text[i] = base64.StdEncoding.EncodeToString([]byte(value))
		}
		result["Text"] = text
	case KindJSDocLinkCode:
		n := node.AsJSDocLinkCode()
		text := make([]string, len(n.text))
		for i, value := range n.text {
			text[i] = base64.StdEncoding.EncodeToString([]byte(value))
		}
		result["Text"] = text
	case KindJSDocTypeLiteral:
		n := node.AsJSDocTypeLiteral()
		result["IsArrayType"] = n.IsArrayType
	case KindJSDocParameterTag, KindJSDocPropertyTag:
		n := node.AsJSDocParameterOrPropertyTag()
		result["IsBracketed"] = n.IsBracketed
		result["IsNameFirst"] = n.IsNameFirst
	}
	return result
}

func CSharpListProperties(node *Node, position func(int) int) map[string]any {
	result := map[string]any{}
	listValue := func(list *NodeList) any {
		if list == nil {
			return nil
		}
		return []any{len(list.Nodes), position(list.Pos()), position(list.End()), list.HasTrailingComma()}
	}
	switch node.Kind {
	case KindCaseBlock:
		n := node.AsCaseBlock()
		result["Clauses"] = listValue(n.Clauses)
	case KindCaseClause, KindDefaultClause:
		n := node.AsCaseOrDefaultClause()
		result["Statements"] = listValue(n.Statements)
	case KindBlock:
		n := node.AsBlock()
		result["Statements"] = listValue(n.Statements)
	case KindVariableStatement:
		n := node.AsVariableStatement()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindVariableDeclarationList:
		n := node.AsVariableDeclarationList()
		result["Declarations"] = listValue(n.Declarations)
	case KindObjectBindingPattern, KindArrayBindingPattern:
		n := node.AsBindingPattern()
		result["Elements"] = listValue(n.Elements)
	case KindParameter:
		n := node.AsParameterDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindMissingDeclaration:
		n := node.AsMissingDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindFunctionDeclaration:
		n := node.AsFunctionDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindClassDeclaration:
		n := node.AsClassDeclaration()
		result["HeritageClauses"] = listValue(n.HeritageClauses)
		result["Members"] = listValue(n.Members)
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindClassExpression:
		n := node.AsClassExpression()
		result["HeritageClauses"] = listValue(n.HeritageClauses)
		result["Members"] = listValue(n.Members)
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindHeritageClause:
		n := node.AsHeritageClause()
		result["Types"] = listValue(n.Types)
	case KindInterfaceDeclaration:
		n := node.AsInterfaceDeclaration()
		result["HeritageClauses"] = listValue(n.HeritageClauses)
		result["Members"] = listValue(n.Members)
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindTypeAliasDeclaration, KindJSTypeAliasDeclaration:
		n := node.AsTypeAliasDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindEnumDeclaration:
		n := node.AsEnumDeclaration()
		result["Members"] = listValue(n.Members)
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindModuleBlock:
		n := node.AsModuleBlock()
		result["Statements"] = listValue(n.Statements)
	case KindImportDeclaration, KindJSImportDeclaration:
		n := node.AsImportDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindNamedImports:
		n := node.AsNamedImports()
		result["Elements"] = listValue(n.Elements)
	case KindExportAssignment:
		n := node.AsExportAssignment()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindNamespaceExportDeclaration:
		n := node.AsNamespaceExportDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindNamedExports:
		n := node.AsNamedExports()
		result["Elements"] = listValue(n.Elements)
	case KindCallSignature:
		n := node.AsCallSignatureDeclaration()
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindConstructSignature:
		n := node.AsConstructSignatureDeclaration()
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindConstructor:
		n := node.AsConstructorDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindGetAccessor:
		n := node.AsGetAccessorDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindSetAccessor:
		n := node.AsSetAccessorDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindIndexSignature:
		n := node.AsIndexSignatureDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
	case KindMethodSignature:
		n := node.AsMethodSignatureDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindMethodDeclaration:
		n := node.AsMethodDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindPropertySignature:
		n := node.AsPropertySignatureDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindPropertyDeclaration:
		n := node.AsPropertyDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindClassStaticBlockDeclaration:
		n := node.AsClassStaticBlockDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindBinaryExpression:
		n := node.AsBinaryExpression()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindArrowFunction:
		n := node.AsArrowFunction()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindFunctionExpression:
		n := node.AsFunctionExpression()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindCallExpression:
		n := node.AsCallExpression()
		result["Arguments"] = listValue(n.Arguments)
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindNewExpression:
		n := node.AsNewExpression()
		result["Arguments"] = listValue(n.Arguments)
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindTemplateExpression:
		n := node.AsTemplateExpression()
		result["TemplateSpans"] = listValue(n.TemplateSpans)
	case KindTaggedTemplateExpression:
		n := node.AsTaggedTemplateExpression()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindArrayLiteralExpression:
		n := node.AsArrayLiteralExpression()
		result["Elements"] = listValue(n.Elements)
	case KindObjectLiteralExpression:
		n := node.AsObjectLiteralExpression()
		result["Properties"] = listValue(n.Properties)
	case KindPropertyAssignment:
		n := node.AsPropertyAssignment()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindShorthandPropertyAssignment:
		n := node.AsShorthandPropertyAssignment()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindUnionType:
		n := node.AsUnionTypeNode()
		result["Types"] = listValue(n.Types)
	case KindIntersectionType:
		n := node.AsIntersectionTypeNode()
		result["Types"] = listValue(n.Types)
	case KindTypeReference:
		n := node.AsTypeReferenceNode()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindExpressionWithTypeArguments:
		n := node.AsExpressionWithTypeArguments()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindImportAttributes:
		n := node.AsImportAttributes()
		result["Attributes"] = listValue(n.Attributes)
	case KindTypeQuery:
		n := node.AsTypeQueryNode()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindMappedType:
		n := node.AsMappedTypeNode()
		result["Members"] = listValue(n.Members)
	case KindTypeLiteral:
		n := node.AsTypeLiteralNode()
		result["Members"] = listValue(n.Members)
	case KindTupleType:
		n := node.AsTupleTypeNode()
		result["Elements"] = listValue(n.Elements)
	case KindFunctionType:
		n := node.AsFunctionTypeNode()
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindConstructorType:
		n := node.AsConstructorTypeNode()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindTemplateLiteralType:
		n := node.AsTemplateLiteralTypeNode()
		result["TemplateSpans"] = listValue(n.TemplateSpans)
	case KindJsxElement:
		n := node.AsJsxElement()
		result["Children"] = listValue(n.Children)
	case KindJsxAttributes:
		n := node.AsJsxAttributes()
		result["Properties"] = listValue(n.Properties)
	case KindJsxOpeningElement:
		n := node.AsJsxOpeningElement()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindJsxSelfClosingElement:
		n := node.AsJsxSelfClosingElement()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindJsxFragment:
		n := node.AsJsxFragment()
		result["Children"] = listValue(n.Children)
	case KindJSDoc:
		n := node.AsJSDoc()
		result["Comment"] = listValue(n.Comment)
		result["Tags"] = listValue(n.Tags)
	case KindJSDocTypeTag:
		n := node.AsJSDocTypeTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocUnknownTag:
		n := node.AsJSDocUnknownTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocTemplateTag:
		n := node.AsJSDocTemplateTag()
		result["Comment"] = listValue(n.Comment)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindJSDocReturnTag:
		n := node.AsJSDocReturnTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocPublicTag:
		n := node.AsJSDocPublicTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocPrivateTag:
		n := node.AsJSDocPrivateTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocProtectedTag:
		n := node.AsJSDocProtectedTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocReadonlyTag:
		n := node.AsJSDocReadonlyTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocOverrideTag:
		n := node.AsJSDocOverrideTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocDeprecatedTag:
		n := node.AsJSDocDeprecatedTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocSeeTag:
		n := node.AsJSDocSeeTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocImplementsTag:
		n := node.AsJSDocImplementsTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocAugmentsTag:
		n := node.AsJSDocAugmentsTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocSatisfiesTag:
		n := node.AsJSDocSatisfiesTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocThrowsTag:
		n := node.AsJSDocThrowsTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocThisTag:
		n := node.AsJSDocThisTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocImportTag:
		n := node.AsJSDocImportTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocCallbackTag:
		n := node.AsJSDocCallbackTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocOverloadTag:
		n := node.AsJSDocOverloadTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocTypedefTag:
		n := node.AsJSDocTypedefTag()
		result["Comment"] = listValue(n.Comment)
	case KindJSDocSignature:
		n := node.AsJSDocSignature()
		result["Parameters"] = listValue(n.Parameters)
		result["TypeParameters"] = listValue(n.TypeParameters)
	case KindSourceFile:
		n := node.AsSourceFile()
		result["Statements"] = listValue(n.Statements)
	case KindModuleDeclaration:
		n := node.AsModuleDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindImportEqualsDeclaration:
		n := node.AsImportEqualsDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindExportDeclaration:
		n := node.AsExportDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindImportType:
		n := node.AsImportTypeNode()
		result["TypeArguments"] = listValue(n.TypeArguments)
	case KindTypeParameter:
		n := node.AsTypeParameterDeclaration()
		if n.modifiers == nil {
			result["Modifiers"] = nil
		} else {
			result["Modifiers"] = listValue(&n.modifiers.NodeList)
		}
	case KindJSDocParameterTag, KindJSDocPropertyTag:
		n := node.AsJSDocParameterOrPropertyTag()
		result["Comment"] = listValue(n.Comment)
	}
	return result
}
