// <auto-generated />
// ast.json SHA256 9ab3dfc6a2ff155ec1e315c6fee3deba8fe77c74256761ed38f475296a569574
using TypeScript.Compiler.Storage;
namespace TypeScript.Compiler.Syntax;

public readonly record struct SourceFileData(NodeId Statements, NodeId EndOfFileToken) : INodePayload<SourceFileData>
{
    public static int Tag => 1;
    public int ChildSlots => 2;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Statements,
        1 => EndOfFileToken,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct IdentifierData(Utf8String Text) : INodePayload<IdentifierData>
{
    public static int Tag => 2;
    public int ChildSlots => 0;
    public NodeId ChildAt(int slot) => slot switch
    {
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct KeywordTypeNodeData() : INodePayload<KeywordTypeNodeData>
{
    public static int Tag => 3;
    public int ChildSlots => 0;
    public NodeId ChildAt(int slot) => slot switch
    {
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct TokenData() : INodePayload<TokenData>
{
    public static int Tag => 4;
    public int ChildSlots => 0;
    public NodeId ChildAt(int slot) => slot switch
    {
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct StringLiteralData(Utf8String Text, uint TokenFlags) : INodePayload<StringLiteralData>
{
    public static int Tag => 5;
    public int ChildSlots => 0;
    public NodeId ChildAt(int slot) => slot switch
    {
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct NumericLiteralData(Utf8String Text, uint TokenFlags) : INodePayload<NumericLiteralData>
{
    public static int Tag => 6;
    public int ChildSlots => 0;
    public NodeId ChildAt(int slot) => slot switch
    {
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct LiteralTypeNodeData(NodeId Literal) : INodePayload<LiteralTypeNodeData>
{
    public static int Tag => 7;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Literal,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct UnionTypeNodeData(NodeId Types) : INodePayload<UnionTypeNodeData>
{
    public static int Tag => 8;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Types,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct ParenthesizedTypeNodeData(NodeId Type) : INodePayload<ParenthesizedTypeNodeData>
{
    public static int Tag => 9;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Type,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct TypeReferenceNodeData(NodeId TypeName, NodeId TypeArguments) : INodePayload<TypeReferenceNodeData>
{
    public static int Tag => 10;
    public int ChildSlots => 2;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => TypeName,
        1 => TypeArguments,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct TypeAliasDeclarationData(NodeId Modifiers, NodeId Name, NodeId TypeParameters, NodeId Type) : INodePayload<TypeAliasDeclarationData>
{
    public static int Tag => 11;
    public int ChildSlots => 4;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Modifiers,
        1 => Name,
        2 => TypeParameters,
        3 => Type,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct ImportDeclarationData(NodeId Modifiers, NodeId ImportClause, NodeId ModuleSpecifier, NodeId Attributes) : INodePayload<ImportDeclarationData>
{
    public static int Tag => 12;
    public int ChildSlots => 4;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Modifiers,
        1 => ImportClause,
        2 => ModuleSpecifier,
        3 => Attributes,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct ImportClauseData(SyntaxKind PhaseModifier, NodeId Name, NodeId NamedBindings) : INodePayload<ImportClauseData>
{
    public static int Tag => 13;
    public int ChildSlots => 2;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Name,
        1 => NamedBindings,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct NamedImportsData(NodeId Elements) : INodePayload<NamedImportsData>
{
    public static int Tag => 14;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Elements,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct ImportSpecifierData(bool IsTypeOnly, NodeId PropertyName, NodeId Name) : INodePayload<ImportSpecifierData>
{
    public static int Tag => 15;
    public int ChildSlots => 2;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => PropertyName,
        1 => Name,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct VariableStatementData(NodeId Modifiers, NodeId DeclarationList) : INodePayload<VariableStatementData>
{
    public static int Tag => 16;
    public int ChildSlots => 2;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Modifiers,
        1 => DeclarationList,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct VariableDeclarationListData(NodeId Declarations) : INodePayload<VariableDeclarationListData>
{
    public static int Tag => 17;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Declarations,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct VariableDeclarationData(NodeId Name, NodeId ExclamationToken, NodeId Type, NodeId Initializer) : INodePayload<VariableDeclarationData>
{
    public static int Tag => 18;
    public int ChildSlots => 4;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Name,
        1 => ExclamationToken,
        2 => Type,
        3 => Initializer,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public readonly record struct PrefixUnaryExpressionData(SyntaxKind Operator, NodeId Operand) : INodePayload<PrefixUnaryExpressionData>
{
    public static int Tag => 19;
    public int ChildSlots => 1;
    public NodeId ChildAt(int slot) => slot switch
    {
        0 => Operand,
        _ => throw new ArgumentOutOfRangeException(nameof(slot)),
    };
}

public static class SliceSchema
{
    public const int PayloadCount = 21;
    public static Utf8String KeywordText(SyntaxKind kind) => kind is >= SyntaxKind.FirstKeyword and <= SyntaxKind.LastKeyword
        ? TokenFacts.Text(kind) : throw new InvalidDataException("Expected keyword");
    public static int ChildSlots<TStore>(TStore store, NodeId id) where TStore : INodeStore => store.Tag(id) switch
    {
        1 => store.Get<SourceFileData>(id).ChildSlots,
        2 => store.Get<IdentifierData>(id).ChildSlots,
        3 => store.Get<KeywordTypeNodeData>(id).ChildSlots,
        4 => store.Get<TokenData>(id).ChildSlots,
        5 => store.Get<StringLiteralData>(id).ChildSlots,
        6 => store.Get<NumericLiteralData>(id).ChildSlots,
        7 => store.Get<LiteralTypeNodeData>(id).ChildSlots,
        8 => store.Get<UnionTypeNodeData>(id).ChildSlots,
        9 => store.Get<ParenthesizedTypeNodeData>(id).ChildSlots,
        10 => store.Get<TypeReferenceNodeData>(id).ChildSlots,
        11 => store.Get<TypeAliasDeclarationData>(id).ChildSlots,
        12 => store.Get<ImportDeclarationData>(id).ChildSlots,
        13 => store.Get<ImportClauseData>(id).ChildSlots,
        14 => store.Get<NamedImportsData>(id).ChildSlots,
        15 => store.Get<ImportSpecifierData>(id).ChildSlots,
        16 => store.Get<VariableStatementData>(id).ChildSlots,
        17 => store.Get<VariableDeclarationListData>(id).ChildSlots,
        18 => store.Get<VariableDeclarationData>(id).ChildSlots,
        19 => store.Get<PrefixUnaryExpressionData>(id).ChildSlots,
        0 => store.Get<NodeListData>(id).Nodes.Length,
        _ => throw new InvalidDataException("Unknown syntax payload"),
    };
    public static NodeId ChildAt<TStore>(TStore store, NodeId id, int slot) where TStore : INodeStore => store.Tag(id) switch
    {
        1 => store.Get<SourceFileData>(id).ChildAt(slot),
        2 => store.Get<IdentifierData>(id).ChildAt(slot),
        3 => store.Get<KeywordTypeNodeData>(id).ChildAt(slot),
        4 => store.Get<TokenData>(id).ChildAt(slot),
        5 => store.Get<StringLiteralData>(id).ChildAt(slot),
        6 => store.Get<NumericLiteralData>(id).ChildAt(slot),
        7 => store.Get<LiteralTypeNodeData>(id).ChildAt(slot),
        8 => store.Get<UnionTypeNodeData>(id).ChildAt(slot),
        9 => store.Get<ParenthesizedTypeNodeData>(id).ChildAt(slot),
        10 => store.Get<TypeReferenceNodeData>(id).ChildAt(slot),
        11 => store.Get<TypeAliasDeclarationData>(id).ChildAt(slot),
        12 => store.Get<ImportDeclarationData>(id).ChildAt(slot),
        13 => store.Get<ImportClauseData>(id).ChildAt(slot),
        14 => store.Get<NamedImportsData>(id).ChildAt(slot),
        15 => store.Get<ImportSpecifierData>(id).ChildAt(slot),
        16 => store.Get<VariableStatementData>(id).ChildAt(slot),
        17 => store.Get<VariableDeclarationListData>(id).ChildAt(slot),
        18 => store.Get<VariableDeclarationData>(id).ChildAt(slot),
        19 => store.Get<PrefixUnaryExpressionData>(id).ChildAt(slot),
        0 => store.Get<NodeListData>(id).Nodes[slot],
        _ => throw new InvalidDataException("Unknown syntax payload"),
    };
    public static NodeId Copy<TSource, TTarget>(TSource source, TTarget target, NodeId id, IReadOnlyDictionary<NodeId, NodeId> copies) where TSource : INodeStore where TTarget : INodeStore
    {
        NodeId Map(NodeId child) => child.IsNull ? default : copies[child];
        switch (source.Tag(id))
        {
            case 1:
            {
                var payload = source.Get<SourceFileData>(id);
                return target.Add(source.Header(id), payload with { Statements = Map(payload.Statements), EndOfFileToken = Map(payload.EndOfFileToken) });
            }
            case 2:
            {
                var payload = source.Get<IdentifierData>(id);
                return target.Add(source.Header(id), payload);
            }
            case 3:
            {
                var payload = source.Get<KeywordTypeNodeData>(id);
                return target.Add(source.Header(id), payload);
            }
            case 4:
            {
                var payload = source.Get<TokenData>(id);
                return target.Add(source.Header(id), payload);
            }
            case 5:
            {
                var payload = source.Get<StringLiteralData>(id);
                return target.Add(source.Header(id), payload);
            }
            case 6:
            {
                var payload = source.Get<NumericLiteralData>(id);
                return target.Add(source.Header(id), payload);
            }
            case 7:
            {
                var payload = source.Get<LiteralTypeNodeData>(id);
                return target.Add(source.Header(id), payload with { Literal = Map(payload.Literal) });
            }
            case 8:
            {
                var payload = source.Get<UnionTypeNodeData>(id);
                return target.Add(source.Header(id), payload with { Types = Map(payload.Types) });
            }
            case 9:
            {
                var payload = source.Get<ParenthesizedTypeNodeData>(id);
                return target.Add(source.Header(id), payload with { Type = Map(payload.Type) });
            }
            case 10:
            {
                var payload = source.Get<TypeReferenceNodeData>(id);
                return target.Add(source.Header(id), payload with { TypeName = Map(payload.TypeName), TypeArguments = Map(payload.TypeArguments) });
            }
            case 11:
            {
                var payload = source.Get<TypeAliasDeclarationData>(id);
                return target.Add(source.Header(id), payload with { Modifiers = Map(payload.Modifiers), Name = Map(payload.Name), TypeParameters = Map(payload.TypeParameters), Type = Map(payload.Type) });
            }
            case 12:
            {
                var payload = source.Get<ImportDeclarationData>(id);
                return target.Add(source.Header(id), payload with { Modifiers = Map(payload.Modifiers), ImportClause = Map(payload.ImportClause), ModuleSpecifier = Map(payload.ModuleSpecifier), Attributes = Map(payload.Attributes) });
            }
            case 13:
            {
                var payload = source.Get<ImportClauseData>(id);
                return target.Add(source.Header(id), payload with { Name = Map(payload.Name), NamedBindings = Map(payload.NamedBindings) });
            }
            case 14:
            {
                var payload = source.Get<NamedImportsData>(id);
                return target.Add(source.Header(id), payload with { Elements = Map(payload.Elements) });
            }
            case 15:
            {
                var payload = source.Get<ImportSpecifierData>(id);
                return target.Add(source.Header(id), payload with { PropertyName = Map(payload.PropertyName), Name = Map(payload.Name) });
            }
            case 16:
            {
                var payload = source.Get<VariableStatementData>(id);
                return target.Add(source.Header(id), payload with { Modifiers = Map(payload.Modifiers), DeclarationList = Map(payload.DeclarationList) });
            }
            case 17:
            {
                var payload = source.Get<VariableDeclarationListData>(id);
                return target.Add(source.Header(id), payload with { Declarations = Map(payload.Declarations) });
            }
            case 18:
            {
                var payload = source.Get<VariableDeclarationData>(id);
                return target.Add(source.Header(id), payload with { Name = Map(payload.Name), ExclamationToken = Map(payload.ExclamationToken), Type = Map(payload.Type), Initializer = Map(payload.Initializer) });
            }
            case 19:
            {
                var payload = source.Get<PrefixUnaryExpressionData>(id);
                return target.Add(source.Header(id), payload with { Operand = Map(payload.Operand) });
            }
            case 0:
            {
                var payload = source.Get<NodeListData>(id);
                return target.Add(source.Header(id), payload with { Nodes = Array.ConvertAll(payload.Nodes, Map) });
            }
            default: throw new InvalidDataException("Unknown syntax payload");
        }
    }
}
