// <auto-generated />
using TypeScript.Compiler.Text;
namespace TypeScript.Compiler.Syntax;
public static partial class TokenFacts
{
    public static SyntaxKind FromText(ReadOnlySpan<byte> text) => text.Length switch
    {
        1 => text[0] switch
        {
            (byte)'{' => SyntaxKind.OpenBraceToken,
            (byte)'}' => SyntaxKind.CloseBraceToken,
            (byte)'(' => SyntaxKind.OpenParenToken,
            (byte)')' => SyntaxKind.CloseParenToken,
            (byte)'[' => SyntaxKind.OpenBracketToken,
            (byte)']' => SyntaxKind.CloseBracketToken,
            (byte)'.' => SyntaxKind.DotToken,
            (byte)';' => SyntaxKind.SemicolonToken,
            (byte)',' => SyntaxKind.CommaToken,
            (byte)'<' => SyntaxKind.LessThanToken,
            (byte)'>' => SyntaxKind.GreaterThanToken,
            (byte)'+' => SyntaxKind.PlusToken,
            (byte)'-' => SyntaxKind.MinusToken,
            (byte)'*' => SyntaxKind.AsteriskToken,
            (byte)'/' => SyntaxKind.SlashToken,
            (byte)'%' => SyntaxKind.PercentToken,
            (byte)'&' => SyntaxKind.AmpersandToken,
            (byte)'|' => SyntaxKind.BarToken,
            (byte)'^' => SyntaxKind.CaretToken,
            (byte)'!' => SyntaxKind.ExclamationToken,
            (byte)'~' => SyntaxKind.TildeToken,
            (byte)'?' => SyntaxKind.QuestionToken,
            (byte)':' => SyntaxKind.ColonToken,
            (byte)'=' => SyntaxKind.EqualsToken,
            (byte)'@' => SyntaxKind.AtToken,
            (byte)'#' => SyntaxKind.HashToken,
            (byte)'`' => SyntaxKind.BacktickToken,
            _ => SyntaxKind.Unknown,
        },
        2 => text[0] switch
        {
            (byte)'a' => text.SequenceEqual("as"u8) ? SyntaxKind.AsKeyword : SyntaxKind.Unknown,
            (byte)'d' => text.SequenceEqual("do"u8) ? SyntaxKind.DoKeyword : SyntaxKind.Unknown,
            (byte)'i' => text.SequenceEqual("if"u8) ? SyntaxKind.IfKeyword : text.SequenceEqual("in"u8) ? SyntaxKind.InKeyword : text.SequenceEqual("is"u8) ? SyntaxKind.IsKeyword : SyntaxKind.Unknown,
            (byte)'o' => text.SequenceEqual("of"u8) ? SyntaxKind.OfKeyword : SyntaxKind.Unknown,
            (byte)'<' => text.SequenceEqual("<="u8) ? SyntaxKind.LessThanEqualsToken : text.SequenceEqual("<<"u8) ? SyntaxKind.LessThanLessThanToken : text.SequenceEqual("</"u8) ? SyntaxKind.LessThanSlashToken : SyntaxKind.Unknown,
            (byte)'>' => text.SequenceEqual(">="u8) ? SyntaxKind.GreaterThanEqualsToken : text.SequenceEqual(">>"u8) ? SyntaxKind.GreaterThanGreaterThanToken : SyntaxKind.Unknown,
            (byte)'=' => text.SequenceEqual("=="u8) ? SyntaxKind.EqualsEqualsToken : text.SequenceEqual("=>"u8) ? SyntaxKind.EqualsGreaterThanToken : SyntaxKind.Unknown,
            (byte)'!' => text.SequenceEqual("!="u8) ? SyntaxKind.ExclamationEqualsToken : SyntaxKind.Unknown,
            (byte)'*' => text.SequenceEqual("**"u8) ? SyntaxKind.AsteriskAsteriskToken : text.SequenceEqual("*="u8) ? SyntaxKind.AsteriskEqualsToken : SyntaxKind.Unknown,
            (byte)'+' => text.SequenceEqual("++"u8) ? SyntaxKind.PlusPlusToken : text.SequenceEqual("+="u8) ? SyntaxKind.PlusEqualsToken : SyntaxKind.Unknown,
            (byte)'-' => text.SequenceEqual("--"u8) ? SyntaxKind.MinusMinusToken : text.SequenceEqual("-="u8) ? SyntaxKind.MinusEqualsToken : SyntaxKind.Unknown,
            (byte)'&' => text.SequenceEqual("&&"u8) ? SyntaxKind.AmpersandAmpersandToken : text.SequenceEqual("&="u8) ? SyntaxKind.AmpersandEqualsToken : SyntaxKind.Unknown,
            (byte)'|' => text.SequenceEqual("||"u8) ? SyntaxKind.BarBarToken : text.SequenceEqual("|="u8) ? SyntaxKind.BarEqualsToken : SyntaxKind.Unknown,
            (byte)'?' => text.SequenceEqual("??"u8) ? SyntaxKind.QuestionQuestionToken : text.SequenceEqual("?."u8) ? SyntaxKind.QuestionDotToken : SyntaxKind.Unknown,
            (byte)'/' => text.SequenceEqual("/="u8) ? SyntaxKind.SlashEqualsToken : SyntaxKind.Unknown,
            (byte)'%' => text.SequenceEqual("%="u8) ? SyntaxKind.PercentEqualsToken : SyntaxKind.Unknown,
            (byte)'^' => text.SequenceEqual("^="u8) ? SyntaxKind.CaretEqualsToken : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        3 => text[0] switch
        {
            (byte)'a' => text.SequenceEqual("any"u8) ? SyntaxKind.AnyKeyword : SyntaxKind.Unknown,
            (byte)'f' => text.SequenceEqual("for"u8) ? SyntaxKind.ForKeyword : SyntaxKind.Unknown,
            (byte)'g' => text.SequenceEqual("get"u8) ? SyntaxKind.GetKeyword : SyntaxKind.Unknown,
            (byte)'l' => text.SequenceEqual("let"u8) ? SyntaxKind.LetKeyword : SyntaxKind.Unknown,
            (byte)'n' => text.SequenceEqual("new"u8) ? SyntaxKind.NewKeyword : SyntaxKind.Unknown,
            (byte)'o' => text.SequenceEqual("out"u8) ? SyntaxKind.OutKeyword : SyntaxKind.Unknown,
            (byte)'s' => text.SequenceEqual("set"u8) ? SyntaxKind.SetKeyword : SyntaxKind.Unknown,
            (byte)'t' => text.SequenceEqual("try"u8) ? SyntaxKind.TryKeyword : SyntaxKind.Unknown,
            (byte)'v' => text.SequenceEqual("var"u8) ? SyntaxKind.VarKeyword : SyntaxKind.Unknown,
            (byte)'.' => text.SequenceEqual("..."u8) ? SyntaxKind.DotDotDotToken : SyntaxKind.Unknown,
            (byte)'=' => text.SequenceEqual("==="u8) ? SyntaxKind.EqualsEqualsEqualsToken : SyntaxKind.Unknown,
            (byte)'!' => text.SequenceEqual("!=="u8) ? SyntaxKind.ExclamationEqualsEqualsToken : SyntaxKind.Unknown,
            (byte)'>' => text.SequenceEqual(">>>"u8) ? SyntaxKind.GreaterThanGreaterThanGreaterThanToken : text.SequenceEqual(">>="u8) ? SyntaxKind.GreaterThanGreaterThanEqualsToken : SyntaxKind.Unknown,
            (byte)'*' => text.SequenceEqual("**="u8) ? SyntaxKind.AsteriskAsteriskEqualsToken : SyntaxKind.Unknown,
            (byte)'<' => text.SequenceEqual("<<="u8) ? SyntaxKind.LessThanLessThanEqualsToken : SyntaxKind.Unknown,
            (byte)'|' => text.SequenceEqual("||="u8) ? SyntaxKind.BarBarEqualsToken : SyntaxKind.Unknown,
            (byte)'&' => text.SequenceEqual("&&="u8) ? SyntaxKind.AmpersandAmpersandEqualsToken : SyntaxKind.Unknown,
            (byte)'?' => text.SequenceEqual("??="u8) ? SyntaxKind.QuestionQuestionEqualsToken : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        4 => text[0] switch
        {
            (byte)'c' => text.SequenceEqual("case"u8) ? SyntaxKind.CaseKeyword : SyntaxKind.Unknown,
            (byte)'e' => text.SequenceEqual("else"u8) ? SyntaxKind.ElseKeyword : text.SequenceEqual("enum"u8) ? SyntaxKind.EnumKeyword : SyntaxKind.Unknown,
            (byte)'f' => text.SequenceEqual("from"u8) ? SyntaxKind.FromKeyword : SyntaxKind.Unknown,
            (byte)'n' => text.SequenceEqual("null"u8) ? SyntaxKind.NullKeyword : SyntaxKind.Unknown,
            (byte)'t' => text.SequenceEqual("this"u8) ? SyntaxKind.ThisKeyword : text.SequenceEqual("true"u8) ? SyntaxKind.TrueKeyword : text.SequenceEqual("type"u8) ? SyntaxKind.TypeKeyword : SyntaxKind.Unknown,
            (byte)'v' => text.SequenceEqual("void"u8) ? SyntaxKind.VoidKeyword : SyntaxKind.Unknown,
            (byte)'w' => text.SequenceEqual("with"u8) ? SyntaxKind.WithKeyword : SyntaxKind.Unknown,
            (byte)'>' => text.SequenceEqual(">>>="u8) ? SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        5 => text[0] switch
        {
            (byte)'b' => text.SequenceEqual("break"u8) ? SyntaxKind.BreakKeyword : SyntaxKind.Unknown,
            (byte)'c' => text.SequenceEqual("catch"u8) ? SyntaxKind.CatchKeyword : text.SequenceEqual("class"u8) ? SyntaxKind.ClassKeyword : text.SequenceEqual("const"u8) ? SyntaxKind.ConstKeyword : SyntaxKind.Unknown,
            (byte)'d' => text.SequenceEqual("defer"u8) ? SyntaxKind.DeferKeyword : SyntaxKind.Unknown,
            (byte)'f' => text.SequenceEqual("false"u8) ? SyntaxKind.FalseKeyword : SyntaxKind.Unknown,
            (byte)'i' => text.SequenceEqual("infer"u8) ? SyntaxKind.InferKeyword : SyntaxKind.Unknown,
            (byte)'k' => text.SequenceEqual("keyof"u8) ? SyntaxKind.KeyOfKeyword : SyntaxKind.Unknown,
            (byte)'n' => text.SequenceEqual("never"u8) ? SyntaxKind.NeverKeyword : SyntaxKind.Unknown,
            (byte)'s' => text.SequenceEqual("super"u8) ? SyntaxKind.SuperKeyword : SyntaxKind.Unknown,
            (byte)'t' => text.SequenceEqual("throw"u8) ? SyntaxKind.ThrowKeyword : SyntaxKind.Unknown,
            (byte)'u' => text.SequenceEqual("using"u8) ? SyntaxKind.UsingKeyword : SyntaxKind.Unknown,
            (byte)'w' => text.SequenceEqual("while"u8) ? SyntaxKind.WhileKeyword : SyntaxKind.Unknown,
            (byte)'y' => text.SequenceEqual("yield"u8) ? SyntaxKind.YieldKeyword : SyntaxKind.Unknown,
            (byte)'a' => text.SequenceEqual("async"u8) ? SyntaxKind.AsyncKeyword : text.SequenceEqual("await"u8) ? SyntaxKind.AwaitKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        6 => text[0] switch
        {
            (byte)'a' => text.SequenceEqual("assert"u8) ? SyntaxKind.AssertKeyword : SyntaxKind.Unknown,
            (byte)'b' => text.SequenceEqual("bigint"u8) ? SyntaxKind.BigIntKeyword : SyntaxKind.Unknown,
            (byte)'d' => text.SequenceEqual("delete"u8) ? SyntaxKind.DeleteKeyword : SyntaxKind.Unknown,
            (byte)'e' => text.SequenceEqual("export"u8) ? SyntaxKind.ExportKeyword : SyntaxKind.Unknown,
            (byte)'i' => text.SequenceEqual("import"u8) ? SyntaxKind.ImportKeyword : SyntaxKind.Unknown,
            (byte)'m' => text.SequenceEqual("module"u8) ? SyntaxKind.ModuleKeyword : SyntaxKind.Unknown,
            (byte)'n' => text.SequenceEqual("number"u8) ? SyntaxKind.NumberKeyword : SyntaxKind.Unknown,
            (byte)'o' => text.SequenceEqual("object"u8) ? SyntaxKind.ObjectKeyword : SyntaxKind.Unknown,
            (byte)'p' => text.SequenceEqual("public"u8) ? SyntaxKind.PublicKeyword : SyntaxKind.Unknown,
            (byte)'g' => text.SequenceEqual("global"u8) ? SyntaxKind.GlobalKeyword : SyntaxKind.Unknown,
            (byte)'r' => text.SequenceEqual("return"u8) ? SyntaxKind.ReturnKeyword : SyntaxKind.Unknown,
            (byte)'s' => text.SequenceEqual("static"u8) ? SyntaxKind.StaticKeyword : text.SequenceEqual("string"u8) ? SyntaxKind.StringKeyword : text.SequenceEqual("switch"u8) ? SyntaxKind.SwitchKeyword : text.SequenceEqual("symbol"u8) ? SyntaxKind.SymbolKeyword : SyntaxKind.Unknown,
            (byte)'t' => text.SequenceEqual("typeof"u8) ? SyntaxKind.TypeOfKeyword : SyntaxKind.Unknown,
            (byte)'u' => text.SequenceEqual("unique"u8) ? SyntaxKind.UniqueKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        7 => text[0] switch
        {
            (byte)'a' => text.SequenceEqual("asserts"u8) ? SyntaxKind.AssertsKeyword : SyntaxKind.Unknown,
            (byte)'b' => text.SequenceEqual("boolean"u8) ? SyntaxKind.BooleanKeyword : SyntaxKind.Unknown,
            (byte)'d' => text.SequenceEqual("declare"u8) ? SyntaxKind.DeclareKeyword : text.SequenceEqual("default"u8) ? SyntaxKind.DefaultKeyword : SyntaxKind.Unknown,
            (byte)'e' => text.SequenceEqual("extends"u8) ? SyntaxKind.ExtendsKeyword : SyntaxKind.Unknown,
            (byte)'f' => text.SequenceEqual("finally"u8) ? SyntaxKind.FinallyKeyword : SyntaxKind.Unknown,
            (byte)'p' => text.SequenceEqual("package"u8) ? SyntaxKind.PackageKeyword : text.SequenceEqual("private"u8) ? SyntaxKind.PrivateKeyword : SyntaxKind.Unknown,
            (byte)'r' => text.SequenceEqual("require"u8) ? SyntaxKind.RequireKeyword : SyntaxKind.Unknown,
            (byte)'u' => text.SequenceEqual("unknown"u8) ? SyntaxKind.UnknownKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        8 => text[0] switch
        {
            (byte)'a' => text.SequenceEqual("abstract"u8) ? SyntaxKind.AbstractKeyword : text.SequenceEqual("accessor"u8) ? SyntaxKind.AccessorKeyword : SyntaxKind.Unknown,
            (byte)'c' => text.SequenceEqual("continue"u8) ? SyntaxKind.ContinueKeyword : SyntaxKind.Unknown,
            (byte)'d' => text.SequenceEqual("debugger"u8) ? SyntaxKind.DebuggerKeyword : SyntaxKind.Unknown,
            (byte)'f' => text.SequenceEqual("function"u8) ? SyntaxKind.FunctionKeyword : SyntaxKind.Unknown,
            (byte)'o' => text.SequenceEqual("override"u8) ? SyntaxKind.OverrideKeyword : SyntaxKind.Unknown,
            (byte)'r' => text.SequenceEqual("readonly"u8) ? SyntaxKind.ReadonlyKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        9 => text[0] switch
        {
            (byte)'i' => text.SequenceEqual("immediate"u8) ? SyntaxKind.ImmediateKeyword : text.SequenceEqual("interface"u8) ? SyntaxKind.InterfaceKeyword : text.SequenceEqual("intrinsic"u8) ? SyntaxKind.IntrinsicKeyword : SyntaxKind.Unknown,
            (byte)'n' => text.SequenceEqual("namespace"u8) ? SyntaxKind.NamespaceKeyword : SyntaxKind.Unknown,
            (byte)'p' => text.SequenceEqual("protected"u8) ? SyntaxKind.ProtectedKeyword : SyntaxKind.Unknown,
            (byte)'s' => text.SequenceEqual("satisfies"u8) ? SyntaxKind.SatisfiesKeyword : SyntaxKind.Unknown,
            (byte)'u' => text.SequenceEqual("undefined"u8) ? SyntaxKind.UndefinedKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        10 => text[0] switch
        {
            (byte)'i' => text.SequenceEqual("implements"u8) ? SyntaxKind.ImplementsKeyword : text.SequenceEqual("instanceof"u8) ? SyntaxKind.InstanceOfKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        11 => text[0] switch
        {
            (byte)'c' => text.SequenceEqual("constructor"u8) ? SyntaxKind.ConstructorKeyword : SyntaxKind.Unknown,
            _ => SyntaxKind.Unknown,
        },
        _ => SyntaxKind.Unknown,
    };
    internal static SyntaxKind Punctuation(ReadOnlySpan<byte> text, out int length)
    {
        if (text.IsEmpty) { length = 0; return SyntaxKind.Unknown; }
        switch (text[0])
        {
            case (byte)'{':
                length = 1; return SyntaxKind.OpenBraceToken;
            case (byte)'}':
                length = 1; return SyntaxKind.CloseBraceToken;
            case (byte)'(':
                length = 1; return SyntaxKind.OpenParenToken;
            case (byte)')':
                length = 1; return SyntaxKind.CloseParenToken;
            case (byte)'[':
                length = 1; return SyntaxKind.OpenBracketToken;
            case (byte)']':
                length = 1; return SyntaxKind.CloseBracketToken;
            case (byte)'.':
                if (text.StartsWith("..."u8)) { length = 3; return SyntaxKind.DotDotDotToken; }
                length = 1; return SyntaxKind.DotToken;
            case (byte)';':
                length = 1; return SyntaxKind.SemicolonToken;
            case (byte)',':
                length = 1; return SyntaxKind.CommaToken;
            case (byte)'<':
                if (text.StartsWith("<<="u8)) { length = 3; return SyntaxKind.LessThanLessThanEqualsToken; }
                if (text.StartsWith("<="u8)) { length = 2; return SyntaxKind.LessThanEqualsToken; }
                if (text.StartsWith("<<"u8)) { length = 2; return SyntaxKind.LessThanLessThanToken; }
                if (text.StartsWith("</"u8)) { length = 2; return SyntaxKind.LessThanSlashToken; }
                length = 1; return SyntaxKind.LessThanToken;
            case (byte)'>':
                if (text.StartsWith(">>>="u8)) { length = 4; return SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken; }
                if (text.StartsWith(">>>"u8)) { length = 3; return SyntaxKind.GreaterThanGreaterThanGreaterThanToken; }
                if (text.StartsWith(">>="u8)) { length = 3; return SyntaxKind.GreaterThanGreaterThanEqualsToken; }
                if (text.StartsWith(">="u8)) { length = 2; return SyntaxKind.GreaterThanEqualsToken; }
                if (text.StartsWith(">>"u8)) { length = 2; return SyntaxKind.GreaterThanGreaterThanToken; }
                length = 1; return SyntaxKind.GreaterThanToken;
            case (byte)'=':
                if (text.StartsWith("==="u8)) { length = 3; return SyntaxKind.EqualsEqualsEqualsToken; }
                if (text.StartsWith("=="u8)) { length = 2; return SyntaxKind.EqualsEqualsToken; }
                if (text.StartsWith("=>"u8)) { length = 2; return SyntaxKind.EqualsGreaterThanToken; }
                length = 1; return SyntaxKind.EqualsToken;
            case (byte)'!':
                if (text.StartsWith("!=="u8)) { length = 3; return SyntaxKind.ExclamationEqualsEqualsToken; }
                if (text.StartsWith("!="u8)) { length = 2; return SyntaxKind.ExclamationEqualsToken; }
                length = 1; return SyntaxKind.ExclamationToken;
            case (byte)'+':
                if (text.StartsWith("++"u8)) { length = 2; return SyntaxKind.PlusPlusToken; }
                if (text.StartsWith("+="u8)) { length = 2; return SyntaxKind.PlusEqualsToken; }
                length = 1; return SyntaxKind.PlusToken;
            case (byte)'-':
                if (text.StartsWith("--"u8)) { length = 2; return SyntaxKind.MinusMinusToken; }
                if (text.StartsWith("-="u8)) { length = 2; return SyntaxKind.MinusEqualsToken; }
                length = 1; return SyntaxKind.MinusToken;
            case (byte)'*':
                if (text.StartsWith("**="u8)) { length = 3; return SyntaxKind.AsteriskAsteriskEqualsToken; }
                if (text.StartsWith("**"u8)) { length = 2; return SyntaxKind.AsteriskAsteriskToken; }
                if (text.StartsWith("*="u8)) { length = 2; return SyntaxKind.AsteriskEqualsToken; }
                length = 1; return SyntaxKind.AsteriskToken;
            case (byte)'/':
                if (text.StartsWith("/="u8)) { length = 2; return SyntaxKind.SlashEqualsToken; }
                length = 1; return SyntaxKind.SlashToken;
            case (byte)'%':
                if (text.StartsWith("%="u8)) { length = 2; return SyntaxKind.PercentEqualsToken; }
                length = 1; return SyntaxKind.PercentToken;
            case (byte)'&':
                if (text.StartsWith("&&="u8)) { length = 3; return SyntaxKind.AmpersandAmpersandEqualsToken; }
                if (text.StartsWith("&&"u8)) { length = 2; return SyntaxKind.AmpersandAmpersandToken; }
                if (text.StartsWith("&="u8)) { length = 2; return SyntaxKind.AmpersandEqualsToken; }
                length = 1; return SyntaxKind.AmpersandToken;
            case (byte)'|':
                if (text.StartsWith("||="u8)) { length = 3; return SyntaxKind.BarBarEqualsToken; }
                if (text.StartsWith("||"u8)) { length = 2; return SyntaxKind.BarBarToken; }
                if (text.StartsWith("|="u8)) { length = 2; return SyntaxKind.BarEqualsToken; }
                length = 1; return SyntaxKind.BarToken;
            case (byte)'^':
                if (text.StartsWith("^="u8)) { length = 2; return SyntaxKind.CaretEqualsToken; }
                length = 1; return SyntaxKind.CaretToken;
            case (byte)'~':
                length = 1; return SyntaxKind.TildeToken;
            case (byte)'?':
                if (text.StartsWith("??="u8)) { length = 3; return SyntaxKind.QuestionQuestionEqualsToken; }
                if (text.StartsWith("??"u8)) { length = 2; return SyntaxKind.QuestionQuestionToken; }
                if (text.StartsWith("?."u8)) { length = 2; return SyntaxKind.QuestionDotToken; }
                length = 1; return SyntaxKind.QuestionToken;
            case (byte)':':
                length = 1; return SyntaxKind.ColonToken;
            case (byte)'@':
                length = 1; return SyntaxKind.AtToken;
        }
        length = 0;
        return SyntaxKind.Unknown;
    }
    private static readonly Utf8String TextAbstractKeyword = Utf8String.Copy("abstract"u8);
    private static readonly Utf8String TextAccessorKeyword = Utf8String.Copy("accessor"u8);
    private static readonly Utf8String TextAnyKeyword = Utf8String.Copy("any"u8);
    private static readonly Utf8String TextAsKeyword = Utf8String.Copy("as"u8);
    private static readonly Utf8String TextAssertsKeyword = Utf8String.Copy("asserts"u8);
    private static readonly Utf8String TextAssertKeyword = Utf8String.Copy("assert"u8);
    private static readonly Utf8String TextBigIntKeyword = Utf8String.Copy("bigint"u8);
    private static readonly Utf8String TextBooleanKeyword = Utf8String.Copy("boolean"u8);
    private static readonly Utf8String TextBreakKeyword = Utf8String.Copy("break"u8);
    private static readonly Utf8String TextCaseKeyword = Utf8String.Copy("case"u8);
    private static readonly Utf8String TextCatchKeyword = Utf8String.Copy("catch"u8);
    private static readonly Utf8String TextClassKeyword = Utf8String.Copy("class"u8);
    private static readonly Utf8String TextContinueKeyword = Utf8String.Copy("continue"u8);
    private static readonly Utf8String TextConstKeyword = Utf8String.Copy("const"u8);
    private static readonly Utf8String TextConstructorKeyword = Utf8String.Copy("constructor"u8);
    private static readonly Utf8String TextDebuggerKeyword = Utf8String.Copy("debugger"u8);
    private static readonly Utf8String TextDeclareKeyword = Utf8String.Copy("declare"u8);
    private static readonly Utf8String TextDefaultKeyword = Utf8String.Copy("default"u8);
    private static readonly Utf8String TextDeferKeyword = Utf8String.Copy("defer"u8);
    private static readonly Utf8String TextDeleteKeyword = Utf8String.Copy("delete"u8);
    private static readonly Utf8String TextDoKeyword = Utf8String.Copy("do"u8);
    private static readonly Utf8String TextElseKeyword = Utf8String.Copy("else"u8);
    private static readonly Utf8String TextEnumKeyword = Utf8String.Copy("enum"u8);
    private static readonly Utf8String TextExportKeyword = Utf8String.Copy("export"u8);
    private static readonly Utf8String TextExtendsKeyword = Utf8String.Copy("extends"u8);
    private static readonly Utf8String TextFalseKeyword = Utf8String.Copy("false"u8);
    private static readonly Utf8String TextFinallyKeyword = Utf8String.Copy("finally"u8);
    private static readonly Utf8String TextForKeyword = Utf8String.Copy("for"u8);
    private static readonly Utf8String TextFromKeyword = Utf8String.Copy("from"u8);
    private static readonly Utf8String TextFunctionKeyword = Utf8String.Copy("function"u8);
    private static readonly Utf8String TextGetKeyword = Utf8String.Copy("get"u8);
    private static readonly Utf8String TextIfKeyword = Utf8String.Copy("if"u8);
    private static readonly Utf8String TextImmediateKeyword = Utf8String.Copy("immediate"u8);
    private static readonly Utf8String TextImplementsKeyword = Utf8String.Copy("implements"u8);
    private static readonly Utf8String TextImportKeyword = Utf8String.Copy("import"u8);
    private static readonly Utf8String TextInKeyword = Utf8String.Copy("in"u8);
    private static readonly Utf8String TextInferKeyword = Utf8String.Copy("infer"u8);
    private static readonly Utf8String TextInstanceOfKeyword = Utf8String.Copy("instanceof"u8);
    private static readonly Utf8String TextInterfaceKeyword = Utf8String.Copy("interface"u8);
    private static readonly Utf8String TextIntrinsicKeyword = Utf8String.Copy("intrinsic"u8);
    private static readonly Utf8String TextIsKeyword = Utf8String.Copy("is"u8);
    private static readonly Utf8String TextKeyOfKeyword = Utf8String.Copy("keyof"u8);
    private static readonly Utf8String TextLetKeyword = Utf8String.Copy("let"u8);
    private static readonly Utf8String TextModuleKeyword = Utf8String.Copy("module"u8);
    private static readonly Utf8String TextNamespaceKeyword = Utf8String.Copy("namespace"u8);
    private static readonly Utf8String TextNeverKeyword = Utf8String.Copy("never"u8);
    private static readonly Utf8String TextNewKeyword = Utf8String.Copy("new"u8);
    private static readonly Utf8String TextNullKeyword = Utf8String.Copy("null"u8);
    private static readonly Utf8String TextNumberKeyword = Utf8String.Copy("number"u8);
    private static readonly Utf8String TextObjectKeyword = Utf8String.Copy("object"u8);
    private static readonly Utf8String TextPackageKeyword = Utf8String.Copy("package"u8);
    private static readonly Utf8String TextPrivateKeyword = Utf8String.Copy("private"u8);
    private static readonly Utf8String TextProtectedKeyword = Utf8String.Copy("protected"u8);
    private static readonly Utf8String TextPublicKeyword = Utf8String.Copy("public"u8);
    private static readonly Utf8String TextOverrideKeyword = Utf8String.Copy("override"u8);
    private static readonly Utf8String TextOutKeyword = Utf8String.Copy("out"u8);
    private static readonly Utf8String TextReadonlyKeyword = Utf8String.Copy("readonly"u8);
    private static readonly Utf8String TextRequireKeyword = Utf8String.Copy("require"u8);
    private static readonly Utf8String TextGlobalKeyword = Utf8String.Copy("global"u8);
    private static readonly Utf8String TextReturnKeyword = Utf8String.Copy("return"u8);
    private static readonly Utf8String TextSatisfiesKeyword = Utf8String.Copy("satisfies"u8);
    private static readonly Utf8String TextSetKeyword = Utf8String.Copy("set"u8);
    private static readonly Utf8String TextStaticKeyword = Utf8String.Copy("static"u8);
    private static readonly Utf8String TextStringKeyword = Utf8String.Copy("string"u8);
    private static readonly Utf8String TextSuperKeyword = Utf8String.Copy("super"u8);
    private static readonly Utf8String TextSwitchKeyword = Utf8String.Copy("switch"u8);
    private static readonly Utf8String TextSymbolKeyword = Utf8String.Copy("symbol"u8);
    private static readonly Utf8String TextThisKeyword = Utf8String.Copy("this"u8);
    private static readonly Utf8String TextThrowKeyword = Utf8String.Copy("throw"u8);
    private static readonly Utf8String TextTrueKeyword = Utf8String.Copy("true"u8);
    private static readonly Utf8String TextTryKeyword = Utf8String.Copy("try"u8);
    private static readonly Utf8String TextTypeKeyword = Utf8String.Copy("type"u8);
    private static readonly Utf8String TextTypeOfKeyword = Utf8String.Copy("typeof"u8);
    private static readonly Utf8String TextUndefinedKeyword = Utf8String.Copy("undefined"u8);
    private static readonly Utf8String TextUniqueKeyword = Utf8String.Copy("unique"u8);
    private static readonly Utf8String TextUnknownKeyword = Utf8String.Copy("unknown"u8);
    private static readonly Utf8String TextUsingKeyword = Utf8String.Copy("using"u8);
    private static readonly Utf8String TextVarKeyword = Utf8String.Copy("var"u8);
    private static readonly Utf8String TextVoidKeyword = Utf8String.Copy("void"u8);
    private static readonly Utf8String TextWhileKeyword = Utf8String.Copy("while"u8);
    private static readonly Utf8String TextWithKeyword = Utf8String.Copy("with"u8);
    private static readonly Utf8String TextYieldKeyword = Utf8String.Copy("yield"u8);
    private static readonly Utf8String TextAsyncKeyword = Utf8String.Copy("async"u8);
    private static readonly Utf8String TextAwaitKeyword = Utf8String.Copy("await"u8);
    private static readonly Utf8String TextOfKeyword = Utf8String.Copy("of"u8);
    private static readonly Utf8String TextOpenBraceToken = Utf8String.Copy("{"u8);
    private static readonly Utf8String TextCloseBraceToken = Utf8String.Copy("}"u8);
    private static readonly Utf8String TextOpenParenToken = Utf8String.Copy("("u8);
    private static readonly Utf8String TextCloseParenToken = Utf8String.Copy(")"u8);
    private static readonly Utf8String TextOpenBracketToken = Utf8String.Copy("["u8);
    private static readonly Utf8String TextCloseBracketToken = Utf8String.Copy("]"u8);
    private static readonly Utf8String TextDotToken = Utf8String.Copy("."u8);
    private static readonly Utf8String TextDotDotDotToken = Utf8String.Copy("..."u8);
    private static readonly Utf8String TextSemicolonToken = Utf8String.Copy(";"u8);
    private static readonly Utf8String TextCommaToken = Utf8String.Copy(","u8);
    private static readonly Utf8String TextLessThanToken = Utf8String.Copy("<"u8);
    private static readonly Utf8String TextGreaterThanToken = Utf8String.Copy(">"u8);
    private static readonly Utf8String TextLessThanEqualsToken = Utf8String.Copy("<="u8);
    private static readonly Utf8String TextGreaterThanEqualsToken = Utf8String.Copy(">="u8);
    private static readonly Utf8String TextEqualsEqualsToken = Utf8String.Copy("=="u8);
    private static readonly Utf8String TextExclamationEqualsToken = Utf8String.Copy("!="u8);
    private static readonly Utf8String TextEqualsEqualsEqualsToken = Utf8String.Copy("==="u8);
    private static readonly Utf8String TextExclamationEqualsEqualsToken = Utf8String.Copy("!=="u8);
    private static readonly Utf8String TextEqualsGreaterThanToken = Utf8String.Copy("=>"u8);
    private static readonly Utf8String TextPlusToken = Utf8String.Copy("+"u8);
    private static readonly Utf8String TextMinusToken = Utf8String.Copy("-"u8);
    private static readonly Utf8String TextAsteriskAsteriskToken = Utf8String.Copy("**"u8);
    private static readonly Utf8String TextAsteriskToken = Utf8String.Copy("*"u8);
    private static readonly Utf8String TextSlashToken = Utf8String.Copy("/"u8);
    private static readonly Utf8String TextPercentToken = Utf8String.Copy("%"u8);
    private static readonly Utf8String TextPlusPlusToken = Utf8String.Copy("++"u8);
    private static readonly Utf8String TextMinusMinusToken = Utf8String.Copy("--"u8);
    private static readonly Utf8String TextLessThanLessThanToken = Utf8String.Copy("<<"u8);
    private static readonly Utf8String TextLessThanSlashToken = Utf8String.Copy("</"u8);
    private static readonly Utf8String TextGreaterThanGreaterThanToken = Utf8String.Copy(">>"u8);
    private static readonly Utf8String TextGreaterThanGreaterThanGreaterThanToken = Utf8String.Copy(">>>"u8);
    private static readonly Utf8String TextAmpersandToken = Utf8String.Copy("&"u8);
    private static readonly Utf8String TextBarToken = Utf8String.Copy("|"u8);
    private static readonly Utf8String TextCaretToken = Utf8String.Copy("^"u8);
    private static readonly Utf8String TextExclamationToken = Utf8String.Copy("!"u8);
    private static readonly Utf8String TextTildeToken = Utf8String.Copy("~"u8);
    private static readonly Utf8String TextAmpersandAmpersandToken = Utf8String.Copy("&&"u8);
    private static readonly Utf8String TextBarBarToken = Utf8String.Copy("||"u8);
    private static readonly Utf8String TextQuestionToken = Utf8String.Copy("?"u8);
    private static readonly Utf8String TextQuestionQuestionToken = Utf8String.Copy("??"u8);
    private static readonly Utf8String TextQuestionDotToken = Utf8String.Copy("?."u8);
    private static readonly Utf8String TextColonToken = Utf8String.Copy(":"u8);
    private static readonly Utf8String TextEqualsToken = Utf8String.Copy("="u8);
    private static readonly Utf8String TextPlusEqualsToken = Utf8String.Copy("+="u8);
    private static readonly Utf8String TextMinusEqualsToken = Utf8String.Copy("-="u8);
    private static readonly Utf8String TextAsteriskEqualsToken = Utf8String.Copy("*="u8);
    private static readonly Utf8String TextAsteriskAsteriskEqualsToken = Utf8String.Copy("**="u8);
    private static readonly Utf8String TextSlashEqualsToken = Utf8String.Copy("/="u8);
    private static readonly Utf8String TextPercentEqualsToken = Utf8String.Copy("%="u8);
    private static readonly Utf8String TextLessThanLessThanEqualsToken = Utf8String.Copy("<<="u8);
    private static readonly Utf8String TextGreaterThanGreaterThanEqualsToken = Utf8String.Copy(">>="u8);
    private static readonly Utf8String TextGreaterThanGreaterThanGreaterThanEqualsToken = Utf8String.Copy(">>>="u8);
    private static readonly Utf8String TextAmpersandEqualsToken = Utf8String.Copy("&="u8);
    private static readonly Utf8String TextBarEqualsToken = Utf8String.Copy("|="u8);
    private static readonly Utf8String TextCaretEqualsToken = Utf8String.Copy("^="u8);
    private static readonly Utf8String TextBarBarEqualsToken = Utf8String.Copy("||="u8);
    private static readonly Utf8String TextAmpersandAmpersandEqualsToken = Utf8String.Copy("&&="u8);
    private static readonly Utf8String TextQuestionQuestionEqualsToken = Utf8String.Copy("??="u8);
    private static readonly Utf8String TextAtToken = Utf8String.Copy("@"u8);
    private static readonly Utf8String TextHashToken = Utf8String.Copy("#"u8);
    private static readonly Utf8String TextBacktickToken = Utf8String.Copy("`"u8);
    public static Utf8String Text(SyntaxKind kind) => kind switch
    {
        SyntaxKind.AbstractKeyword => TextAbstractKeyword,
        SyntaxKind.AccessorKeyword => TextAccessorKeyword,
        SyntaxKind.AnyKeyword => TextAnyKeyword,
        SyntaxKind.AsKeyword => TextAsKeyword,
        SyntaxKind.AssertsKeyword => TextAssertsKeyword,
        SyntaxKind.AssertKeyword => TextAssertKeyword,
        SyntaxKind.BigIntKeyword => TextBigIntKeyword,
        SyntaxKind.BooleanKeyword => TextBooleanKeyword,
        SyntaxKind.BreakKeyword => TextBreakKeyword,
        SyntaxKind.CaseKeyword => TextCaseKeyword,
        SyntaxKind.CatchKeyword => TextCatchKeyword,
        SyntaxKind.ClassKeyword => TextClassKeyword,
        SyntaxKind.ContinueKeyword => TextContinueKeyword,
        SyntaxKind.ConstKeyword => TextConstKeyword,
        SyntaxKind.ConstructorKeyword => TextConstructorKeyword,
        SyntaxKind.DebuggerKeyword => TextDebuggerKeyword,
        SyntaxKind.DeclareKeyword => TextDeclareKeyword,
        SyntaxKind.DefaultKeyword => TextDefaultKeyword,
        SyntaxKind.DeferKeyword => TextDeferKeyword,
        SyntaxKind.DeleteKeyword => TextDeleteKeyword,
        SyntaxKind.DoKeyword => TextDoKeyword,
        SyntaxKind.ElseKeyword => TextElseKeyword,
        SyntaxKind.EnumKeyword => TextEnumKeyword,
        SyntaxKind.ExportKeyword => TextExportKeyword,
        SyntaxKind.ExtendsKeyword => TextExtendsKeyword,
        SyntaxKind.FalseKeyword => TextFalseKeyword,
        SyntaxKind.FinallyKeyword => TextFinallyKeyword,
        SyntaxKind.ForKeyword => TextForKeyword,
        SyntaxKind.FromKeyword => TextFromKeyword,
        SyntaxKind.FunctionKeyword => TextFunctionKeyword,
        SyntaxKind.GetKeyword => TextGetKeyword,
        SyntaxKind.IfKeyword => TextIfKeyword,
        SyntaxKind.ImmediateKeyword => TextImmediateKeyword,
        SyntaxKind.ImplementsKeyword => TextImplementsKeyword,
        SyntaxKind.ImportKeyword => TextImportKeyword,
        SyntaxKind.InKeyword => TextInKeyword,
        SyntaxKind.InferKeyword => TextInferKeyword,
        SyntaxKind.InstanceOfKeyword => TextInstanceOfKeyword,
        SyntaxKind.InterfaceKeyword => TextInterfaceKeyword,
        SyntaxKind.IntrinsicKeyword => TextIntrinsicKeyword,
        SyntaxKind.IsKeyword => TextIsKeyword,
        SyntaxKind.KeyOfKeyword => TextKeyOfKeyword,
        SyntaxKind.LetKeyword => TextLetKeyword,
        SyntaxKind.ModuleKeyword => TextModuleKeyword,
        SyntaxKind.NamespaceKeyword => TextNamespaceKeyword,
        SyntaxKind.NeverKeyword => TextNeverKeyword,
        SyntaxKind.NewKeyword => TextNewKeyword,
        SyntaxKind.NullKeyword => TextNullKeyword,
        SyntaxKind.NumberKeyword => TextNumberKeyword,
        SyntaxKind.ObjectKeyword => TextObjectKeyword,
        SyntaxKind.PackageKeyword => TextPackageKeyword,
        SyntaxKind.PrivateKeyword => TextPrivateKeyword,
        SyntaxKind.ProtectedKeyword => TextProtectedKeyword,
        SyntaxKind.PublicKeyword => TextPublicKeyword,
        SyntaxKind.OverrideKeyword => TextOverrideKeyword,
        SyntaxKind.OutKeyword => TextOutKeyword,
        SyntaxKind.ReadonlyKeyword => TextReadonlyKeyword,
        SyntaxKind.RequireKeyword => TextRequireKeyword,
        SyntaxKind.GlobalKeyword => TextGlobalKeyword,
        SyntaxKind.ReturnKeyword => TextReturnKeyword,
        SyntaxKind.SatisfiesKeyword => TextSatisfiesKeyword,
        SyntaxKind.SetKeyword => TextSetKeyword,
        SyntaxKind.StaticKeyword => TextStaticKeyword,
        SyntaxKind.StringKeyword => TextStringKeyword,
        SyntaxKind.SuperKeyword => TextSuperKeyword,
        SyntaxKind.SwitchKeyword => TextSwitchKeyword,
        SyntaxKind.SymbolKeyword => TextSymbolKeyword,
        SyntaxKind.ThisKeyword => TextThisKeyword,
        SyntaxKind.ThrowKeyword => TextThrowKeyword,
        SyntaxKind.TrueKeyword => TextTrueKeyword,
        SyntaxKind.TryKeyword => TextTryKeyword,
        SyntaxKind.TypeKeyword => TextTypeKeyword,
        SyntaxKind.TypeOfKeyword => TextTypeOfKeyword,
        SyntaxKind.UndefinedKeyword => TextUndefinedKeyword,
        SyntaxKind.UniqueKeyword => TextUniqueKeyword,
        SyntaxKind.UnknownKeyword => TextUnknownKeyword,
        SyntaxKind.UsingKeyword => TextUsingKeyword,
        SyntaxKind.VarKeyword => TextVarKeyword,
        SyntaxKind.VoidKeyword => TextVoidKeyword,
        SyntaxKind.WhileKeyword => TextWhileKeyword,
        SyntaxKind.WithKeyword => TextWithKeyword,
        SyntaxKind.YieldKeyword => TextYieldKeyword,
        SyntaxKind.AsyncKeyword => TextAsyncKeyword,
        SyntaxKind.AwaitKeyword => TextAwaitKeyword,
        SyntaxKind.OfKeyword => TextOfKeyword,
        SyntaxKind.OpenBraceToken => TextOpenBraceToken,
        SyntaxKind.CloseBraceToken => TextCloseBraceToken,
        SyntaxKind.OpenParenToken => TextOpenParenToken,
        SyntaxKind.CloseParenToken => TextCloseParenToken,
        SyntaxKind.OpenBracketToken => TextOpenBracketToken,
        SyntaxKind.CloseBracketToken => TextCloseBracketToken,
        SyntaxKind.DotToken => TextDotToken,
        SyntaxKind.DotDotDotToken => TextDotDotDotToken,
        SyntaxKind.SemicolonToken => TextSemicolonToken,
        SyntaxKind.CommaToken => TextCommaToken,
        SyntaxKind.LessThanToken => TextLessThanToken,
        SyntaxKind.GreaterThanToken => TextGreaterThanToken,
        SyntaxKind.LessThanEqualsToken => TextLessThanEqualsToken,
        SyntaxKind.GreaterThanEqualsToken => TextGreaterThanEqualsToken,
        SyntaxKind.EqualsEqualsToken => TextEqualsEqualsToken,
        SyntaxKind.ExclamationEqualsToken => TextExclamationEqualsToken,
        SyntaxKind.EqualsEqualsEqualsToken => TextEqualsEqualsEqualsToken,
        SyntaxKind.ExclamationEqualsEqualsToken => TextExclamationEqualsEqualsToken,
        SyntaxKind.EqualsGreaterThanToken => TextEqualsGreaterThanToken,
        SyntaxKind.PlusToken => TextPlusToken,
        SyntaxKind.MinusToken => TextMinusToken,
        SyntaxKind.AsteriskAsteriskToken => TextAsteriskAsteriskToken,
        SyntaxKind.AsteriskToken => TextAsteriskToken,
        SyntaxKind.SlashToken => TextSlashToken,
        SyntaxKind.PercentToken => TextPercentToken,
        SyntaxKind.PlusPlusToken => TextPlusPlusToken,
        SyntaxKind.MinusMinusToken => TextMinusMinusToken,
        SyntaxKind.LessThanLessThanToken => TextLessThanLessThanToken,
        SyntaxKind.LessThanSlashToken => TextLessThanSlashToken,
        SyntaxKind.GreaterThanGreaterThanToken => TextGreaterThanGreaterThanToken,
        SyntaxKind.GreaterThanGreaterThanGreaterThanToken => TextGreaterThanGreaterThanGreaterThanToken,
        SyntaxKind.AmpersandToken => TextAmpersandToken,
        SyntaxKind.BarToken => TextBarToken,
        SyntaxKind.CaretToken => TextCaretToken,
        SyntaxKind.ExclamationToken => TextExclamationToken,
        SyntaxKind.TildeToken => TextTildeToken,
        SyntaxKind.AmpersandAmpersandToken => TextAmpersandAmpersandToken,
        SyntaxKind.BarBarToken => TextBarBarToken,
        SyntaxKind.QuestionToken => TextQuestionToken,
        SyntaxKind.QuestionQuestionToken => TextQuestionQuestionToken,
        SyntaxKind.QuestionDotToken => TextQuestionDotToken,
        SyntaxKind.ColonToken => TextColonToken,
        SyntaxKind.EqualsToken => TextEqualsToken,
        SyntaxKind.PlusEqualsToken => TextPlusEqualsToken,
        SyntaxKind.MinusEqualsToken => TextMinusEqualsToken,
        SyntaxKind.AsteriskEqualsToken => TextAsteriskEqualsToken,
        SyntaxKind.AsteriskAsteriskEqualsToken => TextAsteriskAsteriskEqualsToken,
        SyntaxKind.SlashEqualsToken => TextSlashEqualsToken,
        SyntaxKind.PercentEqualsToken => TextPercentEqualsToken,
        SyntaxKind.LessThanLessThanEqualsToken => TextLessThanLessThanEqualsToken,
        SyntaxKind.GreaterThanGreaterThanEqualsToken => TextGreaterThanGreaterThanEqualsToken,
        SyntaxKind.GreaterThanGreaterThanGreaterThanEqualsToken => TextGreaterThanGreaterThanGreaterThanEqualsToken,
        SyntaxKind.AmpersandEqualsToken => TextAmpersandEqualsToken,
        SyntaxKind.BarEqualsToken => TextBarEqualsToken,
        SyntaxKind.CaretEqualsToken => TextCaretEqualsToken,
        SyntaxKind.BarBarEqualsToken => TextBarBarEqualsToken,
        SyntaxKind.AmpersandAmpersandEqualsToken => TextAmpersandAmpersandEqualsToken,
        SyntaxKind.QuestionQuestionEqualsToken => TextQuestionQuestionEqualsToken,
        SyntaxKind.AtToken => TextAtToken,
        SyntaxKind.HashToken => TextHashToken,
        SyntaxKind.BacktickToken => TextBacktickToken,
        _ => default,
    };
}
